<div id="gameEvent">
    <!-- box HEADER START -->
    <div class="wrap-top-left clearfix">
        <div class="wrap-top-right clearfix">
            <div class="wrap-top-middle clearfix"></div>
        </div>
    </div>
    <!-- box HEADER END -->
    <!-- box CONTENT START -->
    <div class="wrap-left clearfix">
        <div class="wrap-content wrap-right clearfix">
            <!-- CONTENT START -->
            <h2><img src="/img/symbols/race1small.gif" alt="">The Magical Sacrificial Bowl</h2>

            <img src="/img/gameEvent/moon_blessing.jpg" class="gameEventImage">

            <p class="bold">
                Curious things have been happening in the county of late. The people are singing songs of spring, preparing sacrifices for a great festival, whilst a child roves around the city at night, seemingly searching for something. The scent of fresh meat hangs in the air...</p>

            <ul>
                <li>
                    Set out on the hunt for a lost artefact in an Easter tale                        </li>
                <li>
                    Discover a new side of the city, its residents and yourself                        </li>
                <li>
                    Find additional crystal eggs in the game and win Gold and Hellstones!                    </li>
                <li>
                    +50% energy regeneration                    </li>
                <li>
                    +100% maximum health points                    </li>
                <li>
                    +100% health point regeneration                    </li>
            </ul>

            <br clear="both">

            <p class="highlight bold" style="text-align:center;">
                The event continues:    <span id="countdown_event_07c1066cb16db2e86dd77173a42af2577723eadd" class="hasCountdown"><span class="countdown_row countdown_amount">5d 16:52:27</span></span>
                <script type="text/javascript">
                    $('#countdown_event_07c1066cb16db2e86dd77173a42af2577723eadd').countdown({
                        until: +492772,
                        compact: true, compactLabels: ['y', 'm', 'w', 'd'],
                        description: ''
                    });
                </script>
            </p>

            <!-- CONTENT END -->
        </div>
    </div>
    <!-- box CONTENT END -->
    <!-- box FOOTER START -->
    <div class="wrap-bottom-left">
        <div class="wrap-bottom-right">
            <div class="wrap-bottom-middle"></div>
        </div>
    </div>
    <!-- box CONTENT END -->
</div>