<?php if(isset($user)): ?>
<div id="infobar">
    <!-- box HEADER START -->
    <div class="wrap-top-left clearfix">
        <div class="wrap-top-right clearfix">
            <div class="wrap-top-middle clearfix"></div>
        </div>
    </div>
    <!-- box HEADER END -->
    <!-- box CONTENT START -->
    <div class="wrap-left clearfix">
        <div class="wrap-content wrap-right clearfix">
            <div class="gold" style="margin-bottom:0px;">
                <?php echo prettyNumber($user->gold); ?>&nbsp;<img src="<?php echo getAssetLink('img/symbols/res2.gif'); ?>" alt="Gold" align="absmiddle" border="0">&nbsp;&nbsp;
                <?php echo prettyNumber($user->hellstone); ?>&nbsp;<img src="<?php echo getAssetLink('img/symbols/res3.gif'); ?>" alt="Hellstones" align="absmiddle" border="0"></a>&nbsp;&nbsp;
                <?php echo prettyNumber($user->fragment); ?>&nbsp;<img src="<?php echo getAssetLink('img/symbols/res_splinters.png'); ?>" alt="Fragments" align="absmiddle" border="0"></a>&nbsp;&nbsp;
                <?php echo prettyNumber($user->ap_now); ?>&nbsp;/&nbsp;<?php echo prettyNumber($user->ap_max); ?>&nbsp;<img src="<?php echo getAssetLink('img/symbols/ap.gif'); ?>" alt="Action points" align="absmiddle" border="0">&nbsp;&nbsp;
                <?php echo prettyNumber($user->hp_now); ?>&nbsp;/&nbsp;<?php echo prettyNumber($user->hp_max); ?>&nbsp;<img src="<?php echo getAssetLink('img/symbols/herz.png'); ?>" alt="Health" align="absmiddle" border="0">&nbsp;&nbsp;
                <img src="<?php echo getAssetLink('img/symbols/level.gif'); ?>" alt="Level" align="absmiddle" border="0">&nbsp;<?php echo prettyNumber(getLevel($user->exp)); ?>&nbsp;&nbsp;
                <img src="<?php echo getAssetLink('img/symbols/fightvalue.gif'); ?>" alt="Battle value" align="absmiddle" border="0">&nbsp;<?php echo prettyNumber($user->battle_value); ?></div>
        </div>
    </div>
    <div class="wrap-bottom-left">
        <div class="wrap-bottom-right">
            <div class="wrap-bottom-middle"></div>
        </div>
    </div>
</div>
<br/>
<?php endif; ?>
