<?php if(isset($user)): ?>
<div id="infobar">
    <!-- box HEADER START -->
    <div class="wrap-top-left clearfix">
        <div class="wrap-top-right clearfix">
            <div class="wrap-top-middle clearfix"></div>
        </div>
    </div>
    <!-- box HEADER END -->
    <!-- box CONTENT START -->
    <div class="wrap-left clearfix">
        <div class="wrap-content wrap-right clearfix">
            <div class="gold" style="margin-bottom:0px;">
                4.541&nbsp;<img src="<?php echo getAssetLink('img/symbols/res2.gif'); ?>" alt="Gold" align="absmiddle" border="0">&nbsp;&nbsp;
                3&nbsp;<img src="<?php echo getAssetLink('img/symbols/res3.gif'); ?>" alt="Hellstones" align="absmiddle" border="0"></a>&nbsp;&nbsp;
                3.213&nbsp;<img src="<?php echo getAssetLink('img/symbols/res_splinters.png'); ?>" alt="Fragments" align="absmiddle" border="0"></a>&nbsp;&nbsp;
                126&nbsp;/&nbsp;126&nbsp;<img src="<?php echo getAssetLink('img/symbols/ap.gif'); ?>" alt="Action points" align="absmiddle" border="0">&nbsp;&nbsp;
                157.100&nbsp;/&nbsp;157.100&nbsp;<img src="<?php echo getAssetLink('img/symbols/herz.png'); ?>" alt="Health" align="absmiddle" border="0">&nbsp;&nbsp;
                <img src="<?php echo getAssetLink('img/symbols/level.gif'); ?>" alt="Level" align="absmiddle" border="0">&nbsp;258&nbsp;&nbsp;
                <img src="<?php echo getAssetLink('img/symbols/fightvalue.gif'); ?>" alt="Battle value" align="absmiddle" border="0">&nbsp;2923</div>
        </div>
    </div>
    <div class="wrap-bottom-left">
        <div class="wrap-bottom-right">
            <div class="wrap-bottom-middle"></div>
        </div>
    </div>
</div>
<br/>
<?php endif; ?>
