<?php if(isset($user)): ?>
<div id="infobar">
    <div class="wrap-top-left clearfix">
        <div class="wrap-top-right clearfix">
            <div class="wrap-top-middle clearfix"></div>
        </div>
    </div>
    <div class="wrap-left clearfix">
        <div class="wrap-content wrap-right clearfix">
            <div class="gold" style="margin-bottom:0px;">
                <?php echo prettyNumber($user->gold); ?>&nbsp;<img src="<?php echo getAssetLink('img/symbols/res2.gif'); ?>" alt="<?php echo \Bitefight\Library\Translate::_('menu_infobar_gold'); ?>" align="absmiddle" border="0">&nbsp;&nbsp;
                <?php echo prettyNumber($user->hellstone); ?>&nbsp;<img src="<?php echo getAssetLink('img/symbols/res3.gif'); ?>" alt="<?php echo \Bitefight\Library\Translate::_('menu_infobar_hellstone'); ?>" align="absmiddle" border="0"></a>&nbsp;&nbsp;
                <?php echo prettyNumber($user->fragment); ?>&nbsp;<img src="<?php echo getAssetLink('img/symbols/res_splinters.png'); ?>" alt="<?php echo \Bitefight\Library\Translate::_('menu_infobar_fragments'); ?>" align="absmiddle" border="0"></a>&nbsp;&nbsp;
                <?php echo prettyNumber(floor($user->ap_now)); ?>&nbsp;/&nbsp;<?php echo prettyNumber($user->ap_max); ?>&nbsp;<img src="<?php echo getAssetLink('img/symbols/ap.gif'); ?>" alt="<?php echo \Bitefight\Library\Translate::_('menu_infobar_action_points'); ?>" align="absmiddle" border="0">&nbsp;&nbsp;
                <?php echo prettyNumber(floor($user->hp_now)); ?>&nbsp;/&nbsp;<?php echo prettyNumber($user->hp_max); ?>&nbsp;<img src="<?php echo getAssetLink('img/symbols/herz.png'); ?>" alt="<?php echo \Bitefight\Library\Translate::_('menu_infobar_health'); ?>" align="absmiddle" border="0">&nbsp;&nbsp;
                <img src="<?php echo getAssetLink('img/symbols/level.gif'); ?>" alt="<?php echo \Bitefight\Library\Translate::_('menu_infobar_level'); ?>" align="absmiddle" border="0">&nbsp;<?php echo prettyNumber(getLevel($user->exp)); ?>&nbsp;&nbsp;
                <img src="<?php echo getAssetLink('img/symbols/fightvalue.gif'); ?>" alt="<?php echo \Bitefight\Library\Translate::_('menu_infobar_battle_value'); ?>" align="absmiddle" border="0">&nbsp;<?php echo prettyNumber(getLevel($user->exp) * 4 + $user->str + $user->def + $user->dex + $user->end + $user->cha + $user->talent_points * 12); ?></div>
        </div>
    </div>
    <div class="wrap-bottom-left">
        <div class="wrap-bottom-right">
            <div class="wrap-bottom-middle"></div>
        </div>
    </div>
</div>
<br/>
<?php endif; ?>
