<?php if (!isset($user)): ?>
    <ul id="menuHead">
        <li <?php if ($menu_active == 'news') echo 'class="active"'; ?>><a href="<?php echo getUrl('news'); ?>" target="_top" class="newmessage"><?php echo \Bitefight\Library\Translate::_('menu_news'); ?></a></li>
        <!--<li><a href="<?php echo getUrl('news'); ?>" target="_blank"><?php echo \Bitefight\Library\Translate::_('menu_support'); ?></a></li>-->
        <li <?php if ($menu_active == 'register') echo 'class="active"'; ?>><a href="<?php echo getUrl('register/0'); ?>" target="_top"><?php echo \Bitefight\Library\Translate::_('menu_register'); ?></a></li>
        <li <?php if ($menu_active == 'login') echo 'class="active"'; ?>><a href="<?php echo getUrl('login'); ?>" target="_top"><?php echo \Bitefight\Library\Translate::_('menu_login'); ?></a></li>
        <!--<li><a href="<?php echo getUrl('news'); ?>" target="_blank"><?php echo \Bitefight\Library\Translate::_('menu_forum'); ?></a></li>-->
        <li <?php if ($menu_active == 'highscore') echo 'class="active"'; ?>><a href="<?php echo getUrl('highscore'); ?>" target="_top"><?php echo \Bitefight\Library\Translate::_('menu_highscore'); ?></a></li>
        <li id="time">09.01.2017 12:07</li>
        <script type="text/javascript">
            var $menuHead = $('#menuHead'),
                $active = $menuHead.find('.active');
            var currentPage = $active.text();

            if (currentPage) {
                $('#header').find('h1').text(currentPage);
            }

            $(document).ready(function () {
                $menuHead.find('li').on('click', function () {
                    $active.removeClass('active');
                    $(this).addClass('active');
                });
            });
        </script>
    </ul>
<?php else: ?>
    <ul id="menuHead">
        <li <?php if ($menu_active == 'news') echo 'class="active"'; ?>><a href="<?php echo getUrl('news'); ?>" target="_top" class=""><?php echo \Bitefight\Library\Translate::_('menu_news'); ?></a></li>
        <li <?php if ($menu_active == 'profile') echo 'class="active"'; ?>><a href="<?php echo getUrl('profile'); ?>" target="_top"><?php echo \Bitefight\Library\Translate::_('menu_overview'); ?></a></li>
        <li <?php if ($menu_active == 'message') echo 'class="active"'; ?>><a href="<?php echo getUrl('message'); ?>" target="_top" <?php if($user_new_message_count) echo 'class="newmessage"'; ?> id="msgmenu"><?php echo \Bitefight\Library\Translate::_('menu_message'); ?></a></li>
        <li <?php if ($menu_active == 'hideout') echo 'class="active"'; ?>><a href="<?php echo getUrl('hideout'); ?>" target="_top"><?php echo \Bitefight\Library\Translate::_('menu_hideout'); ?></a></li>
        <li <?php if ($menu_active == 'city') echo 'class="active"'; ?>><a href="<?php echo getUrl('city/index'); ?>" target="_top"><?php echo \Bitefight\Library\Translate::_('menu_city'); ?></a></li>
        <li class="free-space <?php if ($menu_active == 'hunt') echo 'active'; ?>"><a href="<?php echo getUrl('hunt/index'); ?>" target="_top"><?php echo \Bitefight\Library\Translate::_('menu_hunt'); ?></a></li>
        <!--<li id="premium" <?php if ($menu_active == 'register') echo 'class="active"'; ?>>
            <img border="0" src="<?php echo getAssetLink('img/voodoo/res3_rotation.gif'); ?>">
            <a href="<?php echo getUrl('profile'); ?>" target="_top"><?php echo \Bitefight\Library\Translate::_('menu_voodoo_shop'); ?></a>
        </li>-->
        <li <?php if ($menu_active == 'clan') echo 'class="active"'; ?>><a href="<?php echo getUrl('clan/index'); ?>" target="_top"><?php echo \Bitefight\Library\Translate::_('menu_clan'); ?></a></li>
        <!--<li <?php if ($menu_active == 'register') echo 'class="active"'; ?>><a href="<?php echo getUrl('profile'); ?>" target="_top"><?php echo \Bitefight\Library\Translate::_('menu_buddy_list'); ?></a></li>-->
        <li <?php if ($menu_active == 'notepad') echo 'class="active"'; ?>><a href="<?php echo getUrl('notepad'); ?>" target="_top"><?php echo \Bitefight\Library\Translate::_('menu_notepad'); ?></a></li>
        <!--<li class="free-space "></li>-->
        <li <?php if ($menu_active == 'settings') echo 'class="active"'; ?>><a href="<?php echo getUrl('user/settings'); ?>" target="_top"><?php echo \Bitefight\Library\Translate::_('menu_settings'); ?></a></li>
        <!--<li><a href="<?php echo getUrl('profile'); ?>" target="_blank"><?php echo \Bitefight\Library\Translate::_('menu_forum'); ?></a></li>-->
        <li <?php if ($menu_active == 'highscore') echo 'class="active"'; ?>><a href="<?php echo getUrl('highscore'); ?>" target="_top"><?php echo \Bitefight\Library\Translate::_('menu_highscore'); ?></a></li>
        <li <?php if ($menu_active == 'search') echo 'class="active"'; ?>><a href="<?php echo getUrl('search'); ?>" target="_top"><?php echo \Bitefight\Library\Translate::_('menu_search'); ?></a></li>
        <!--<li class="free-space "><a href="<?php echo getUrl('profile'); ?>" target="_blank"><?php echo \Bitefight\Library\Translate::_('menu_support'); ?></a></li>-->
        <li><a href="<?php echo getUrl('logout'); ?>" target="_top"><?php echo \Bitefight\Library\Translate::_('menu_logout'); ?></a></li>
        <li id="time">14.01.2017 00:25</li>
        <script type="text/javascript">
            var $menuHead = $('#menuHead'),
                $active = $menuHead.find('.active');
            var currentPage = $active.text();

            if (currentPage) {
                $('#header').find('h1').text(currentPage);
            }

            $(document).ready(function () {
                $menuHead.find('li').on('click', function () {
                    $active.removeClass('active');
                    $(this).addClass('active');
                });
            });
        </script>
    </ul>
<?php endif; ?>