<?php if (!isset($user)): ?>
    <ul id="menuHead">
        <li <?php if ($menu_active == 'news') echo 'class="active"'; ?>><a href="<?php echo getUrl('news'); ?>" target="_top" class="newmessage">News</a></li>
        <!--<li><a href="<?php echo getUrl('news'); ?>" target="_blank">Support</a></li>-->
        <li <?php if ($menu_active == 'register') echo 'class="active"'; ?>><a href="<?php echo getUrl('register/0'); ?>" target="_top">Register</a></li>
        <li <?php if ($menu_active == 'login') echo 'class="active"'; ?>><a href="<?php echo getUrl('login'); ?>" target="_top">Login</a></li>
        <!--<li><a href="<?php echo getUrl('news'); ?>" target="_blank">Forum</a></li>-->
        <li <?php if ($menu_active == 'highscore') echo 'class="active"'; ?>><a href="<?php echo getUrl('highscore'); ?>" target="_top">Highscore</a></li>
        <li id="time">09.01.2017 12:07</li>
        <script type="text/javascript">
            var $menuHead = $('#menuHead'),
                $active = $menuHead.find('.active');
            var currentPage = $active.text();

            if (currentPage) {
                $('#header').find('h1').text(currentPage);
            }

            $(document).ready(function () {
                $menuHead.find('li').on('click', function () {
                    $active.removeClass('active');
                    $(this).addClass('active');
                });
            });
        </script>
    </ul>
<?php else: ?>
    <ul id="menuHead">
        <li <?php if ($menu_active == 'news') echo 'class="active"'; ?>><a href="<?php echo getUrl('news'); ?>" target="_top" class="">News</a></li>
        <li <?php if ($menu_active == 'profile') echo 'class="active"'; ?>><a href="<?php echo getUrl('profile'); ?>" target="_top">Overview</a></li>
        <!--<li <?php if ($menu_active == 'register') echo 'class="active"'; ?>><a href="<?php echo getUrl('profile'); ?>" target="_top" class="newmessage" id="msgmenu">Messages</a></li>-->
        <li <?php if ($menu_active == 'hideout') echo 'class="active"'; ?>><a href="<?php echo getUrl('hideout'); ?>" target="_top">Hideout</a></li>
        <li <?php if ($menu_active == 'city') echo 'class="active"'; ?>><a href="<?php echo getUrl('city/index'); ?>" target="_top">City</a></li>
        <li class="free-space <?php if ($menu_active == 'hunt') echo 'active'; ?>"><a href="<?php echo getUrl('hunt/index'); ?>" target="_top">Hunt</a></li>
        <!--<li id="premium" <?php if ($menu_active == 'register') echo 'class="active"'; ?>>
            <img border="0" src="<?php echo getAssetLink('img/voodoo/res3_rotation.gif'); ?>">
            <a href="<?php echo getUrl('profile'); ?>" target="_top">Voodoo Shop</a>
        </li>-->
        <li <?php if ($menu_active == 'clan') echo 'class="active"'; ?>><a href="<?php echo getUrl('clan/index'); ?>" target="_top">Clan</a></li>
        <!--<li <?php if ($menu_active == 'register') echo 'class="active"'; ?>><a href="<?php echo getUrl('profile'); ?>" target="_top">Buddy list</a></li>-->
        <li <?php if ($menu_active == 'notepad') echo 'class="active"'; ?>><a href="<?php echo getUrl('notepad'); ?>" target="_top">Notepad</a></li>
        <!--<li class="free-space "></li>-->
        <li <?php if ($menu_active == 'settings') echo 'class="active"'; ?>><a href="<?php echo getUrl('user/settings'); ?>" target="_top">Settings</a></li>
        <!--<li><a href="<?php echo getUrl('profile'); ?>" target="_blank">Forum</a></li>-->
        <li <?php if ($menu_active == 'highscore') echo 'class="active"'; ?>><a href="<?php echo getUrl('highscore'); ?>" target="_top">Highscore</a></li>
        <li <?php if ($menu_active == 'search') echo 'class="active"'; ?>><a href="<?php echo getUrl('search'); ?>" target="_top">Search</a></li>
        <!--<li class="free-space "><a href="<?php echo getUrl('profile'); ?>" target="_blank">Support</a></li>-->
        <li><a href="<?php echo getUrl('logout'); ?>" target="_top">Leave game</a></li>
        <li id="time">14.01.2017 00:25</li>
        <script type="text/javascript">
            var $menuHead = $('#menuHead'),
                $active = $menuHead.find('.active');
            var currentPage = $active.text();

            if (currentPage) {
                $('#header').find('h1').text(currentPage);
            }

            $(document).ready(function () {
                $menuHead.find('li').on('click', function () {
                    $active.removeClass('active');
                    $(this).addClass('active');
                });
            });
        </script>
    </ul>
<?php endif; ?>