<script type="text/javascript">
    var questBox = {
        questName: 'huntForShards',

        buttonClick: function() {
            var questButton = $("button#questButton");
            if (questButton.hasClass("nextPage")) {
                var allPages = $("div#questText>div.questPage");
                allPages.each(function(index) {
                    if ($(this).css("display") == "block") {
                        $(this).css("display", "none");
                        $(this).next().css("display", "block");
                        if (index == allPages.length - 2) {
                            questButton.removeClass("nextPage");
                            questButton.addClass("confirmQuest");
                        }
                        return false;
                    }
                });
            } else if (questButton.hasClass("confirmQuest")) {
                $.ajax({
                    type: 'GET',
                    url: '/ajax/gameevent/continueEasterQuest',
                    dataType: 'json',
                    success: function(data)
                    {
                        if (questBox.questName == "speedyRecovery") {
                            var url = "https://s202-en.bitefight.gameforge.com:443/city/index";
                            window.location.replace(url);
                        }
                        if (questBox.questName == "speedyRecovery2") {
                            $('div.littlegirl').removeClass('healingBrother').addClass('recoveredBrother');
                        }

                        //close window
                        questBox.close();
                        //set questmark
                        $("div#npcMark").removeClass();
                        if (typeof(data) != "undefined") {
                            if (typeof(data.newNpcMark) != "undefined") {
                                $("div#npcMark").addClass(data.newNpcMark);
                                if (data.newNpcMark == 'questInProgress') {
                                    $("button#questButton").removeClass("confirmQuest");
                                    $("button#questButton").addClass("closeBox");
                                }
                            }
                            if (typeof(data.newQuestText) != "undefined" && typeof(data.newQuestName) != "undefined") {
                                $("div#questText").html(data.newQuestText);
                                questBox.questName = data.newQuestName;
                                if ($("div#questText>div.questPage").length > 1) {
                                    $("button#questButton").removeClass("confirmQuest");
                                    $("button#questButton").addClass("nextPage");
                                }
                                if (questBox.questName == "happyEnd") {
                                    $('div#healthbar').remove();
                                }
                            }
                        }
                    },
                    data: {
                        questName: questBox.questName,
                        questLocation: 'popupvessel'
                    },
                    async: true
                });
            } else if (questButton.hasClass("closeBox")) {
                questBox.close();
            }
        }

    }
</script>

<script type="text/javascript">
    questBox.open = function() {
        $('div#questBoxPopup').css("display", "block");
    };
    questBox.close = function() {
        $('div#questBoxPopup').css("display", "none");
    };
</script>

<div id="questBoxPopup" class="questBox" style="display: block;">
    <div class="wrap-top-left clearfix">
        <div class="wrap-top-right clearfix">
            <div class="wrap-top-middle clearfix"></div>
        </div>
    </div>
    <div class="wrap-left clearfix">
        <div class="wrap-content wrap-right clearfix">
            <div id="questBoxContent">
                <div class="questLogo"></div>
                <div id="questText"><div class="questPage" style="display:block;"><p class="questTaskText">You`ve found all the pieces of the bowl, but it will take some work to join them back together. Maybe that girl at the marketplace will prove more useful to you than as an appetising snack and can help restoring this vessel?</p></div></div>
            </div>
            <button id="questButton" class="confirmQuest" onclick="questBox.buttonClick();"></button>
        </div>
    </div>
    <div class="wrap-bottom-left">
        <div class="wrap-bottom-right">
            <div class="wrap-bottom-middle"></div>
        </div>
    </div>
</div>

<script>questBox.open();</script>

<!-- {"result":true,"newNpcMark":"none"} -->