<table class="noBackground">
    <tbody>
    <tr>
        <td nowrap="" style="font-size: 1.1em;">
            <?php echo \Bitefight\Library\Translate::_tn($talent_obj['id']); ?>
        </td>
    </tr>
    <tr>
        <td>
            <?php echo \Bitefight\Library\Translate::_td($talent_obj['id']); ?>
        </td>
    </tr>
    <?php foreach ($talent_obj['info'] as $prop): ?>
        <tr>
            <td nowrap="">
                <?php echo sprintf("%+d", $prop[1]); ?> <?php echo $prop[0]; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    <?php if($talent_obj['duration']): ?>
        <tr>
            <td nowrap="">
                <?php echo \Bitefight\Library\Translate::_('profile_talent_duration', ['duration' => $talent_obj['duration']]); ?>
            </td>
        </tr>
    <?php endif; ?>
    </tbody>
</table>