<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html>
<head>
    <title><?php echo \Bitefight\Library\Translate::_('404_error_page_title') ?></title>
    <meta http-equiv="Refresh" content="2; URL=<?php echo getUrl(''); ?>">
</head>
<body style="background-color: #220202; color: #FFF;">
<h1><?php echo \Bitefight\Library\Translate::_('404_error_page_header'); ?></h1>
<p><?php echo \Bitefight\Library\Translate::_('404_error_page_p1'); ?></p>
<p><?php echo \Bitefight\Library\Translate::_('404_error_page_p2'); ?></p>
<p><?php echo \Bitefight\Library\Translate::_('404_error_page_p3'); ?></p>
</body>
</html>