<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
    <head>
        <title><?php echo \Bitefight\Config::SERVER_NAME; ?></title>
        <?php echo headLink('game.css'); ?>
        <?php echo headLink('tipped.css'); ?>
        <meta http-equiv="content-type" content="text/html; charset=UTF-8">
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <meta http-equiv="cache-control" content="no-cache"/>
        <meta http-equiv="cache-control" content="no-store"/>
        <meta http-equiv="cache-control" content="max-age=0"/>
        <meta http-equiv="cache-control" content="must-revalidate"/>
        <meta http-equiv="expires" content="0"/>
        <meta http-equiv="pragma" content="no-cache"/>
        <?php echo headJs('jquery-3.1.1.js'); ?>
        <?php echo headJs('jquery-plugin.js'); ?>
        <?php echo headJs('jquery-countdown-2.1.0.js'); ?>
        <?php echo headJs('jquery-ui-1.11.4.js'); ?>
        <?php echo headJs('jquery-ui-chatbox.js'); ?>
        <?php echo headJs('tipped.js'); ?>
        <?php echo headJs('tipped-spinners.js'); ?>
        <?php echo headJs('init-game.js'); ?>
        <!--[if lt IE 9]><?php echo headJs('if-ie.js'); ?><![endif]-->
    </head>

    <body>

        <div id="header">
            <h1>Bitefight</h1>
            <div id="decoLamp"></div>
        </div>

        <div id="container" class="clearfix">
            <div id="menu">
                <?php $this->partial('partials/menu'); ?>
            </div>
            <div id="content">
                <?php $this->partial('partials/infobar'); ?>
                <?php echo $this->getContent(); ?>
            </div>
        </div>

        <div id="footer">
            <div id="beast"></div>
            <div id="skull"></div>
            <div id="copyright"><?php echo \Bitefight\Config::VERSION; ?> Bitefight Fun Private Server</div>
        </div>

    </body>
</html>