<div id="fightreport">
    <div class="wrap-top-left clearfix">
        <div class="wrap-top-right clearfix">
            <div class="wrap-top-middle clearfix"></div>
        </div>
    </div>
    <div class="wrap-left clearfix">
        <div class="wrap-content wrap-right clearfix">
            <h2><img src="<?php echo getAssetLink('img/symbols/race'.$user->race.'small.gif'); ?>" alt=""><?php echo \Bitefight\Library\Translate::_('user_hideout_header', ['user' => e($user->name)]); ?></h2>

            <div id="hideoutPic">
                <div id="hideout_overlay_container">
                    <div class="overlay" style="background-image:url('<?php echo getAssetLink('img/hideout/1/b/bg'.$user->h_land.'.jpg'); ?>');"></div>
                    <div class="overlay" style="background-image:url('<?php echo getAssetLink('img/hideout/1/weg/s'.$user->h_path.'.gif'); ?>');"></div>
                    <div class="overlay" style="background-image:url('<?php echo getAssetLink('img/hideout/1/u/stufe'.$user->h_domicile.'.gif'); ?>');"></div>
                    <div class="overlay" style="background-image:url('<?php echo getAssetLink('img/hideout/1/m/stufe'.$user->h_wall.'.gif'); ?>');"></div>

                    <div class="overlay" style="background-image:url('<?php echo getAssetLink('img/hideout/1/chest/stufe'.($user->h_treasure > time()?1:0).'.gif'); ?>');"></div>
                    <div class="overlay" style="background-image:url('<?php echo getAssetLink('img/hideout/1/bigchest/stufe'.($user->h_royal > time()?1:0).'.gif'); ?>');"></div>
                    <div class="overlay" style="background-image:url('<?php echo getAssetLink('img/hideout/1/guard/stufe'.($user->h_gargoyle > time()?1:0).'.gif'); ?>');"></div>
                    <div class="overlay" style="background-image:url('<?php echo getAssetLink('img/hideout/1/book/stufe'.($user->h_book > time()?1:0).'.gif'); ?>');"></div>
                </div>
            </div>

            <table style="width:100%">
                <tbody>
                    <tr>
                        <td class="no-bg" style="padding:0;">
                            <h2><img alt="" src="<?php echo getAssetLink('img/symbols/race'.$user->race.'small.gif'); ?>"><?php echo \Bitefight\Library\Translate::_('user_hideout_upgrade_hideout'); ?></h2>
                        </td>
                    </tr>
                    <tr>
                        <td class="no-bg" style="padding:0;">
                            <table class="upgrade" align="center" cellpadding="2" cellspacing="2" border="0" style="width:100%">
                            <tbody>
                            <tr>
                                <td class="tdn" width="100">
                                    <img src="<?php echo getAssetLink('img/hideout/1/palace5.jpg'); ?>" alt="<?php echo \Bitefight\Library\Translate::_('treasure_chest'); ?>">
                                </td>
                                <td class="tdn" width="150">
                                    <a href="#hint"><?php echo \Bitefight\Library\Translate::_('treasure_chest'); ?><br>(<?php echo prettyNumber(getLevel($user->exp) * 4800); ?> <img src="<?php echo getAssetLink('img/symbols/res2.gif'); ?>" alt="<?php echo \Bitefight\Library\Translate::_('gold'); ?>" align="absmiddle" border="0">)</a>
                                </td>
                                <td class="tdn" width="100">
                                    <?php if($user->h_treasure < time()): ?>
                                        <?php echo \Bitefight\Library\Translate::_('not_active'); ?>
                                    <?php else: ?>
                                        <span id="treasure_countdown"></span>
                                        <script type="text/javascript">
                                            $(function () {
                                                $("#treasure_countdown").countdown({
                                                    until: +<?php echo $user->h_treasure - time(); ?>,
                                                    compact: true,
                                                    compactLabels: ['y', 'm', 'w', 'd'],
                                                    description: '',
                                                    onExpiry: function() {
                                                        setTimeout('window.location = "/bf/user/hideout"',3000);
                                                    }
                                                });
                                            });
                                        </script>
                                    <?php endif; ?>
                                </td>
                                <td class="center-text">
                                    <a href="<?php if($user->hellstone >= 20): ?><?php echo getUrl('hideout/upgrade?id=5&_tkey='.$this->security->getTokenKey().'&_token='.$this->security->getToken()) ?><?php else: ?><?php echo getUrl('hideout') ?><?php endif; ?>" target="_top" style="display:block; width:260px; text-align:center;"><?php echo \Bitefight\Library\Translate::_('user_hideout_xweek_costs', ['week' => 4]); ?> 20 <img src="<?php echo getAssetLink('img/symbols/res3.gif'); ?>" alt="<?php echo \Bitefight\Library\Translate::_('hellstones'); ?>" align="absmiddle" border="0"></a>

                                    <br>

                                    <a href="<?php if($user->hellstone >= 55): ?><?php echo getUrl('hideout/upgrade?id=6&_tkey='.$this->security->getTokenKey().'&_token='.$this->security->getToken()) ?><?php else: ?><?php echo getUrl('hideout') ?><?php endif; ?>" target="_top" style="display:block; width:260px; text-align:center;"><?php echo \Bitefight\Library\Translate::_('user_hideout_xweek_costs', ['week' => 12]); ?> 55 <img src="<?php echo getAssetLink('img/symbols/res3.gif'); ?>" alt="<?php echo \Bitefight\Library\Translate::_('hellstones'); ?>" align="absmiddle" border="0"></a>
                                </td>
                            </tr>
                            <tr>
                                <td class="tdn" width="100">
                                    <img src="<?php echo getAssetLink('img/hideout/1/palace8.jpg'); ?>" alt="<?php echo \Bitefight\Library\Translate::_('royal_chest'); ?>">
                                </td>
                                <td class="tdn" width="150">
                                    <a href="#hint"><?php echo \Bitefight\Library\Translate::_('royal_chest'); ?><br>(<?php echo prettyNumber(getLevel($user->exp) * 4800 * 4); ?> <img src="<?php echo getAssetLink('img/symbols/res2.gif'); ?>" alt="<?php echo \Bitefight\Library\Translate::_('gold'); ?>" align="absmiddle" border="0">)</a>
                                </td>
                                <td class="tdn" width="100">
                                    <?php if($user->h_royal < time()): ?>
                                        <?php echo \Bitefight\Library\Translate::_('not_active'); ?>
                                    <?php else: ?>
                                        <span id="royal_countdown"></span>
                                        <script type="text/javascript">
                                            $(function () {
                                                $("#royal_countdown").countdown({
                                                    until: +<?php echo $user->h_royal - time(); ?>,
                                                    compact: true,
                                                    compactLabels: ['y', 'm', 'w', 'd'],
                                                    description: '',
                                                    onExpiry: function() {
                                                        setTimeout('window.location = "/bf/user/hideout"',3000);
                                                    }
                                                });
                                            });
                                        </script>
                                    <?php endif; ?>
                                </td>
                                <td class="center-text">
                                    <a href="<?php if($user->hellstone >= 69): ?><?php echo getUrl('hideout/upgrade?id=11&_tkey='.$this->security->getTokenKey().'&_token='.$this->security->getToken()) ?><?php else: ?><?php echo getUrl('hideout') ?><?php endif; ?>" target="_top" style="display:block; width:260px; text-align:center;"><?php echo \Bitefight\Library\Translate::_('user_hideout_xweek_costs', ['week' => 6]); ?> 69 <img src="<?php echo getAssetLink('img/symbols/res3.gif'); ?>" alt="<?php echo \Bitefight\Library\Translate::_('hellstones'); ?>" align="absmiddle" border="0"></a>
                                </td>
                            </tr>

                            <tr>
                                <td class="tdn" width="100">
                                    <img src="<?php echo getAssetLink('img/hideout/1/palace6.jpg'); ?>" alt="<?php echo \Bitefight\Library\Translate::_('gargoyle_guardian'); ?>">
                                </td>
                                <td class="tdn" width="150">
                                    <a href="#hint"><?php echo \Bitefight\Library\Translate::_('gargoyle_guardian'); ?></a>
                                </td>
                                <td class="tdn" width="100">
                                    <?php if($user->h_gargoyle < time()): ?>
                                        <?php echo \Bitefight\Library\Translate::_('not_active'); ?>
                                    <?php else: ?>
                                        <span id="gargoyle_countdown"></span>
                                        <script type="text/javascript">
                                            $(function () {
                                                $("#gargoyle_countdown").countdown({
                                                    until: +<?php echo $user->h_gargoyle - time(); ?>,
                                                    compact: true, compactLabels: ['y', 'm', 'w', 'd'],
                                                    description: '',
                                                    onExpiry: function() {
                                                        setTimeout('window.location = "/bf/user/hideout"',3000);
                                                    }
                                                });
                                            });
                                        </script>
                                    <?php endif; ?>
                                </td>
                                <td class="center-text">
                                    <a href="<?php if($user->hellstone >= 20): ?><?php echo getUrl('hideout/upgrade?id=7&_tkey='.$this->security->getTokenKey().'&_token='.$this->security->getToken()) ?><?php else: ?><?php echo getUrl('hideout') ?><?php endif; ?>" target="_top" style="display:block; width:260px; text-align:center;"><?php echo \Bitefight\Library\Translate::_('user_hideout_xweek_costs', ['week' => 4]); ?> 20 <img src="<?php echo getAssetLink('img/symbols/res3.gif'); ?>" alt="<?php echo \Bitefight\Library\Translate::_('hellstones'); ?>" align="absmiddle" border="0"></a>

                                    <br>

                                    <a href="<?php if($user->hellstone >= 55): ?><?php echo getUrl('hideout/upgrade?id=8&_tkey='.$this->security->getTokenKey().'&_token='.$this->security->getToken()) ?><?php else: ?><?php echo getUrl('hideout') ?><?php endif; ?>" target="_top" style="display:block; width:260px; text-align:center;"><?php echo \Bitefight\Library\Translate::_('user_hideout_xweek_costs', ['week' => 12]); ?> 55 <img src="<?php echo getAssetLink('img/symbols/res3.gif'); ?>" alt="<?php echo \Bitefight\Library\Translate::_('hellstones'); ?>" align="absmiddle" border="0"></a>
                                </td>
                            </tr>

                            <tr>
                                <td class="tdn" width="100">
                                    <img src="<?php echo getAssetLink('img/hideout/1/palace7.jpg'); ?>" alt="<?php echo \Bitefight\Library\Translate::_('book_of_the_damned'); ?>">
                                </td>
                                <td class="tdn" width="150">
                                    <a href="#hint"><?php echo \Bitefight\Library\Translate::_('book_of_the_damned'); ?></a>
                                </td>
                                <td class="tdn" width="100">
                                    <?php if($user->h_book < time()): ?>
                                        <?php echo \Bitefight\Library\Translate::_('not_active'); ?>
                                    <?php else: ?>
                                        <span id="book_countdown"></span>
                                        <script type="text/javascript">
                                            $(function () {
                                                $("#book_countdown").countdown({
                                                    until: +<?php echo $user->h_book - time(); ?>,
                                                    compact: true, compactLabels: ['y', 'm', 'w', 'd'],
                                                    description: '',
                                                    onExpiry: function() {
                                                        setTimeout('window.location = "/bf/user/hideout"',3000);
                                                    }
                                                });
                                            });
                                        </script>
                                    <?php endif; ?>
                                </td>
                                <td class="center-text">
                                    <a href="<?php if($user->hellstone >= 20): ?><?php echo getUrl('hideout/upgrade?id=9&_tkey='.$this->security->getTokenKey().'&_token='.$this->security->getToken()) ?><?php else: ?><?php echo getUrl('hideout') ?><?php endif; ?>" target="_top" style="display:block; width:260px; text-align:center;"><?php echo \Bitefight\Library\Translate::_('user_hideout_xweek_costs', ['week' => 4]); ?> 20 <img src="<?php echo getAssetLink('img/symbols/res3.gif'); ?>" alt="<?php echo \Bitefight\Library\Translate::_('hellstones'); ?>" align="absmiddle" border="0"></a>

                                    <br>

                                    <a href="<?php if($user->hellstone >= 55): ?><?php echo getUrl('hideout/upgrade?id=10&_tkey='.$this->security->getTokenKey().'&_token='.$this->security->getToken()) ?><?php else: ?><?php echo getUrl('hideout') ?><?php endif; ?>" target="_top" style="display:block; width:260px; text-align:center;"><?php echo \Bitefight\Library\Translate::_('user_hideout_xweek_costs', ['week' => 12]); ?> 55 <img src="<?php echo getAssetLink('img/symbols/res3.gif'); ?>" alt="<?php echo \Bitefight\Library\Translate::_('hellstones'); ?>" align="absmiddle" border="0"></a>
                                </td>
                            </tr>
                            <tr>
                                <td class="tdn" width="100"><img src="<?php echo getAssetLink('img/hideout/1/palace1.jpg'); ?>" alt="<?php echo \Bitefight\Library\Translate::_('domicile'); ?>"></td>
                                <td class="tdn" width="150"><a href="#hint"><?php echo \Bitefight\Library\Translate::_('domicile'); ?></a>
                                </td>
                                <td class="tdn" width="100">
                                    <?php echo \Bitefight\Library\Translate::_('level'); ?> <?php echo $user->h_domicile; ?> / 14
                                </td>
                                <td class="center-text">
                                    <?php if($user->h_domicile == 14): ?>
                                    -
                                    <?php else: ?>
                                        <?php if(getHideoutCost('domi', $user->h_domicile) <= $user->gold): ?>
                                            <a href="<?php echo getUrl('hideout/upgrade?id=1&_tkey='.$this->security->getTokenKey().'&_token='.$this->security->getToken()) ?>" target="_top"><?php echo \Bitefight\Library\Translate::_('user_hideout_next_level_costs'); ?> <?php echo prettyNumber(getHideoutCost('domi', $user->h_domicile)); ?> <img src="<?php echo getAssetLink('img/symbols/res2.gif'); ?>" alt="<?php echo \Bitefight\Library\Translate::_('gold'); ?>" align="absmiddle" border="0"></a>
                                        <?php else: ?>
                                            <?php echo \Bitefight\Library\Translate::_('user_hideout_next_level_costs'); ?> <?php echo prettyNumber(getHideoutCost('domi', $user->h_domicile)); ?> <img src="<?php echo getAssetLink('img/symbols/res2.gif'); ?>" alt="<?php echo \Bitefight\Library\Translate::_('gold'); ?>" align="absmiddle" border="0">
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </td>
                            </tr>
                            <tr>
                                <td class="tdn" width="100"><img src="<?php echo getAssetLink('img/hideout/1/palace2.jpg'); ?>" alt="<?php echo \Bitefight\Library\Translate::_('wall'); ?>"></td>
                                <td class="tdn" width="150"><a href="#hint"><?php echo \Bitefight\Library\Translate::_('wall'); ?></a>
                                </td>
                                <td class="tdn" width="100">
                                    <?php echo \Bitefight\Library\Translate::_('level'); ?> <?php echo $user->h_wall; ?> / 6
                                </td>
                                <td class="center-text">
                                    <?php if($user->h_wall == 6): ?>
                                        -
                                    <?php else: ?>
                                        <?php if(getHideoutCost('wall', $user->h_wall) <= $user->gold): ?>
                                            <a href="<?php echo getUrl('hideout/upgrade?id=2&_tkey='.$this->security->getTokenKey().'&_token='.$this->security->getToken()) ?>" target="_top"><?php echo \Bitefight\Library\Translate::_('user_hideout_next_level_costs'); ?> <?php echo prettyNumber(getHideoutCost('wall', $user->h_wall)); ?> <img src="<?php echo getAssetLink('img/symbols/res2.gif'); ?>" alt="<?php echo \Bitefight\Library\Translate::_('gold'); ?>" align="absmiddle" border="0"></a>
                                        <?php else: ?>
                                            <?php echo \Bitefight\Library\Translate::_('user_hideout_next_level_costs'); ?> <?php echo prettyNumber(getHideoutCost('wall', $user->h_wall)); ?> <img src="<?php echo getAssetLink('img/symbols/res2.gif'); ?>" alt="<?php echo \Bitefight\Library\Translate::_('gold'); ?>" align="absmiddle" border="0">
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </td>
                            </tr>
                            <tr>
                                <td class="tdn" width="100"><img src="<?php echo getAssetLink('img/hideout/1/palace3.jpg'); ?>" alt="<?php echo \Bitefight\Library\Translate::_('path'); ?>"></td>
                                <td class="tdn" width="150"><a href="#hint"><?php echo \Bitefight\Library\Translate::_('path'); ?></a>
                                </td>
                                <td class="tdn" width="100">
                                    <?php echo \Bitefight\Library\Translate::_('level'); ?> <?php echo $user->h_path; ?> / 6
                                </td>
                                <td class="center-text">
                                    <?php if($user->h_path == 6): ?>
                                        -
                                    <?php else: ?>
                                        <?php if(getHideoutCost('wall', $user->h_path) <= $user->gold): ?>
                                            <a href="<?php echo getUrl('hideout/upgrade?id=3&_tkey='.$this->security->getTokenKey().'&_token='.$this->security->getToken()) ?>" target="_top"><?php echo \Bitefight\Library\Translate::_('user_hideout_next_level_costs'); ?> <?php echo prettyNumber(getHideoutCost('path', $user->h_path)); ?> <img src="<?php echo getAssetLink('img/symbols/res2.gif'); ?>" alt="<?php echo \Bitefight\Library\Translate::_('gold'); ?>" align="absmiddle" border="0"></a>
                                        <?php else: ?>
                                            <?php echo \Bitefight\Library\Translate::_('user_hideout_next_level_costs'); ?> <?php echo prettyNumber(getHideoutCost('path', $user->h_path)); ?> <img src="<?php echo getAssetLink('img/symbols/res2.gif'); ?>" alt="<?php echo \Bitefight\Library\Translate::_('gold'); ?>" align="absmiddle" border="0">
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </td>
                            </tr>
                            <tr>
                                <td class="tdn" width="100"><img src="<?php echo getAssetLink('img/hideout/1/palace4.jpg'); ?>" alt="<?php echo \Bitefight\Library\Translate::_('landscape'); ?>"></td>
                                <td class="tdn" width="150"><a href="#hint"><?php echo \Bitefight\Library\Translate::_('landscape'); ?></a>
                                </td>
                                <td class="tdn" width="100">
                                    <?php echo \Bitefight\Library\Translate::_('level'); ?> <?php echo $user->h_land; ?> / 6
                                </td>
                                <td class="center-text">
                                    <?php if($user->h_land == 6): ?>
                                        -
                                    <?php else: ?>
                                        <?php if(getHideoutCost('wall', $user->h_land) <= $user->gold): ?>
                                            <a href="<?php echo getUrl('hideout/upgrade?id=4&_tkey='.$this->security->getTokenKey().'&_token='.$this->security->getToken()) ?>" target="_top"><?php echo \Bitefight\Library\Translate::_('user_hideout_next_level_costs'); ?> <?php echo prettyNumber(getHideoutCost('land', $user->h_land)); ?> <img src="<?php echo getAssetLink('img/symbols/res2.gif'); ?>" alt="<?php echo \Bitefight\Library\Translate::_('gold'); ?>" align="absmiddle" border="0"></a>
                                        <?php else: ?>
                                            <?php echo \Bitefight\Library\Translate::_('user_hideout_next_level_costs'); ?> <?php echo prettyNumber(getHideoutCost('land', $user->h_land)); ?> <img src="<?php echo getAssetLink('img/symbols/res2.gif'); ?>" alt="<?php echo \Bitefight\Library\Translate::_('gold'); ?>" align="absmiddle" border="0">
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </td>
                            </tr>
                            </tbody>
                            </table>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdh"><a name="hint"><?php echo \Bitefight\Library\Translate::_('tip'); ?>:</a></td>
                    </tr>
                    <tr>
                        <td class="tdn" style="text-align:justify">
                            <span class="text">
                                <?php echo \Bitefight\Library\Translate::_('user_hideout_info_header'); ?><br><br>
                                <?php echo \Bitefight\Library\Translate::_('user_hideout_info_treasure'); ?><br><br>
                                <?php echo \Bitefight\Library\Translate::_('user_hideout_info_royal'); ?><br><br>
                                <?php echo \Bitefight\Library\Translate::_('user_hideout_info_gargoyle'); ?><br><br>
                                <?php echo \Bitefight\Library\Translate::_('user_hideout_info_book'); ?><br><br>
                                <?php echo \Bitefight\Library\Translate::_('user_hideout_info_domi'); ?><br><br>
                                <?php echo \Bitefight\Library\Translate::_('user_hideout_info_wall'); ?><?php if($user->h_wall > 0): ?><br><?php echo \Bitefight\Library\Translate::_('user_hideout_info_wall_personal', ['level' => $user->h_wall, 'effect' => getWallEffect($user->h_wall)]); ?><?php endif; ?><br><br>
                                <?php echo \Bitefight\Library\Translate::_('user_hideout_info_path'); ?><br><br>
                                <?php echo \Bitefight\Library\Translate::_('user_hideout_info_land'); ?><?php if($user->h_land > 0): ?><br><?php echo \Bitefight\Library\Translate::_('user_hideout_info_land_personal', ['level' => $user->h_land, 'effect' => getLandEffect($user->h_land)]); ?><?php endif; ?><br><br>
                            </span>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    <div class="wrap-bottom-left">
        <div class="wrap-bottom-right">
            <div class="wrap-bottom-middle"></div>
        </div>
    </div>
</div>