<div id="fightreport">
    <div class="wrap-top-left clearfix">
        <div class="wrap-top-right clearfix">
            <div class="wrap-top-middle clearfix"></div>
        </div>
    </div>
    <div class="wrap-left clearfix">
        <div class="wrap-content wrap-right clearfix">
            <h2><img src="<?php echo getAssetLink('img/symbols/race'.$user->race.'small.gif'); ?>" alt="">Hideout of <?php echo e($user->name); ?></h2>

            <div id="hideoutPic">
                <div id="hideout_overlay_container">
                    <div class="overlay" style="background-image:url('<?php echo getAssetLink('img/hideout/1/b/bg'.$user->h_land.'.jpg'); ?>');"></div>
                    <div class="overlay" style="background-image:url('<?php echo getAssetLink('img/hideout/1/weg/s'.$user->h_path.'.gif'); ?>');"></div>
                    <div class="overlay" style="background-image:url('<?php echo getAssetLink('img/hideout/1/u/stufe'.$user->h_domicile.'.gif'); ?>');"></div>
                    <div class="overlay" style="background-image:url('<?php echo getAssetLink('img/hideout/1/m/stufe'.$user->h_wall.'.gif'); ?>');"></div>

                    <div class="overlay" style="background-image:url('<?php echo getAssetLink('img/hideout/1/chest/stufe'.($user->h_treasure > time()?1:0).'.gif'); ?>');"></div>
                    <div class="overlay" style="background-image:url('<?php echo getAssetLink('img/hideout/1/bigchest/stufe'.($user->h_royal > time()?1:0).'.gif'); ?>');"></div>
                    <div class="overlay" style="background-image:url('<?php echo getAssetLink('img/hideout/1/guard/stufe'.($user->h_gargoyle > time()?1:0).'.gif'); ?>');"></div>
                    <div class="overlay" style="background-image:url('<?php echo getAssetLink('img/hideout/1/book/stufe'.($user->h_book > time()?1:0).'.gif'); ?>');"></div>
                </div>
            </div>

            <table style="width:100%">
                <tbody>
                    <tr>
                        <td class="no-bg" style="padding:0;">
                            <h2><img alt="" src="<?php echo getAssetLink('img/symbols/race'.$user->race.'small.gif'); ?>">Upgrade hideout</h2>
                        </td>
                    </tr>
                    <tr>
                        <td class="no-bg" style="padding:0;">
                            <table class="upgrade" align="center" cellpadding="2" cellspacing="2" border="0" style="width:100%">
                            <tbody>
                            <tr>
                                <td class="tdn" width="100">
                                    <img src="<?php echo getAssetLink('img/hideout/1/palace5.jpg'); ?>" alt="Treasure Chest">
                                </td>
                                <td class="tdn" width="150">
                                    <a href="#hint">Treasure Chest<br>(<?php echo prettyNumber(getLevel($user->exp) * 4800); ?> <img src="<?php echo getAssetLink('img/symbols/res2.gif'); ?>" alt="Gold" align="absmiddle" border="0">)</a>
                                </td>
                                <td class="tdn" width="100">
                                    <?php if($user->h_treasure < time()): ?>
                                        not active
                                    <?php else: ?>
                                        <span id="treasure_countdown"></span>
                                        <script type="text/javascript">
                                            $(function () {
                                                $("#treasure_countdown").countdown({
                                                    until: +<?php echo $user->h_treasure - time(); ?>,
                                                    compact: true,
                                                    compactLabels: ['y', 'm', 'w', 'd'],
                                                    description: '',
                                                    onExpiry: function() {
                                                        setTimeout('window.location = "/bf/user/hideout"',3000);
                                                    }
                                                });
                                            });
                                        </script>
                                    <?php endif; ?>
                                </td>
                                <td class="center-text">
                                    <a href="<?php if($user->hellstone >= 20): ?><?php echo getUrl('hideout/upgrade?id=5&_tkey='.$this->security->getTokenKey().'&_token='.$this->security->getToken()) ?><?php else: ?><?php echo getUrl('hideout') ?><?php endif; ?>" target="_top" style="display:block; width:260px; text-align:center;">4 weeks cost you 20 <img src="<?php echo getAssetLink('img/symbols/res3.gif'); ?>" alt="Hellstones" align="absmiddle" border="0"></a>

                                    <br>

                                    <a href="<?php if($user->hellstone >= 55): ?><?php echo getUrl('hideout/upgrade?id=6&_tkey='.$this->security->getTokenKey().'&_token='.$this->security->getToken()) ?><?php else: ?><?php echo getUrl('hideout') ?><?php endif; ?>" target="_top" style="display:block; width:260px; text-align:center;">12 weeks cost you 55 <img src="<?php echo getAssetLink('img/symbols/res3.gif'); ?>" alt="Hellstones" align="absmiddle" border="0"></a>
                                </td>
                            </tr>
                            <tr>
                                <td class="tdn" width="100">
                                    <img src="<?php echo getAssetLink('img/hideout/1/palace8.jpg'); ?>" alt="Royal Chest">
                                </td>
                                <td class="tdn" width="150">
                                    <a href="#hint">Royal Chest<br>(<?php echo prettyNumber(getLevel($user->exp) * 4800 * 4); ?> <img src="<?php echo getAssetLink('img/symbols/res2.gif'); ?>" alt="Gold" align="absmiddle" border="0">)</a>
                                </td>
                                <td class="tdn" width="100">
                                    <?php if($user->h_royal < time()): ?>
                                        not active
                                    <?php else: ?>
                                        <span id="royal_countdown"></span>
                                        <script type="text/javascript">
                                            $(function () {
                                                $("#royal_countdown").countdown({
                                                    until: +<?php echo $user->h_royal - time(); ?>,
                                                    compact: true,
                                                    compactLabels: ['y', 'm', 'w', 'd'],
                                                    description: '',
                                                    onExpiry: function() {
                                                        setTimeout('window.location = "/bf/user/hideout"',3000);
                                                    }
                                                });
                                            });
                                        </script>
                                    <?php endif; ?>
                                </td>
                                <td class="center-text">
                                    <a href="<?php if($user->hellstone >= 69): ?><?php echo getUrl('hideout/upgrade?id=11&_tkey='.$this->security->getTokenKey().'&_token='.$this->security->getToken()) ?><?php else: ?><?php echo getUrl('hideout') ?><?php endif; ?>" target="_top" style="display:block; width:260px; text-align:center;">6 weeks cost you 69 <img src="<?php echo getAssetLink('img/symbols/res3.gif'); ?>" alt="Hellstones" align="absmiddle" border="0"></a>
                                </td>
                            </tr>

                            <tr>
                                <td class="tdn" width="100">
                                    <img src="<?php echo getAssetLink('img/hideout/1/palace6.jpg'); ?>" alt="Gargoyle Guardian">
                                </td>
                                <td class="tdn" width="150">
                                    <a href="#hint">Gargoyle Guardian</a>
                                </td>
                                <td class="tdn" width="100">
                                    <?php if($user->h_gargoyle < time()): ?>
                                        not active
                                    <?php else: ?>
                                        <span id="gargoyle_countdown"></span>
                                        <script type="text/javascript">
                                            $(function () {
                                                $("#gargoyle_countdown").countdown({
                                                    until: +<?php echo $user->h_gargoyle - time(); ?>,
                                                    compact: true, compactLabels: ['y', 'm', 'w', 'd'],
                                                    description: '',
                                                    onExpiry: function() {
                                                        setTimeout('window.location = "/bf/user/hideout"',3000);
                                                    }
                                                });
                                            });
                                        </script>
                                    <?php endif; ?>
                                </td>
                                <td class="center-text">
                                    <a href="<?php if($user->hellstone >= 20): ?><?php echo getUrl('hideout/upgrade?id=7&_tkey='.$this->security->getTokenKey().'&_token='.$this->security->getToken()) ?><?php else: ?><?php echo getUrl('hideout') ?><?php endif; ?>" target="_top" style="display:block; width:260px; text-align:center;">4 weeks cost you 20 <img src="<?php echo getAssetLink('img/symbols/res3.gif'); ?>" alt="Hellstones" align="absmiddle" border="0"></a>

                                    <br>

                                    <a href="<?php if($user->hellstone >= 55): ?><?php echo getUrl('hideout/upgrade?id=8&_tkey='.$this->security->getTokenKey().'&_token='.$this->security->getToken()) ?><?php else: ?><?php echo getUrl('hideout') ?><?php endif; ?>" target="_top" style="display:block; width:260px; text-align:center;">12 weeks cost you 55 <img src="<?php echo getAssetLink('img/symbols/res3.gif'); ?>" alt="Hellstones" align="absmiddle" border="0"></a>
                                </td>
                            </tr>

                            <tr>
                                <td class="tdn" width="100">
                                    <img src="<?php echo getAssetLink('img/hideout/1/palace7.jpg'); ?>" alt="Book of the Damned">
                                </td>
                                <td class="tdn" width="150">
                                    <a href="#hint">Book of the Damned</a>
                                </td>
                                <td class="tdn" width="100">
                                    <?php if($user->h_book < time()): ?>
                                        not active
                                    <?php else: ?>
                                        <span id="book_countdown"></span>
                                        <script type="text/javascript">
                                            $(function () {
                                                $("#book_countdown").countdown({
                                                    until: +<?php echo $user->h_book - time(); ?>,
                                                    compact: true, compactLabels: ['y', 'm', 'w', 'd'],
                                                    description: '',
                                                    onExpiry: function() {
                                                        setTimeout('window.location = "/bf/user/hideout"',3000);
                                                    }
                                                });
                                            });
                                        </script>
                                    <?php endif; ?>
                                </td>
                                <td class="center-text">
                                    <a href="<?php if($user->hellstone >= 20): ?><?php echo getUrl('hideout/upgrade?id=9&_tkey='.$this->security->getTokenKey().'&_token='.$this->security->getToken()) ?><?php else: ?><?php echo getUrl('hideout') ?><?php endif; ?>" target="_top" style="display:block; width:260px; text-align:center;">4 weeks cost you 20 <img src="<?php echo getAssetLink('img/symbols/res3.gif'); ?>" alt="Hellstones" align="absmiddle" border="0"></a>

                                    <br>

                                    <a href="<?php if($user->hellstone >= 55): ?><?php echo getUrl('hideout/upgrade?id=10&_tkey='.$this->security->getTokenKey().'&_token='.$this->security->getToken()) ?><?php else: ?><?php echo getUrl('hideout') ?><?php endif; ?>" target="_top" style="display:block; width:260px; text-align:center;">12 weeks cost you 55 <img src="<?php echo getAssetLink('img/symbols/res3.gif'); ?>" alt="Hellstones" align="absmiddle" border="0"></a>
                                </td>
                            </tr>
                            <tr>
                                <td class="tdn" width="100"><img src="<?php echo getAssetLink('img/hideout/1/palace1.jpg'); ?>" alt="Domicile"></td>
                                <td class="tdn" width="150"><a href="#hint">Domicile</a>
                                </td>
                                <td class="tdn" width="100">
                                    Level <?php echo $user->h_domicile; ?> / 14
                                </td>
                                <td class="center-text">
                                    <?php if($user->h_domicile == 14): ?>
                                    -
                                    <?php else: ?>
                                        <?php if(getHideoutCost('domi', $user->h_domicile) <= $user->gold): ?>
                                            <a href="<?php echo getUrl('hideout/upgrade?id=1&_tkey='.$this->security->getTokenKey().'&_token='.$this->security->getToken()) ?>" target="_top">The next level costs <?php echo prettyNumber(getHideoutCost('domi', $user->h_domicile)); ?> <img src="<?php echo getAssetLink('img/symbols/res2.gif'); ?>" alt="Gold" align="absmiddle" border="0"></a>
                                        <?php else: ?>
                                            The next level costs <?php echo prettyNumber(getHideoutCost('domi', $user->h_domicile)); ?> <img src="<?php echo getAssetLink('img/symbols/res2.gif'); ?>" alt="Gold" align="absmiddle" border="0">
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </td>
                            </tr>
                            <tr>
                                <td class="tdn" width="100"><img src="<?php echo getAssetLink('img/hideout/1/palace2.jpg'); ?>" alt="Wall"></td>
                                <td class="tdn" width="150"><a href="#hint">Wall</a>
                                </td>
                                <td class="tdn" width="100">
                                    Level <?php echo $user->h_wall; ?> / 6
                                </td>
                                <td class="center-text">
                                    <?php if($user->h_wall == 6): ?>
                                        -
                                    <?php else: ?>
                                        <?php if(getHideoutCost('wall', $user->h_wall) <= $user->gold): ?>
                                            <a href="<?php echo getUrl('hideout/upgrade?id=2&_tkey='.$this->security->getTokenKey().'&_token='.$this->security->getToken()) ?>" target="_top">The next level costs <?php echo prettyNumber(getHideoutCost('wall', $user->h_wall)); ?> <img src="<?php echo getAssetLink('img/symbols/res2.gif'); ?>" alt="Gold" align="absmiddle" border="0"></a>
                                        <?php else: ?>
                                            The next level costs <?php echo prettyNumber(getHideoutCost('wall', $user->h_wall)); ?> <img src="<?php echo getAssetLink('img/symbols/res2.gif'); ?>" alt="Gold" align="absmiddle" border="0">
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </td>
                            </tr>
                            <tr>
                                <td class="tdn" width="100"><img src="<?php echo getAssetLink('img/hideout/1/palace3.jpg'); ?>" alt="Path"></td>
                                <td class="tdn" width="150"><a href="#hint">Path</a>
                                </td>
                                <td class="tdn" width="100">
                                    Level <?php echo $user->h_path; ?> / 6
                                </td>
                                <td class="center-text">
                                    <?php if($user->h_path == 6): ?>
                                        -
                                    <?php else: ?>
                                        <?php if(getHideoutCost('wall', $user->h_path) <= $user->gold): ?>
                                            <a href="<?php echo getUrl('hideout/upgrade?id=3&_tkey='.$this->security->getTokenKey().'&_token='.$this->security->getToken()) ?>" target="_top">The next level costs <?php echo prettyNumber(getHideoutCost('path', $user->h_path)); ?> <img src="<?php echo getAssetLink('img/symbols/res2.gif'); ?>" alt="Gold" align="absmiddle" border="0"></a>
                                        <?php else: ?>
                                            The next level costs <?php echo prettyNumber(getHideoutCost('path', $user->h_path)); ?> <img src="<?php echo getAssetLink('img/symbols/res2.gif'); ?>" alt="Gold" align="absmiddle" border="0">
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </td>
                            </tr>
                            <tr>
                                <td class="tdn" width="100"><img src="<?php echo getAssetLink('img/hideout/1/palace4.jpg'); ?>" alt="Landscape"></td>
                                <td class="tdn" width="150"><a href="#hint">Landscape</a>
                                </td>
                                <td class="tdn" width="100">
                                    Level <?php echo $user->h_land; ?> / 6
                                </td>
                                <td class="center-text">
                                    <?php if($user->h_land == 6): ?>
                                        -
                                    <?php else: ?>
                                        <?php if(getHideoutCost('wall', $user->h_land) <= $user->gold): ?>
                                            <a href="<?php echo getUrl('hideout/upgrade?id=4&_tkey='.$this->security->getTokenKey().'&_token='.$this->security->getToken()) ?>" target="_top">The next level costs <?php echo prettyNumber(getHideoutCost('land', $user->h_land)); ?> <img src="<?php echo getAssetLink('img/symbols/res2.gif'); ?>" alt="Gold" align="absmiddle" border="0"></a>
                                        <?php else: ?>
                                            The next level costs <?php echo prettyNumber(getHideoutCost('land', $user->h_land)); ?> <img src="<?php echo getAssetLink('img/symbols/res2.gif'); ?>" alt="Gold" align="absmiddle" border="0">
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </td>
                            </tr>
                            </tbody>
                            </table>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdh"><a name="hint">Tip:</a></td>
                    </tr>
                    <tr>
                        <td class="tdn" style="text-align:justify">
                            <span class="text">
                                Your hideout protects you from your enemies. Your safety is increased every time you upgrade your hideout or its walls. Be aware that the upgraded level of your walls, path or landscape cannot exceed the level of your building.<br><br>
                                <b>Treasure Chest</b>:&nbsp;You can save a portion of your gold from your enemies in the Treasure Chest. A full day`s pay (level-dependant) is protected and can`t be pillaged.<br><br>
                                <b>Royal Chest</b>:&nbsp;In the royal chest you can protect part of your looted Gold from your enemies. If you are attacked by an enemy, then 4 days' pay (depending on your level) will definitely be safe in your royal chest. The royal chest works in addition to the treasure chest.<br><br>
                                <b>Gargoyle Guardian</b>:&nbsp;The gargoyle protects you and helps you fight your enemies. Your defence will be 30% more powerful.<br>Defence +30%<br>
                            You will only receive the increase when you are attacked.<br><br>
                                <b>Book of the Damned</b>:&nbsp;The Elders have written much valuable information over the course of the centuries in the Book of the Damned, all of which can help you in the fight against your foes. Using the Book, your strength increases by 30%. <br>Strength +30%<br>
                            You will only receive the increase when you are the attacker.<br><br>
                                <b>Domicile</b>:&nbsp;With every upgrade of your main building you will get two more items in your inventory.<br><br>
                                <b>Wall</b>:&nbsp;A wall protects you when you are attacked. It helps you to receive less damage.<?php if($user->h_wall > 0): ?><br>With your wall (level <?php echo $user->h_wall; ?>), your opponent will receive <?php echo getWallEffect($user->h_wall); ?> bonus damage when they attack you.<?php endif; ?><br><br>
                                <b>Path</b>:&nbsp;Having a good path gets you to your targets faster. As a result you can carry out more actions.<br> +1 on the maximum AP per path level.<br><br>
                                <b>Landscape</b>:&nbsp;The landscape is a symbol of your dark aura. The more lavish it is, the stronger effect your particular skills will have on your enemies when you are attacked.<?php if($user->h_land > 0): ?><br>Your landscape (level <?php echo $user->h_land; ?>) provides you with +<?php echo getLandEffect($user->h_land); ?>% bonus talent of activating your talents when you are attacked.<?php endif; ?><br><br>
                            </span>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    <div class="wrap-bottom-left">
        <div class="wrap-bottom-right">
            <div class="wrap-bottom-middle"></div>
        </div>
    </div>
</div>