<div id="highscore">
    <div class="wrap-top-left clearfix">
        <div class="wrap-top-right clearfix">
            <div class="wrap-top-middle clearfix"></div>
        </div>
    </div>
    <div class="wrap-left clearfix">
        <div class="wrap-content wrap-right clearfix">
            <h2><img src="<?php echo getAssetLink('img/symbols/race1small.gif'); ?>" alt="">Highscore</h2>
            <div class="table-wrap">
                <?php if(isset($user) && ($type == 'player' || $type == 'clan' && $user->clan_id > 0)): ?>
                    <form action="<?php echo getUrl('highscore/mypos'); ?>?type=<?php echo $type; ?>&race=<?php echo $race; ?>&order=<?php echo $order; ?><?php foreach ($show as $s2) {echo '&amp;show[]='.$s2;} ?>" method="POST">
                        <input type="hidden" name="<?php echo $this->security->getTokenKey() ?>" value="<?php echo $this->security->getToken() ?>"/>
                        <div class="btn-left left">
                            <div class="btn-right">
                                <input class="btn" type="submit" name="mypos" value="My position">
                            </div>
                        </div>
                    </form>
                <?php endif; ?>
                <script language="JavaScript">
                    $(document).ready(function() {
                        $('.JScheckbox').on('click', function() {
                            if($('.JScheckbox:checked').length >= 5) {
                                $('.JScheckbox:not(:checked)').attr('disabled', true);
                            } else {
                                $('.JScheckbox:not(:checked)').attr('disabled', false);
                            }
                        });

                        if($('.JScheckbox:checked').length == 5) {
                            $('.JScheckbox:not(:checked)').attr('disabled', true);
                        }

                        $('#selectClan').on('change', function() {
                            window.location.href = '<?php echo getUrl('highscore?type='); ?>'+$(this).val();
                        });
                    });
                </script>
                <form action="<?php echo getUrl('highscore'); ?>" method="GET">
                    <p></p>
                    <table cellpadding="2" cellspacing="2" border="0" width="100%" id="navigationTable">
                        <tbody>
                        <tr>
                            <td class="no-bg" colspan="2">
                                <select name="type" id="selectClan" size="1">
                                    <option value="player" <?php if($type == 'player') echo 'selected="selected"'; ?>>Player - Highscore</option>
                                    <option value="clan" <?php if($type == 'clan') echo 'selected="selected"'; ?>>Clan - Highscore</option>
                                </select>
                                <select name="race" size="1">
                                    <option value="0" <?php if($race == 0) echo 'selected="selected"'; ?>>All races</option>
                                    <option value="1" <?php if($race == 1) echo 'selected="selected"'; ?>>Vampires</option>
                                    <option value="2" <?php if($race == 2) echo 'selected="selected"'; ?>>Werewolves</option>
                                </select>
                            </td>
                            <td class="no-bg" colspan="2" style="line-height:45px;">
                                <div class="btn-left left">
                                    <div class="btn-right">
                                        <input class="btn" type="submit" value="show">
                                    </div>
                                </div>&nbsp;(Maximum of 5 options possible)
                            </td>
                        </tr>
                        <?php if($type == 'player'): ?>
                            <tr>
                                <td><input type="checkbox" class="JScheckbox" name="show[]" value="level" <?php if(in_array('level', $show)) echo 'checked'; ?>>Level</td>
                                <td><input type="checkbox" class="JScheckbox" name="show[]" value="raid" <?php if(in_array('raid', $show)) echo 'checked'; ?>>Booty</td>
                                <td><input type="checkbox" class="JScheckbox" name="show[]" value="fightvalue" <?php if(in_array('fightvalue', $show)) echo 'checked'; ?>>Battle value</td>
                                <td><input type="checkbox" class="JScheckbox" name="show[]" value="fights" <?php if(in_array('fights', $show)) echo 'checked'; ?>>Fights</td>
                            </tr>
                            <tr>
                                <td><input type="checkbox" class="JScheckbox" name="show[]" value="fight1" <?php if(in_array('fight1', $show)) echo 'checked'; ?>>Victories</td>
                                <td><input type="checkbox" class="JScheckbox" name="show[]" value="fight2" <?php if(in_array('fight2', $show)) echo 'checked'; ?>>Defeats</td>
                                <td><input type="checkbox" class="JScheckbox" name="show[]" value="fight0" <?php if(in_array('fight0', $show)) echo 'checked'; ?>>Draw</td>
                                <!--<td><input type="checkbox" class="JScheckbox" name="show[]" value="lanter">Lanterns</td>-->
                                <td><input type="checkbox" class="JScheckbox" name="show[]" value="goldwin" <?php if(in_array('goldwin', $show)) echo 'checked'; ?>>looted Gold</td>
                            </tr>
                            <tr>
                                <td><input type="checkbox" class="JScheckbox" name="show[]" value="goldlost" <?php if(in_array('goldlost', $show)) echo 'checked'; ?>>lost Gold</td>
                                <td><input type="checkbox" class="JScheckbox" name="show[]" value="hits1" <?php if(in_array('hits1', $show)) echo 'checked'; ?>>Damage caused</td>
                                <td><input type="checkbox" class="JScheckbox" name="show[]" value="hits2" <?php if(in_array('hits2', $show)) echo 'checked'; ?>>Hit points lost</td>
                            </tr>
                            <!--
                            <tr>
                                <td><input type="checkbox" class="JScheckbox" name="show[]" value="trophypoints">Trophy points</td>
                                <td><input type="checkbox" class="JScheckbox" name="show[]" value="henchmanlevels">Henchmen power</td>
                            </tr>
                            -->
                        <?php else: ?>
                            <tr>
                                <td><input type="checkbox" class="JScheckbox" name="show[]" value="castle" <?php if(in_array('castle', $show)) echo 'checked'; ?>>Level</td>
                                <td><input type="checkbox" class="JScheckbox" name="show[]" value="raid" <?php if(in_array('raid', $show)) echo 'checked'; ?>>Booty</td>
                                <td><input type="checkbox" class="JScheckbox" name="show[]" value="warraid" <?php if(in_array('warraid', $show)) echo 'checked'; ?>>War Booty</td>
                                <td><input type="checkbox" class="JScheckbox" name="show[]" value="members" <?php if(in_array('members', $show)) echo 'checked'; ?>>Members</td>
                            </tr>
                            <tr>
                                <td><input type="checkbox" class="JScheckbox" name="show[]" value="fights" <?php if(in_array('fights', $show)) echo 'checked'; ?>>Fights</td>
                                <td><input type="checkbox" class="JScheckbox" name="show[]" value="fight0" <?php if(in_array('fight0', $show)) echo 'checked'; ?>>Draw</td>
                                <td><input type="checkbox" class="JScheckbox" name="show[]" value="fight1" <?php if(in_array('fight1', $show)) echo 'checked'; ?>>Victories</td>
                                <td><input type="checkbox" class="JScheckbox" name="show[]" value="fight2" <?php if(in_array('fight2', $show)) echo 'checked'; ?>>Defeats</td>
                            </tr>
                            <!--
                            <tr>
                                <td><input type="checkbox" class="JScheckbox" name="show[]" value="ppm" <?php if(in_array('ppm', $show)) echo 'checked'; ?>>average Booty</td>
                                <td><input type="checkbox" class="JScheckbox" name="show[]" value="seals" <?php if(in_array('seals', $show)) echo 'checked'; ?>>Seals</td>
                                <td><input type="checkbox" class="JScheckbox" name="show[]" value="gatesopen" <?php if(in_array('gatesopen', $show)) echo 'checked'; ?>>Gate openings</td>
                                <td><input type="checkbox" class="JScheckbox" name="show[]" value="lastgateopen" <?php if(in_array('lastgateopen', $show)) echo 'checked'; ?>>last gate opening</td>
                            </tr>
                            -->
                        <?php endif; ?>
                        </tbody>
                    </table>
                    <p></p>
                </form>
                <center>
                    <?php if($page > 1): ?>
                    <a href="<?php echo getUrl('highscore'); ?>?type=<?php echo $type; ?>&race=<?php echo $race; ?>&page=1&order=<?php echo $order; ?><?php foreach ($show as $s2) {echo '&amp;show[]='.$s2;} ?>">
                        <img src="<?php echo getAssetLink('img/symbols/arrow_left_end.gif'); ?>" border="0" title="to the start">
                    </a>&nbsp;&nbsp;
                    <?php endif; ?>
                    <?php if($page > 10): ?>
                    <a href="<?php echo getUrl('highscore'); ?>?type=<?php echo $type; ?>&race=<?php echo $race; ?>&page=<?php echo $page - 10; ?>&order=<?php echo $order; ?><?php foreach ($show as $s2) {echo '&amp;show[]='.$s2;} ?>">
                        <img src="<?php echo getAssetLink('img/symbols/double_arrow_left.gif'); ?>" border="0" title="-10">
                    </a>&nbsp;&nbsp;
                    <?php endif; ?>
                    <?php if($page > 1): ?>
                    <a href="<?php echo getUrl('highscore'); ?>?type=<?php echo $type; ?>&race=<?php echo $race; ?>&page=<?php echo $page - 1; ?>&order=<?php echo $order; ?><?php foreach ($show as $s2) {echo '&amp;show[]='.$s2;} ?>">
                        <img src="<?php echo getAssetLink('img/symbols/single_arrow_left.gif'); ?>" border="0" title="-1">
                    </a>&nbsp;&nbsp;
                    <?php endif; ?>
                    <?php if($page > 2): ?>
                    <a href="<?php echo getUrl('highscore'); ?>?type=<?php echo $type; ?>&race=<?php echo $race; ?>&page=<?php echo $page - 2; ?>&order=<?php echo $order; ?><?php foreach ($show as $s2) {echo '&amp;show[]='.$s2;} ?>"><?php echo $page - 2; ?></a>&nbsp;&nbsp;
                    <?php endif; ?>
                    <?php if($page > 1): ?>
                    <a href="<?php echo getUrl('highscore'); ?>?type=<?php echo $type; ?>&race=<?php echo $race; ?>&page=<?php echo $page - 1; ?>&order=<?php echo $order; ?><?php foreach ($show as $s2) {echo '&amp;show[]='.$s2;} ?>"><?php echo $page - 1; ?></a>&nbsp;&nbsp;
                    <?php endif; ?>
                    <b><?php echo $page; ?></b>&nbsp;&nbsp;
                    <?php if($page < $maxPage): ?>
                    <a href="<?php echo getUrl('highscore'); ?>?type=<?php echo $type; ?>&race=<?php echo $race; ?>&page=<?php echo $page + 1; ?>&order=<?php echo $order; ?><?php foreach ($show as $s2) {echo '&amp;show[]='.$s2;} ?>"><?php echo $page + 1; ?></a>&nbsp;&nbsp;
                    <?php endif; ?>
                    <?php if($page < $maxPage - 1): ?>
                    <a href="<?php echo getUrl('highscore'); ?>?type=<?php echo $type; ?>&race=<?php echo $race; ?>&page=<?php echo $page + 2; ?>&order=<?php echo $order; ?><?php foreach ($show as $s2) {echo '&amp;show[]='.$s2;} ?>"><?php echo  $page + 2; ?></a>&nbsp;&nbsp;
                    <?php endif; ?>
                    <?php if($page < $maxPage): ?>
                    <a href="<?php echo getUrl('highscore'); ?>?type=<?php echo $type; ?>&race=<?php echo $race; ?>&page=<?php echo $page + 1; ?>&order=<?php echo $order; ?><?php foreach ($show as $s2) {echo '&amp;show[]='.$s2;} ?>">
                        <img src="<?php echo getAssetLink('img/symbols/single_arrow_right.gif'); ?>" border="0" title="+1">
                    </a>&nbsp;&nbsp;
                    <?php endif; ?>
                    <?php if($page < $maxPage - 10): ?>
                    <a href="<?php echo getUrl('highscore'); ?>?type=<?php echo $type; ?>&race=<?php echo $race; ?>&page=<?php echo $page + 10; ?>&order=<?php echo $order; ?><?php foreach ($show as $s2) {echo '&amp;show[]='.$s2;} ?>">
                        <img src="<?php echo getAssetLink('img/symbols/double_arrow_right.gif'); ?>" border="0" title="+10">
                    </a>&nbsp;&nbsp;
                    <?php endif; ?>
                    <?php if($page < $maxPage): ?>
                    <a href="<?php echo getUrl('highscore'); ?>?type=<?php echo $type; ?>&race=<?php echo $race; ?>&page=<?php echo $maxPage; ?>&order=<?php echo $order; ?><?php foreach ($show as $s2) {echo '&amp;show[]='.$s2;} ?>">
                        <img src="<?php echo getAssetLink('img/symbols/arrow_right_end.gif'); ?>" border="0" title="to the end">
                    </a>
                    <?php endif; ?>
                </center>
                <p></p>
                <table cellpadding="2" cellspacing="2" border="0" width="100%">
                    <tbody>
                    <tr>
                        <td align="center"> # </td>
                        <td align="center">Race</td>
                        <td align="center">Name</td>
                        <?php foreach($show as $s): ?>
                            <td align="center">
                                <a href="<?php echo getUrl('highscore'); ?>?type=<?php echo $type; ?>&race=<?php echo $race; ?>&page=<?php echo $page; ?>&order=<?php echo $s; ?><?php foreach ($show as $s2) {echo '&amp;show[]='.$s2;} ?>"><?php echo highscoreShowToName($s); ?></a>
                            </td>
                        <?php endforeach; ?>
                    </tr>
                    <?php foreach($results as $result): ?>
                        <tr <?php if($type == 'player' && $user->id == $result->id || $type == 'clan' && $result->id == $user->clan_id) echo 'class="own"'; ?>>
                            <td align="right"><?php echo $startRank; ?></td>
                            <td><img src="<?php echo getAssetLink('img/symbols/race'.$result->race.'small.gif'); ?>" alt="<?php echo $result->race==1?'Vampires':'Werewolves'; ?>"></td>
                            <td><a href="<?php if($type == 'clan') echo getUrl('clan/'.$result->id); else echo getUrl('profile/player/'.$result->id); ?>" title="<?php echo e($result->name); ?>"><?php echo e($result->name); ?></a></td>
                            <?php foreach ($show as $s): ?>
                                <td align="right"><?php echo (int)$result->{$s}; ?></td>
                            <?php endforeach; ?>
                        </tr>
                        <?php $startRank++; ?>
                    <?php endforeach; ?>
                    </tbody>
                </table>
                <p></p>
                <center>
                    <?php if($page > 1): ?>
                        <a href="<?php echo getUrl('highscore'); ?>?type=<?php echo $type; ?>&race=<?php echo $race; ?>&page=1&order=<?php echo $order; ?><?php foreach ($show as $s2) {echo '&amp;show[]='.$s2;} ?>">
                            <img src="<?php echo getAssetLink('img/symbols/arrow_left_end.gif'); ?>" border="0" title="to the start">
                        </a>&nbsp;&nbsp;
                    <?php endif; ?>
                    <?php if($page > 10): ?>
                        <a href="<?php echo getUrl('highscore'); ?>?type=<?php echo $type; ?>&race=<?php echo $race; ?>&page=<?php echo $page - 10; ?>&order=<?php echo $order; ?><?php foreach ($show as $s2) {echo '&amp;show[]='.$s2;} ?>">
                            <img src="<?php echo getAssetLink('img/symbols/double_arrow_left.gif'); ?>" border="0" title="-10">
                        </a>&nbsp;&nbsp;
                    <?php endif; ?>
                    <?php if($page > 1): ?>
                        <a href="<?php echo getUrl('highscore'); ?>?type=<?php echo $type; ?>&race=<?php echo $race; ?>&page=<?php echo $page - 1; ?>&order=<?php echo $order; ?><?php foreach ($show as $s2) {echo '&amp;show[]='.$s2;} ?>">
                            <img src="<?php echo getAssetLink('img/symbols/single_arrow_left.gif'); ?>" border="0" title="-1">
                        </a>&nbsp;&nbsp;
                    <?php endif; ?>
                    <?php if($page > 2): ?>
                        <a href="<?php echo getUrl('highscore'); ?>?type=<?php echo $type; ?>&race=<?php echo $race; ?>&page=<?php echo $page - 2; ?>&order=<?php echo $order; ?><?php foreach ($show as $s2) {echo '&amp;show[]='.$s2;} ?>"><?php echo $page - 2; ?></a>&nbsp;&nbsp;
                    <?php endif; ?>
                    <?php if($page > 1): ?>
                        <a href="<?php echo getUrl('highscore'); ?>?type=<?php echo $type; ?>&race=<?php echo $race; ?>&page=<?php echo $page - 1; ?>&order=<?php echo $order; ?><?php foreach ($show as $s2) {echo '&amp;show[]='.$s2;} ?>"><?php echo $page - 1; ?></a>&nbsp;&nbsp;
                    <?php endif; ?>
                    <b><?php echo $page; ?></b>&nbsp;&nbsp;
                    <?php if($page < $maxPage): ?>
                        <a href="<?php echo getUrl('highscore'); ?>?type=<?php echo $type; ?>&race=<?php echo $race; ?>&page=<?php echo $page + 1; ?>&order=<?php echo $order; ?><?php foreach ($show as $s2) {echo '&amp;show[]='.$s2;} ?>"><?php echo $page + 1; ?></a>&nbsp;&nbsp;
                    <?php endif; ?>
                    <?php if($page < $maxPage - 1): ?>
                        <a href="<?php echo getUrl('highscore'); ?>?type=<?php echo $type; ?>&race=<?php echo $race; ?>&page=<?php echo $page + 2; ?>&order=<?php echo $order; ?><?php foreach ($show as $s2) {echo '&amp;show[]='.$s2;} ?>"><?php echo  $page + 2; ?></a>&nbsp;&nbsp;
                    <?php endif; ?>
                    <?php if($page < $maxPage): ?>
                        <a href="<?php echo getUrl('highscore'); ?>?type=<?php echo $type; ?>&race=<?php echo $race; ?>&page=<?php echo $page + 1; ?>&order=<?php echo $order; ?><?php foreach ($show as $s2) {echo '&amp;show[]='.$s2;} ?>">
                            <img src="<?php echo getAssetLink('img/symbols/single_arrow_right.gif'); ?>" border="0" title="+1">
                        </a>&nbsp;&nbsp;
                    <?php endif; ?>
                    <?php if($page < $maxPage - 10): ?>
                        <a href="<?php echo getUrl('highscore'); ?>?type=<?php echo $type; ?>&race=<?php echo $race; ?>&page=<?php echo $page + 10; ?>&order=<?php echo $order; ?><?php foreach ($show as $s2) {echo '&amp;show[]='.$s2;} ?>">
                            <img src="<?php echo getAssetLink('img/symbols/double_arrow_right.gif'); ?>" border="0" title="+10">
                        </a>&nbsp;&nbsp;
                    <?php endif; ?>
                    <?php if($page < $maxPage): ?>
                        <a href="<?php echo getUrl('highscore'); ?>?type=<?php echo $type; ?>&race=<?php echo $race; ?>&page=<?php echo $maxPage; ?>&order=<?php echo $order; ?><?php foreach ($show as $s2) {echo '&amp;show[]='.$s2;} ?>">
                            <img src="<?php echo getAssetLink('img/symbols/arrow_right_end.gif'); ?>" border="0" title="to the end">
                        </a>
                    <?php endif; ?>
                </center>
                <br>
                <table cellpadding="2" cellspacing="2" border="0" width="100%">
                    <tbody>
                    <tr>
                        <td class="no-bg" align="center" width="50%">
                            <img src="<?php echo getAssetLink('img/symbols/race1.gif'); ?>" alt="Vampires">
                            <br><br>
                            <?php echo prettyNumber($vampireCount); ?> Vampires<br>
                            Booty: <?php echo prettyNumber($vampireBlood); ?> Blood<br>
                            Battles: <?php echo prettyNumber($vampireBattle); ?><br>
                            Gold: <?php echo prettyNumber($vampireGold); ?> <img src="<?php echo getAssetLink('img/symbols/res2.gif'); ?>" alt="Gold" align="absmiddle" border="0"><br>                        </td>
                        <td class="no-bg" align="center" width="50%">
                            <img src="<?php echo getAssetLink('img/symbols/race2.gif'); ?>" alt="Werewolves">
                            <br><br>
                            <?php echo prettyNumber($werewolfCount); ?> Werewolves<br>
                            Booty: <?php echo prettyNumber($werewolfBlood); ?> Meat<br>
                            Battles: <?php echo prettyNumber($werewolfBattle); ?><br>
                            Gold: <?php echo prettyNumber($werewolfGold); ?> <img src="<?php echo getAssetLink('img/symbols/res2.gif'); ?>" alt="Gold" align="absmiddle" border="0"><br>                        </td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="wrap-bottom-left">
        <div class="wrap-bottom-right">
            <div class="wrap-bottom-middle"></div>
        </div>
    </div>
</div>