<div id="highscore">
    <div class="wrap-top-left clearfix">
        <div class="wrap-top-right clearfix">
            <div class="wrap-top-middle clearfix"></div>
        </div>
    </div>
    <div class="wrap-left clearfix">
        <div class="wrap-content wrap-right clearfix">
            <h2><img src="<?php echo getAssetLink('img/symbols/race1small.gif'); ?>" alt="">Highscore</h2>
            <div class="table-wrap">
                <script language="JavaScript">
                    $(document).ready(function() {
                        $('.JScheckbox').on('click', function() {
                            if($('.JScheckbox:checked').length >= 5) {
                                $('.JScheckbox:not(:checked)').attr('disabled', true);
                            } else {
                                $('.JScheckbox:not(:checked)').attr('disabled', false);
                            }
                        });

                        if($('.JScheckbox:checked').length == 5) {
                            $('.JScheckbox:not(:checked)').attr('disabled', true);
                        }
                    });
                </script>
                <form action="<?php echo getUrl('highscore'); ?>" method="GET">
                    <p></p>
                    <table cellpadding="2" cellspacing="2" border="0" width="100%" id="navigationTable">
                        <tbody>
                        <tr>
                            <td class="no-bg" colspan="2">
                                <!--<select name="type" size="1">
                                    <option value="player" selected="selected">Player - Highscore</option>
                                    <option value="clan">Clan - Highscore</option>
                                </select>-->
                                <select name="race" size="1">
                                    <option value="0" selected="selected">All races</option>
                                    <option value="1">Vampires</option>
                                    <option value="2">Werewolves</option>
                                </select>
                            </td>
                            <td class="no-bg" colspan="2" style="line-height:45px;">
                                <div class="btn-left left">
                                    <div class="btn-right">
                                        <input class="btn" type="submit" value="show">
                                    </div>
                                </div>
                                &nbsp;
                                (Maximum of 5 options possible)
                            </td>
                        </tr>
                        <tr>
                            <td><input type="checkbox" class="JScheckbox" name="show[]" value="level" <?php if(in_array('level', $show)) echo 'checked'; ?>>Level</td>
                            <td><input type="checkbox" class="JScheckbox" name="show[]" value="raid" <?php if(in_array('raid', $show)) echo 'checked'; ?>>Booty</td>
                            <td><input type="checkbox" class="JScheckbox" name="show[]" value="fightvalue" <?php if(in_array('fightvalue', $show)) echo 'checked'; ?>>Battle value</td>
                            <td><input type="checkbox" class="JScheckbox" name="show[]" value="fights" <?php if(in_array('fights', $show)) echo 'checked'; ?>>Fights</td>
                        </tr>
                        <tr>
                            <td><input type="checkbox" class="JScheckbox" name="show[]" value="fight1" <?php if(in_array('fight1', $show)) echo 'checked'; ?>>Victories</td>
                            <td><input type="checkbox" class="JScheckbox" name="show[]" value="fight2" <?php if(in_array('fight2', $show)) echo 'checked'; ?>>Defeats</td>
                            <td><input type="checkbox" class="JScheckbox" name="show[]" value="fight0" <?php if(in_array('fight0', $show)) echo 'checked'; ?>>Draw</td>
                            <!--<td><input type="checkbox" class="JScheckbox" name="show[]" value="lanter">Lanterns</td>-->
                            <td><input type="checkbox" class="JScheckbox" name="show[]" value="goldwin" <?php if(in_array('goldwin', $show)) echo 'checked'; ?>>looted Gold</td>
                        </tr>
                        <tr>
                            <td><input type="checkbox" class="JScheckbox" name="show[]" value="goldlost" <?php if(in_array('goldlost', $show)) echo 'checked'; ?>>lost Gold</td>
                            <td><input type="checkbox" class="JScheckbox" name="show[]" value="hits1" <?php if(in_array('hits1', $show)) echo 'checked'; ?>>Damage caused</td>
                            <td><input type="checkbox" class="JScheckbox" name="show[]" value="hits2" <?php if(in_array('hits2', $show)) echo 'checked'; ?>>Hit points lost</td>
                        </tr>
                        <!--
                        <tr>
                            <td><input type="checkbox" class="JScheckbox" name="show[]" value="trophypoints">Trophy points</td>
                            <td><input type="checkbox" class="JScheckbox" name="show[]" value="henchmanlevels">Henchmen power</td>
                        </tr>
                        -->
                        </tbody>
                    </table>
                    <p></p>
                </form>
                <center><b>1</b>&nbsp;&nbsp;<a href="/user/highscore/player/0/2?order=&amp;show[]=level&amp;show[]=raid&amp;show[]=fightvalue">2</a>&nbsp;&nbsp;<a href="/user/highscore/player/0/3?order=&amp;show[]=level&amp;show[]=raid&amp;show[]=fightvalue">3</a>&nbsp;&nbsp;<a href="/user/highscore/player/0/2?order=&amp;show[]=level&amp;show[]=raid&amp;show[]=fightvalue"><img src="/img/symbols/single_arrow_right.gif" border="0" title="+1"></a>&nbsp;&nbsp;<a href="/user/highscore/player/0/11?order=&amp;show[]=level&amp;show[]=raid&amp;show[]=fightvalue"><img src="/img/symbols/double_arrow_right.gif" border="0" title="+10"></a>&nbsp;&nbsp;<a href="/user/highscore/player/0/41?order=&amp;show[]=level&amp;show[]=raid&amp;show[]=fightvalue"><img src="/img/symbols/arrow_right_end.gif" border="0" title="to the end"></a></center>
                <p></p>
                <table cellpadding="2" cellspacing="2" border="0" width="100%">
                    <tbody>
                    <tr>
                        <td align="center"> # </td>
                        <td align="center">Race</td>
                        <td align="center">Name</td>
                        <?php foreach($show as $s): ?>
                            <td align="center">
                                <a href="<?php echo getUrl('highscore'); ?>?order=<?php echo $s; ?><?php foreach ($show as $s2) {echo '&amp;show[]='.$s2;} ?>"><?php echo highscoreShowToName($s); ?></a>
                            </td>
                        <?php endforeach; ?>
                    </tr>
                    <?php foreach($results as $result): ?>
                        <tr>
                            <td align="right"><?php echo $startRank; ?></td>
                            <td><img src="<?php echo getAssetLink('img/symbols/race'.$result->race.'small.gif'); ?>" alt="<?php echo $result->race==1?'Vampires':'Werewolves'; ?>"></td>
                            <td><a href="<?php echo getUrl('profile/player/'.$result->id); ?>" title="<?php echo e($result->name); ?>"><?php echo e($result->name); ?></a><!-- [<a href="/clan/viewExtern/5274">666</a>]--></td>
                            <?php foreach ($show as $s): ?>
                                <td align="right"><?php echo $result->{$s}; ?></td>
                            <?php endforeach; ?>
                        </tr>
                        <?php $startRank++; ?>
                    <?php endforeach; ?>
                    </tbody>
                </table>
                <p></p>
                <center><b>1</b>&nbsp;&nbsp;<a href="/user/highscore/player/0/2?order=&amp;show[]=level&amp;show[]=raid&amp;show[]=fightvalue">2</a>&nbsp;&nbsp;<a href="/user/highscore/player/0/3?order=&amp;show[]=level&amp;show[]=raid&amp;show[]=fightvalue">3</a>&nbsp;&nbsp;<a href="/user/highscore/player/0/2?order=&amp;show[]=level&amp;show[]=raid&amp;show[]=fightvalue"><img src="/img/symbols/single_arrow_right.gif" border="0" title="+1"></a>&nbsp;&nbsp;<a href="/user/highscore/player/0/11?order=&amp;show[]=level&amp;show[]=raid&amp;show[]=fightvalue"><img src="/img/symbols/double_arrow_right.gif" border="0" title="+10"></a>&nbsp;&nbsp;<a href="/user/highscore/player/0/41?order=&amp;show[]=level&amp;show[]=raid&amp;show[]=fightvalue"><img src="/img/symbols/arrow_right_end.gif" border="0" title="to the end"></a></center>
                <br>
                <table cellpadding="2" cellspacing="2" border="0" width="100%">
                    <tbody>
                    <tr>
                        <td class="no-bg" align="center" width="50%">
                            <img src="<?php echo getAssetLink('img/symbols/race1.gif'); ?>" alt="Vampires">
                            <br><br>
                            1.063 Vampires<br>
                            Booty: 575.307.006.466 Blood<br>
                            Battles: 5.160.706<br>
                            Gold: 44.835.056.778 <img src="<?php echo getAssetLink('img/symbols/res2.gif'); ?>" alt="Gold" align="absmiddle" border="0"><br>                        </td>
                        <td class="no-bg" align="center" width="50%">
                            <img src="<?php echo getAssetLink('img/symbols/race2.gif'); ?>" alt="Werewolves">
                            <br><br>
                            961 Werewolves<br> <?php echo $resultCount; ?>
                            Booty: 910.458.846.668 Meat<br>
                            Battles: 5.449.849<br>
                            Gold: 40.809.141.410 <img src="<?php echo getAssetLink('img/symbols/res2.gif'); ?>" alt="Gold" align="absmiddle" border="0"><br>                        </td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="wrap-bottom-left">
        <div class="wrap-bottom-right">
            <div class="wrap-bottom-middle"></div>
        </div>
    </div>
</div>