<div class="btn-left left">
    <div class="btn-right"><a href="<?php echo getUrl('profile/index'); ?>"  class="btn" >back</a></div>
</div>
<br class="clearfloat"/>
<div id="editUserpic">
    <div class="wrap-top-left">
        <div class="wrap-top-right">
            <div class="wrap-top-middle"></div>
        </div>
    </div>
    <div class="wrap-left">
        <div class="wrap-content wrap-right">
            <h2><img src="<?php echo getAssetLink('img/symbols/race'.$user->race.'small.gif'); ?>" alt="" />edit character picture</h2>
            <div class="table-wrap">
                <table width="100%" border="0">
                    <tr>
                        <th align="center">
                            <div>
                                <div class="wrap-top-left">
                                    <div class="wrap-top-right">
                                        <div class="wrap-top-middle"></div>
                                    </div>
                                </div>
                                <div class="wrap-left">
                                    <div class="wrap-content wrap-right">
                                        <img id="logo" src="<?php echo getAssetLink('img/logo/'.$user->race.'/'.$user->gender.'/'.$user->image_type.'.jpg') ?>" alt="playerlogo">				                </div>
                                </div>
                                <div class="wrap-bottom-left">
                                    <div class="wrap-bottom-right">
                                        <div class="wrap-bottom-middle"></div>
                                    </div>
                                </div>
                            </div>
                        </th>
                        <td align="center" style="background:none; padding:0; vertical-align:top;">
                            <script type="text/javascript">
                                $(function ()
                                {
                                    $("#logoForm").change(function()
                                    {
                                        var gender = $("input[name='gender']:checked").val();
                                        var type = $("input[name='type']:checked").val();

                                        $("#logo").attr('src', "<?php echo getAssetLink(''); ?>img/logo/<?php echo $user->race; ?>/" + gender + "/" + type + ".jpg");
                                    });
                                });
                            </script>
                            <form id="logoForm" action="<?php echo getUrl('user/profile/logo'); ?>" method="POST">
                                <input type="hidden" name="<?php echo $this->security->getTokenKey() ?>" value="<?php echo $this->security->getToken() ?>"/>
                                <table width="100%" border="0">
                                    <tr>
                                        <td class="radio" align="left">
                                            <strong>Gender</strong><br />
                                            <input type="radio" name="gender" value="1" <?php if($user->gender == 1) echo 'checked'; ?> /><label>Female</label>
                                            <input type="radio" name="gender" value="2" <?php if($user->gender == 2) echo 'checked'; ?> /><label>Male</label>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="radio" align="left">
                                            <strong>Type</strong><br />
                                            <input type="radio" name="type" value="1" <?php if($user->image_type == 1) echo 'checked' ?> /><label>1</label>
                                            <input type="radio" name="type" value="2" <?php if($user->image_type == 2) echo 'checked' ?> /><label>2</label>
                                            <input type="radio" name="type" value="3" <?php if($user->image_type == 3) echo 'checked' ?> /><label>3</label>
                                            <input type="radio" name="type" value="4" <?php if($user->image_type == 4) echo 'checked' ?> /><label>4</label>
                                            <input type="radio" name="type" value="5" <?php if($user->image_type == 5) echo 'checked' ?> /><label>5</label>
                                            <input type="radio" name="type" value="6" <?php if($user->image_type == 6) echo 'checked' ?> /><label>6</label>
                                            <input type="radio" name="type" value="7" <?php if($user->image_type == 7) echo 'checked' ?> /><label>7</label>
                                            <input type="radio" name="type" value="8" <?php if($user->image_type == 8) echo 'checked' ?> /><label>8</label>
                                            <input type="radio" name="type" value="9" <?php if($user->image_type == 9) echo 'checked' ?> /><label>9</label>
                                            <input type="radio" name="type" value="10" <?php if($user->image_type == 10) echo 'checked' ?> /><label>10</label>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td align="left" style="width:500px;">
                                            <div class="btn-left">
                                                <div class="btn-right">
                                                    <input class="btn" type="submit" name="submit" value="Save">
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                </table>
                            </form>
                        </td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
    <div class="wrap-bottom-left">
        <div class="wrap-bottom-right">
            <div class="wrap-bottom-middle"></div>
        </div>
    </div>
</div>
</div>
</div>
