<div class="table-wrap">
    <div id="playerUserPic">
        <div class="wrap-top-left">
            <div class="wrap-top-right">
                <div class="wrap-top-middle"></div>
            </div>
        </div>
        <div class="wrap-left">
            <div class="wrap-content wrap-right">
                <img src="<?php echo getAssetLink('img/logo/'.$puser->race.'/'.$puser->gender.'/'.$puser->image_type.'.jpg') ?>" border="0" width="168" alt="playerlogo">
                <?php if($puser->clan_id > 0): ?>
                <a href="<?php echo getUrl('clan/view/'.$puser->clan_id); ?>"><img src="<?php echo getAssetLink('img/clan/'.$puser->logo_bg.'-'.$puser->logo_sym.'.png'); ?>" border="0"></a>
                <?php endif; ?>
            </div>
        </div>
        <div class="wrap-bottom-left">
            <div class="wrap-bottom-right">
                <div class="wrap-bottom-middle"></div>
            </div>
        </div>
    </div>
    <div id="player">
        <div class="wrap-top-left clearfix">
            <div class="wrap-top-right clearfix">
                <div class="wrap-top-middle clearfix"></div>
            </div>
        </div>
        <div class="wrap-left clearfix">
            <div class="wrap-content wrap-right clearfix">
                <h2><img src="<?php echo getAssetLink('img/symbols/race'.$puser->race.'small.gif'); ?>" alt=""><?php echo $puser->race == 1?'Vampire':'Werewolf' ?> <span><?php echo e($puser->name); ?></span></h2>
                <div class="table-wrap">
                    <table width="100%">
                        <tbody>
                        <tr>
                            <td class="no-bg">
                                <h3>Entire Booty:</h3>
                                <p><?php echo prettyNumber($puser->s_booty); ?> Blood</p>
                                <?php if($puser->clan_id > 0): ?>
                                <h3>Clan:</h3>
                                <p><a href="<?php echo getUrl('clan/view/'.$puser->clan_id); ?>"><?php echo e($puser->clan_name); ?> [<?php echo e($puser->clan_tag); ?>]</a></p>
                                <h3>Rank:</h3>
                                <p><?php echo e($puser->rank_name); ?><?php if($puser->war_minister) { echo ' (War minister)'; } ?>
                                </p>
                                <?php endif; ?>
                            </td>
                            <td class="no-bg">
                                <!--<br class="clearfloat">
                                <div class="center">
                                    <div class="btn-left center">
                                        <div class="btn-right">
                                            <a class="btn" href="/buddy/buddyrequest/77625">Buddy request</a>
                                        </div>
                                    </div>
                                </div>-->
                                <!--<br class="clearfloat">
                                <div class="center">
                                    <div class="btn-left center">
                                        <div class="btn-right">
                                            <button type="submit" class="btndisable">Attack</button>
                                        </div>
                                    </div>
                                </div>-->
                                <!--<br class="clearfloat">
                                <div class="center">
                                    <script type="text/javascript">
                                        var showNewMessage = false;
                                        var writeDivId = '#newMessageScreen';
                                        var newMessageContent = '#newMessageContent';
                                        var blackDiv = '#blackDiv';
                                        var timer;
                                        var proposalReceiver = new Array();

                                        function writeMessageSplash()
                                        {
                                            if (showNewMessage)
                                            {
                                                hideNewMessageSplash();
                                                return;
                                            }
                                            else
                                            {
                                                if (navigator.userAgent.indexOf('MSIE 6.0') >= 0)
                                                {
                                                }
                                                else
                                                {
                                                    showBlackDiv();
                                                }
                                                showNewMessage = true;
                                            }
                                            if (navigator.userAgent.indexOf('MSIE') >= 0)
                                            {
                                                var doc_width  = document.documentElement.clientWidth;
                                            }
                                            else
                                            {
                                                var doc_width  = window.innerWidth;
                                            }
                                            $(writeDivId).css("display", "block");

                                            var off = $(writeDivId).offsetWidth;
                                            var left = Math.floor((doc_width / 2) - (off / 2));
                                            var top = 100;
                                            var width = 600;
                                            $(writeDivId).css("left", left+"px");
                                            $(writeDivId).css("top", top+"px");
                                            $(writeDivId).css("width", width+"px");
                                            $(writeDivId).css("zIndex", "501");

                                            var content = '';
                                            content += '<div id="write_error" style="display:none;"></div>';
                                            content += '<table id="write_form" width="100%" border="0" cellpadding="0" cellspacing="0">';
                                            content += '<tr>';
                                            content += '<td><b>Sender</b>:</td>';
                                            content += '<td>Xyir</td>';
                                            content += '</tr>';
                                            content += '<tr>';
                                            content += '<td><b>Recipient</b>:</td>';
                                            content += '<td style="padding:1px 5px;">';
                                            content += '<input id="receivername" style="margin:0px;" type="text" name="receiver" size="30" maxlength="30" class="input" value="Xyir" autocomplete="off">';
                                            content += '</td>';
                                            content += '</tr>';
                                            content += '<tr>';
                                            content += '<td style="padding:1px 5px;"><b>Subject</b>:</td>';
                                            content += '<td style="padding:1px 5px;"><input id="subject" style="margin:0px;" type="text" name="subject" size="30" maxlength="30" class="input" value=""></td>';
                                            content += '</tr>';
                                            content += '<tr>';
                                            content += '<td><b>message</b><br>(<span id="charcount1" style="display:inline-block; margin-bottom:0px;">2000</span> Characters)</td>';
                                            content += '<td><textarea id="message" class="no-bg fakeMsgBorder" style="margin:0px;" name="text" rows="9" cols="55" onkeydown="CheckLen2(this)" onkeyup="CheckLen2(this)" onfocus="CheckLen2(this)" onchange="CheckLen2(this)"></textarea></td>';
                                            content += '</tr>';
                                            content += '</table>';
                                            content += '<table id="write_form2" width="100%" border="0" cellpadding="0" cellspacing="0">';
                                            content += '<tr>';
                                            content += '<td width="100%" nowrap><center><a href="#" onClick="sendMessage()">( send )</a></center></td>';
                                            content += '<td nowrap><a href="#" onClick="hideNewMessageSplash()">( Close )</a></td>';
                                            content += '</tr>';
                                            content += '</table>';
                                            content += '<center>';
                                            content += '<table id="write_form3" width="100%" border="0" cellpadding="0" cellspacing="0" style="display:none;">';
                                            content += '<tr>';
                                            content += '<td><center><a href="#" onClick="hideNewMessageSplash()">( Close )</a></center></td>';
                                            content += '</tr>';
                                            content += '</table>';
                                            content += '</center>';
                                            content += '<div id="senderid" style="display:none;">77625</div>';
                                            content += '<div id="receiverid" style="display:none;"></div>';
                                            content += '<div id="sendkey" style="display:none;">7d1eb08c|77625</div>';
                                            $(newMessageContent).html(content);
                                            $("#receivername").keyup(function ()
                                            {
                                                ajaxCheckReceiver();
                                            });
                                            function ajaxCheckReceiver()
                                            {
                                                $.getJSON('/ajax/user/ajaxcheckreceiver',
                                                    'key=a16ec7|77625'+
                                                    '&name='+encodeURIComponent($("#receivername").val()),
                                                    function(data){
                                                        if (data.list.length > 0)
                                                        {
                                                            proposalReceiver = new Array();
                                                            $.each(data.list, function(i, proposal){
                                                                proposalReceiver[i] = proposal;
                                                            })
                                                            $( "#receivername" ).autocomplete({
                                                                source: proposalReceiver
                                                            });
                                                        }
                                                        else
                                                        {
                                                            proposalReceiver = new Array();
                                                        }
                                                    })
                                            }
                                        }

                                        function sendMessage()
                                        {
                                            $.getJSON('/ajax/msg/ajaxwritemail',
                                                'sendkey='+$('#sendkey').html()+
                                                '&senderid='+$('#senderid').html()+
                                                '&receivername='+encodeURIComponent($('#receivername').val())+
                                                '&subject='+encodeURIComponent($('#subject').val())+
                                                '&message='+encodeURIComponent($('#message').val()),
                                                function(data)
                                                {
                                                    if (data.errorstatus == 0)
                                                    {
                                                        msgSendSuccess(data.error);
                                                    }
                                                    else
                                                    {
                                                        msgSendFail(data.error);
                                                    }
                                                })
                                        }

                                        function msgSendSuccess(message)
                                        {
                                            $('#write_error').css('display', 'block');
                                            $('#write_error').html('<p class="info">'+message+'</p>');
                                            $('#write_form').css('display', 'none');
                                            $('#write_form2').css('display', 'none');
                                            $('#write_form3').css('display', 'block');
                                        }

                                        function msgSendFail(error)
                                        {
                                            $('#write_error').css('display', 'block');
                                            $('#write_error').html('<p class="info">'+error+'</p>');
                                        }

                                        function CheckLen2(Target)
                                        {
                                            var maxlength = "2000";
                                            StrLen=Target.value.replace(/\r\n?/g, "\n").length;
                                            if (StrLen==1&&Target.value.substring(0,1)==" ")
                                            {
                                                Target.value="";
                                                StrLen=0;
                                            }
                                            if (StrLen>maxlength )
                                            {
                                                Target.value=Target.value.substring(0,maxlength);
                                                CharsLeft=0;
                                            }
                                            else
                                            {
                                                CharsLeft=maxlength-StrLen;
                                            }
                                            document.getElementById('charcount1').innerHTML=CharsLeft;
                                        }

                                        function showBlackDiv()
                                        {
                                            var div=document.createElement('div');
                                            div.id = 'blackDiv';
                                            div.className = 'break_div';
                                            //div.onmousedown = function() {hideNewMessageSplash();};
                                            div.style.zIndex = 500;
                                            div.style.overflow = 'hidden';
                                            if (navigator.userAgent.indexOf('MSIE 6.0') >= 0)
                                            {
                                                document.body.style.width='100%';
                                                document.body.style.height='100%';
                                                div.style.width=document.body.offsetWidth+'px';
                                                div.style.height=document.body.offsetHeight+'px';
                                            }
                                            else
                                            {
                                                div.style.position='fixed';
                                                div.style.width='100%';
                                                div.style.height='100%';
                                            }
                                            document.body.appendChild(div);
                                        }

                                        function hideNewMessageSplash()
                                        {
                                            if (navigator.userAgent.indexOf('MSIE 6.0') >= 0)
                                            {
                                            }
                                            else
                                            {
                                                hideBlackDiv();
                                            }
                                            $(writeDivId).css('display', 'none');
                                            $(writeDivId).css('zIndex', '-1');
                                            $(newMessageContent).html('');
                                            showNewMessage = false;
                                            content = '';
                                        }

                                        function hideBlackDiv()
                                        {
                                            if ($(blackDiv))
                                            {
                                                $(blackDiv).remove();
                                            }
                                        }

                                    </script>
                                    <div class="btn-left left">
                                        <div class="btn-right">
                                            <a href="#" class="btn" onclick="writeMessageSplash()">Write message</a>
                                        </div>
                                    </div>
                                    <div id="newMessageScreen" class="message_screen">
                                        <div id="messageWriter">
                                            <div class="wrap-top-left clearfix">
                                                <div class="wrap-top-right clearfix">
                                                    <div class="wrap-top-middle clearfix"></div>
                                                </div>
                                            </div>
                                            <div class="wrap-left clearfix">
                                                <div class="wrap-content wrap-right clearfix">
                                                    <div id="newMessageContent" class="message_content"></div>
                                                </div>
                                            </div>
                                            <div class="wrap-bottom-left">
                                                <div class="wrap-bottom-right">
                                                    <div class="wrap-bottom-middle"></div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>-->
                            </td>
                        </tr>
                        <tr>
                            <td class="no-bg" colspan="2">
                                <h3>Character description:<!-- &nbsp;<a href="/msg/complain/pprofile?id=77625&amp;cc=c3fdd5d" class="copyright">(report)</a>--></h3>

                                <p class="char-desc">
                                    <?php echo $puser->descriptionHtml; ?>
                                </p>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="wrap-bottom-left">
            <div class="wrap-bottom-right">
                <div class="wrap-bottom-middle"></div>
            </div>
        </div>
    </div>
    <br class="clearfloat">
    <div id="otherPlayerStats" style="margin-top: 1rem;">
        <div class="wrap-top-left clearfix">
            <div class="wrap-top-right clearfix">
                <div class="wrap-top-middle clearfix"></div>
            </div>
        </div>
        <div class="wrap-left clearfix">
            <div class="wrap-content wrap-right clearfix">
                <h2><img src="<?php echo getAssetLink('img/symbols/race'.$puser->race.'small.gif'); ?>" alt="">The characteristics of <?php echo $puser->name; ?></h2>
                <table cellpadding="2" cellspacing="2" border="0" width="100%">
                    <tbody><tr>
                        <td class="tdn">Level:</td>
                        <td class="tdn"><?php echo prettyNumber(getLevel($puser->exp)); ?></td>
                    </tr>
                    <tr>
                        <td class="tdn">Battle value:</td>
                        <td class="tdn"><?php echo prettyNumber($puser->battle_value); ?></td>
                    </tr>
                    <tr>
                        <td class="tdn">Strength:</td>
                        <td class="tdn" colspan="2">
                            <img src="<?php echo getAssetLink('img/b1.gif'); ?>" alt=""><img src="<?php echo getAssetLink('img/b2.gif'); ?>" alt="" height="12" width="<?php echo $str_red_long; ?>"><img src="<?php echo getAssetLink('img/b3.gif'); ?>" alt="">
                            <span class="fontsmall">(<?php echo prettyNumber($puser->str); ?>)</span>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdn">Defence:</td>
                        <td class="tdn" colspan="2">
                            <img src="<?php echo getAssetLink('img/b1.gif'); ?>" alt=""><img src="<?php echo getAssetLink('img/b2.gif'); ?>" alt="" height="12" width="<?php echo $def_red_long; ?>"><img src="<?php echo getAssetLink('img/b3.gif'); ?>" alt="">
                            <span class="fontsmall">(<?php echo prettyNumber($puser->def); ?>)</span>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdn">Dexterity:</td>
                        <td class="tdn" colspan="2">
                            <img src="<?php echo getAssetLink('img/b1.gif'); ?>" alt=""><img src="<?php echo getAssetLink('img/b2.gif'); ?>" alt="" height="12" width="<?php echo $dex_red_long; ?>"><img src="<?php echo getAssetLink('img/b3.gif'); ?>" alt="">
                            <span class="fontsmall">(<?php echo prettyNumber($puser->dex); ?>)</span>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdn">Endurance:</td>
                        <td class="tdn" colspan="2">
                            <img src="<?php echo getAssetLink('img/b1.gif'); ?>" alt=""><img src="<?php echo getAssetLink('img/b2.gif'); ?>" alt="" height="12" width="<?php echo $end_red_long; ?>"><img src="<?php echo getAssetLink('img/b3.gif'); ?>" alt="">
                            <span class="fontsmall">(<?php echo prettyNumber($puser->end); ?>)</span>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdn">Charisma:</td>
                        <td class="tdn" colspan="2">
                            <img src="<?php echo getAssetLink('img/b1.gif'); ?>" alt=""><img src="<?php echo getAssetLink('img/b2.gif'); ?>" alt="" height="12" width="<?php echo $cha_red_long; ?>"><img src="<?php echo getAssetLink('img/b3.gif'); ?>" alt="">
                            <span class="fontsmall">(<?php echo prettyNumber($puser->cha); ?>)</span>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdn">Experience:</td>
                        <td class="tdn">
                            <img src="<?php echo getAssetLink('img/b1.gif'); ?>"><img src="<?php echo getAssetLink('img/b2.gif'); ?>" height="12" width="<?php echo $exp_red_long; ?>"><img src="<?php echo getAssetLink('img/b4.gif'); ?>" height="12" width="<?php echo 400 - $exp_red_long; ?>"><img src="<?php echo getAssetLink('img/b5.gif'); ?>"><span class="fontsmall"> (<?php echo prettyNumber($puser->exp); ?> / <?php echo prettyNumber(getExpNeeded(getLevel($puser->exp))); ?>)</span>
                        </td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="wrap-bottom-left">
            <div class="wrap-bottom-right">
                <div class="wrap-bottom-middle"></div>
            </div>
        </div>
    </div>
    <br class="clearfloat">
    <div id="playerStatistic">
        <div class="wrap-top-left clearfix">
            <div class="wrap-top-right clearfix">
                <div class="wrap-top-middle clearfix"></div>
            </div>
        </div>
        <div class="wrap-left clearfix">
            <div class="wrap-content wrap-right clearfix">
                <h2><img src="<?php echo getAssetLink('img/symbols/race'.$puser->race.'small.gif'); ?>" alt="">Statistics</h2>
                <table cellpadding="2" cellspacing="2" border="0" width="100%">
                    <tbody><tr>
                        <td class="tdn"><strong>Entire booty:</strong></td>
                        <td class="tdn"><?php echo prettyNumber($puser->s_booty); ?> Blood</td>
                    </tr>
                    <tr>
                        <td class="tdn"><strong>Fights:</strong></td>
                        <td class="tdn"><?php echo prettyNumber($puser->s_fight); ?></td>
                    </tr>
                    <tr>
                        <td class="tdn"><strong>Victories:</strong></td>
                        <td class="tdn"><?php echo prettyNumber($puser->s_victory); ?></td>
                    </tr>
                    <tr>
                        <td class="tdn"><strong>Defeats:</strong></td>
                        <td class="tdn"><?php echo prettyNumber($puser->s_defeat); ?></td>
                    </tr>
                    <tr>
                        <td class="tdn"><strong>Draws:</strong></td>
                        <td class="tdn"><?php echo prettyNumber($puser->s_draw); ?></td>
                    </tr>
                    <tr>
                        <td class="tdn"><strong>Gold captured:</strong></td>
                        <td class="tdn"><?php echo prettyNumber($puser->s_gold_captured); ?> <img src="<?php echo getAssetLink('img/symbols/res2.gif'); ?>" alt="Gold" align="absmiddle" border="0"></td>
                    </tr>
                    <tr>
                        <td class="tdn"><strong>Gold lost:</strong></td>
                        <td class="tdn"><?php echo prettyNumber($puser->s_gold_lost); ?> <img src="<?php echo getAssetLink('img/symbols/res2.gif'); ?>" alt="Gold" align="absmiddle" border="0"></td>
                    </tr>
                    <tr>
                        <td class="tdn"><strong>Damage caused:</strong></td>
                        <td class="tdn"><?php echo prettyNumber($puser->s_damage_caused); ?></td>
                    </tr>
                    <tr>
                        <td class="tdn"><strong>Hit points lost:</strong></td>
                        <td class="tdn"><?php echo prettyNumber($puser->s_hp_lost); ?></td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="wrap-bottom-left">
            <div class="wrap-bottom-right">
                <div class="wrap-bottom-middle"></div>
            </div>
        </div>
    </div>
    <br class="clearfloat">
</div>