<div class="table-wrap">
    <div id="playerUserPic">
        <div class="wrap-top-left">
            <div class="wrap-top-right">
                <div class="wrap-top-middle"></div>
            </div>
        </div>
        <div class="wrap-left">
            <div class="wrap-content wrap-right">
                <img src="<?php echo getAssetLink('img/logo/'.$puser->race.'/'.$puser->gender.'/'.$puser->image_type.'.jpg') ?>" border="0" width="168">
                <?php if($puser->clan_id > 0): ?>
                <a href="<?php echo getUrl('clan/view/'.$puser->clan_id); ?>"><img src="<?php echo getAssetLink('img/clan/'.$puser->logo_bg.'-'.$puser->logo_sym.'.png'); ?>" border="0"></a>
                <?php endif; ?>
            </div>
        </div>
        <div class="wrap-bottom-left">
            <div class="wrap-bottom-right">
                <div class="wrap-bottom-middle"></div>
            </div>
        </div>
    </div>
    <div id="player">
        <div class="wrap-top-left clearfix">
            <div class="wrap-top-right clearfix">
                <div class="wrap-top-middle clearfix"></div>
            </div>
        </div>
        <div class="wrap-left clearfix">
            <div class="wrap-content wrap-right clearfix">
                <h2><img src="<?php echo getAssetLink('img/symbols/race'.$puser->race.'small.gif'); ?>" alt=""><?php echo getRaceString($puser->race); ?> <span><?php echo e($puser->name); ?></span></h2>
                <div class="table-wrap">
                    <table width="100%">
                        <tbody>
                        <tr>
                            <td class="no-bg">
                                <h3><?php echo \Bitefight\Library\Translate::_('entire_booty'); ?>:</h3>
                                <p><?php echo \Bitefight\Library\Translate::_('entire_booty_count', ['count' => prettyNumber($puser->s_booty)]); ?></p>
                                <?php if($puser->clan_id > 0): ?>
                                <h3><?php echo \Bitefight\Library\Translate::_('clan'); ?>:</h3>
                                <p><a href="<?php echo getUrl('clan/view/'.$puser->clan_id); ?>"><?php echo e($puser->clan_name); ?> [<?php echo e($puser->clan_tag); ?>]</a></p>
                                <h3><?php echo \Bitefight\Library\Translate::_('rank'); ?>:</h3>
                                <p><?php echo e($puser->rank_name); ?><?php if($puser->war_minister) { echo ' ('.\Bitefight\Library\Translate::_('war_minister').')'; } ?>
                                </p>
                                <?php endif; ?>
                            </td>
                            <td class="no-bg">
                                <!--<br class="clearfloat">
                                <div class="center">
                                    <div class="btn-left center">
                                        <div class="btn-right">
                                            <a class="btn" href="/buddy/buddyrequest/77625">Buddy request</a>
                                        </div>
                                    </div>
                                </div>-->
                                <!--<br class="clearfloat">
                                <div class="center">
                                    <div class="btn-left center">
                                        <div class="btn-right">
                                            <button type="submit" class="btndisable">Attack</button>
                                        </div>
                                    </div>
                                </div>-->
                                <br class="clearfloat">
                                <div class="center">
                                    <?php $this->partial('partials/write_message', ['receiverName' => $puser->name]) ?>
                                    <div class="btn-left left">
                                        <div class="btn-right">
                                            <a href="#" class="btn" onclick="writeMessageSplash()">Write message</a>
                                        </div>
                                    </div>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td class="no-bg" colspan="2">
                                <h3><?php echo \Bitefight\Library\Translate::_('character_description'); ?>:<!-- &nbsp;<a href="/msg/complain/pprofile?id=77625&amp;cc=c3fdd5d" class="copyright">(report)</a>--></h3>

                                <p class="char-desc">
                                    <?php echo $puser->descriptionHtml; ?>
                                </p>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="wrap-bottom-left">
            <div class="wrap-bottom-right">
                <div class="wrap-bottom-middle"></div>
            </div>
        </div>
    </div>
    <br class="clearfloat">
    <div id="otherPlayerStats" style="margin-top: 1rem;">
        <div class="wrap-top-left clearfix">
            <div class="wrap-top-right clearfix">
                <div class="wrap-top-middle clearfix"></div>
            </div>
        </div>
        <div class="wrap-left clearfix">
            <div class="wrap-content wrap-right clearfix">
                <h2><img src="<?php echo getAssetLink('img/symbols/race'.$puser->race.'small.gif'); ?>" alt=""><?php echo \Bitefight\Library\Translate::_('characteristics_of_user', ['user' => e($puser->name)]); ?></h2>
                <table cellpadding="2" cellspacing="2" border="0" width="100%">
                    <tbody><tr>
                        <td class="tdn">Level:</td>
                        <td class="tdn"><?php echo prettyNumber(getLevel($puser->exp)); ?></td>
                    </tr>
                    <tr>
                        <td class="tdn">Battle value:</td>
                        <td class="tdn"><?php echo prettyNumber($puser->battle_value); ?></td>
                    </tr>
                    <tr>
                        <td class="tdn">Strength:</td>
                        <td class="tdn" colspan="2">
                            <img src="<?php echo getAssetLink('img/b1.gif'); ?>" alt=""><img src="<?php echo getAssetLink('img/b2.gif'); ?>" alt="" height="12" width="<?php echo $str_red_long; ?>"><img src="<?php echo getAssetLink('img/b3.gif'); ?>" alt="">
                            <span class="fontsmall">(<?php echo prettyNumber($puser->str); ?>)</span>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdn">Defence:</td>
                        <td class="tdn" colspan="2">
                            <img src="<?php echo getAssetLink('img/b1.gif'); ?>" alt=""><img src="<?php echo getAssetLink('img/b2.gif'); ?>" alt="" height="12" width="<?php echo $def_red_long; ?>"><img src="<?php echo getAssetLink('img/b3.gif'); ?>" alt="">
                            <span class="fontsmall">(<?php echo prettyNumber($puser->def); ?>)</span>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdn">Dexterity:</td>
                        <td class="tdn" colspan="2">
                            <img src="<?php echo getAssetLink('img/b1.gif'); ?>" alt=""><img src="<?php echo getAssetLink('img/b2.gif'); ?>" alt="" height="12" width="<?php echo $dex_red_long; ?>"><img src="<?php echo getAssetLink('img/b3.gif'); ?>" alt="">
                            <span class="fontsmall">(<?php echo prettyNumber($puser->dex); ?>)</span>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdn">Endurance:</td>
                        <td class="tdn" colspan="2">
                            <img src="<?php echo getAssetLink('img/b1.gif'); ?>" alt=""><img src="<?php echo getAssetLink('img/b2.gif'); ?>" alt="" height="12" width="<?php echo $end_red_long; ?>"><img src="<?php echo getAssetLink('img/b3.gif'); ?>" alt="">
                            <span class="fontsmall">(<?php echo prettyNumber($puser->end); ?>)</span>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdn">Charisma:</td>
                        <td class="tdn" colspan="2">
                            <img src="<?php echo getAssetLink('img/b1.gif'); ?>" alt=""><img src="<?php echo getAssetLink('img/b2.gif'); ?>" alt="" height="12" width="<?php echo $cha_red_long; ?>"><img src="<?php echo getAssetLink('img/b3.gif'); ?>" alt="">
                            <span class="fontsmall">(<?php echo prettyNumber($puser->cha); ?>)</span>
                        </td>
                    </tr>
                    <tr>
                        <td class="tdn">Experience:</td>
                        <td class="tdn">
                            <img src="<?php echo getAssetLink('img/b1.gif'); ?>"><img src="<?php echo getAssetLink('img/b2.gif'); ?>" height="12" width="<?php echo $exp_red_long; ?>"><img src="<?php echo getAssetLink('img/b4.gif'); ?>" height="12" width="<?php echo 400 - $exp_red_long; ?>"><img src="<?php echo getAssetLink('img/b5.gif'); ?>"><span class="fontsmall"> (<?php echo prettyNumber($puser->exp); ?> / <?php echo prettyNumber(getExpNeeded(getLevel($puser->exp))); ?>)</span>
                        </td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="wrap-bottom-left">
            <div class="wrap-bottom-right">
                <div class="wrap-bottom-middle"></div>
            </div>
        </div>
    </div>
    <br class="clearfloat">
    <div id="playerStatistic">
        <div class="wrap-top-left clearfix">
            <div class="wrap-top-right clearfix">
                <div class="wrap-top-middle clearfix"></div>
            </div>
        </div>
        <div class="wrap-left clearfix">
            <div class="wrap-content wrap-right clearfix">
                <h2><img src="<?php echo getAssetLink('img/symbols/race'.$puser->race.'small.gif'); ?>" alt="">Statistics</h2>
                <table cellpadding="2" cellspacing="2" border="0" width="100%">
                    <tbody><tr>
                        <td class="tdn"><strong>Entire booty:</strong></td>
                        <td class="tdn"><?php echo prettyNumber($puser->s_booty); ?> Blood</td>
                    </tr>
                    <tr>
                        <td class="tdn"><strong>Fights:</strong></td>
                        <td class="tdn"><?php echo prettyNumber($puser->s_fight); ?></td>
                    </tr>
                    <tr>
                        <td class="tdn"><strong>Victories:</strong></td>
                        <td class="tdn"><?php echo prettyNumber($puser->s_victory); ?></td>
                    </tr>
                    <tr>
                        <td class="tdn"><strong>Defeats:</strong></td>
                        <td class="tdn"><?php echo prettyNumber($puser->s_defeat); ?></td>
                    </tr>
                    <tr>
                        <td class="tdn"><strong>Draws:</strong></td>
                        <td class="tdn"><?php echo prettyNumber($puser->s_draw); ?></td>
                    </tr>
                    <tr>
                        <td class="tdn"><strong>Gold captured:</strong></td>
                        <td class="tdn"><?php echo prettyNumber($puser->s_gold_captured); ?> <img src="<?php echo getAssetLink('img/symbols/res2.gif'); ?>" alt="Gold" align="absmiddle" border="0"></td>
                    </tr>
                    <tr>
                        <td class="tdn"><strong>Gold lost:</strong></td>
                        <td class="tdn"><?php echo prettyNumber($puser->s_gold_lost); ?> <img src="<?php echo getAssetLink('img/symbols/res2.gif'); ?>" alt="Gold" align="absmiddle" border="0"></td>
                    </tr>
                    <tr>
                        <td class="tdn"><strong>Damage caused:</strong></td>
                        <td class="tdn"><?php echo prettyNumber($puser->s_damage_caused); ?></td>
                    </tr>
                    <tr>
                        <td class="tdn"><strong>Hit points lost:</strong></td>
                        <td class="tdn"><?php echo prettyNumber($puser->s_hp_lost); ?></td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="wrap-bottom-left">
            <div class="wrap-bottom-right">
                <div class="wrap-bottom-middle"></div>
            </div>
        </div>
    </div>
    <br class="clearfloat">
</div>