<!--
<p id="upgrademsg">
    <a href="http://s202.en.bitefight.gameforge.com/city/voodoo" >Become a Shadow-Lord now! Hunt for longer and much more...</a>
</p>
-->

<script type="text/javascript">
    jQuery().ready(function(){
        // show div that is hidden on load to hide the graphics from showing on top of the loading page
        $('#tabs-6').show();

        $('#tabs').tabs();
    });
</script>

<div id="tabs">
    <ul>
        <li><a href="#tabs-1">Character</a></li>
        <li><a href="#tabs-2">Attributes</a></li>
        <li><a href="#tabs-3">Statistics</a></li>
        <li><a href="#tabs-4">Fight modifications</a></li>
        <!--<li><a href="#tabs-5">Talents</a></li>
        <li><a href="#tabs-6">Aspects</a></li>
        <li><a href="#tabs-7">Orbs</a></li>-->
    </ul>
    <div id="tabs-1">
        <div id="character_tab">
            <div class="wrap-top-left clearfix">
                <div class="wrap-top-right clearfix">
                    <div class="wrap-top-middle clearfix"></div>
                </div>
            </div>
            <div class="wrap-left clearfix">
                <div class="wrap-content wrap-right clearfix">
                    <div id="character_tab">
                        <div id="userPic">
                            <div class="wrap-top-left">
                                <div class="wrap-top-right">
                                    <div class="wrap-top-middle"></div>
                                </div>
                            </div>
                            <div class="wrap-left">
                                <div class="wrap-content wrap-right">
                                    <a id="userLogo" href="<?php echo getUrl('user/profile/logo'); ?>" >
                                        <img src="<?php echo getAssetLink('img/logo/'.$user->race.'/'.$user->gender.'/'.$user->image_type.'.jpg'); ?>" border="0" width="168" alt="playerlogo">
                                        <br>
                                        <span>edit picture</span>
                                    </a>
                                </div>
                            </div>
                            <div class="wrap-bottom-left">
                                <div class="wrap-bottom-right">
                                    <div class="wrap-bottom-middle"></div>
                                </div>
                            </div>
                        </div>
                        <table cellpadding="2" cellspacing="2" border="0" width="520px" style="float: right;">
                            <tr>
                                <td nowrap>County:</td>
                                <td nowrap width="90%"><?php echo $config->serverName; ?></td>
                            </tr>
                            <tr>
                                <td nowrap>Race:</td>
                                <td nowrap><?php if($user->race == 1) echo 'Vampire'; else echo 'Werewolf'; ?><!--&nbsp;&nbsp;<a href="/city/voodoo#premItem_1" title="To the metamorphosis stone"><img src="http://s202.en.bitefight.gameforge.com/img/symbols/metastone.gif"></a>--></td>
                            </tr>
                            <tr>
                                <td nowrap>Player ID:</td>
                                <td nowrap><?php echo $user->id; ?></td>
                            </tr>
                            <tr>
                                <td nowrap>Player name:</td>
                                <td nowrap><?php echo $user->name; ?><!--<a href="/profile/player/77625">Xyir</a>--></td>
                            </tr>
                            <tr>
                                <td nowrap>Level:</td>
                                <td nowrap><?php echo prettyNumber(getLevel($user->exp)); ?></td>
                            </tr>
                            <tr>
                                <td nowrap>Battle value:</td>
                                <td nowrap><?php echo prettyNumber($user->battle_value); ?></td>
                            </tr>
                            <tr>
                                <td nowrap>Highscore position:</td>
                                <td nowrap><?php echo prettyNumber($highscorePosition); ?></td>
                            </tr>
                            <!--
                            <tr>
                                <td nowrap>Clan Highscore position:</td>
                                <td nowrap>72</td>
                            </tr>
                            -->
                        </table>
                    </div>
                </div>
            </div>
            <div class="wrap-bottom-left">
                <div class="wrap-bottom-right">
                    <div class="wrap-bottom-middle"></div>
                </div>
            </div>
        </div>
    </div>
    <div id="tabs-2">
        <div id="skills_tab">
            <div class="wrap-top-left clearfix">
                <div class="wrap-top-right clearfix">
                    <div class="wrap-top-middle clearfix"></div>
                </div>
            </div>
            <div class="wrap-left clearfix">
                <div class="wrap-content wrap-right clearfix">
                    <div class="table-wrap">
                        <table cellpadding="2" cellspacing="2" border="0" width="100%">
                            <tr>
                                <td>Strength:</td>
                                <td nowrap>
                                    <div class="tooltip left"  title="<div><div class='tooltipHead'>Strength: <?php echo prettyNumber($user->str); ?></div><div class='tooltipContent'><table><tr><td>Basic value:</td><td align='right'><?php echo prettyNumber($user->str); ?></td></tr></table></div></div>" style="text-align:left;">
                                        <img src="<?php echo getAssetLink('img/b1.gif'); ?>" alt=""><img src="<?php echo getAssetLink('img/b2.gif'); ?>" alt="" height="12" width="<?php echo $str_red_long; ?>"><img src="<?php echo getAssetLink('img/b3.gif') ?>" alt=""> <span class="fontsmall">(<?php echo prettyNumber($user->str); ?>)</span>
                                    </div>
                                </td>
                                <td>
                                    <div class="tooltip" title='<div style="width: 150px;"><table class="noBackground"><tbody><tr><td nowrap="">costs: <?php echo prettyNumber($str_cost); ?><img src="<?php echo getAssetLink('img/symbols/res2.gif'); ?>" alt="Gold" align="absmiddle" border="0"></td></tr><?php if($user->gold < $str_cost): ?><tr><td>Unfortunately you don`t have enough gold coins!</td></tr><?php endif; ?></tbody></table></div>'>
                                        <?php if($user->gold >= $str_cost): ?>
                                            <form id="upgradeStrength" action="<?php echo getUrl('user/profile/training'); ?>" method="post">
                                                <input type="hidden" name="<?php echo $this->security->getTokenKey() ?>" value="<?php echo $this->security->getToken() ?>"/>
                                                <input type="hidden" name="stat_type" value="str">
                                                <img style="cursor: hand" onclick='document.forms["upgradeStrength"].submit();' src="<?php echo getAssetLink('img/symbols/iconplus.png'); ?>">
                                            </form>
                                        <?php else: ?>
                                            <img src="<?php echo getAssetLink('img/symbols/iconplus_inactiv.png'); ?>"/>
                                        <?php endif; ?>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td>Defence:</td>
                                <td nowrap>
                                    <div class="tooltip left"  title="<div><div class='tooltipHead'>Defence: <?php echo prettyNumber($user->def); ?></div><div class='tooltipContent'><table><tr><td>Basic value:</td><td align='right'><?php echo prettyNumber($user->def); ?></td></tr></table></div></div>" style="text-align:left;">
                                        <img src="<?php echo getAssetLink('img/b1.gif'); ?>" alt=""><img src="<?php echo getAssetLink('img/b2.gif'); ?>" alt="" height="12" width="<?php echo $def_red_long; ?>"><img src="<?php echo getAssetLink('img/b3.gif') ?>" alt=""> <span class="fontsmall">(<?php echo prettyNumber($user->def); ?>)</span>
                                    </div>
                                </td>
                                <td>
                                    <div class="tooltip" title='<div style="width: 150px;"><table class="noBackground"><tbody><tr><td nowrap="">costs: <?php echo prettyNumber($def_cost); ?><img src="<?php echo getAssetLink('img/symbols/res2.gif'); ?>" alt="Gold" align="absmiddle" border="0"></td></tr><?php if($user->gold < $def_cost): ?><tr><td>Unfortunately you don`t have enough gold coins!</td></tr><?php endif; ?></tbody></table></div>'>
                                        <?php if($user->gold >= $def_cost): ?>
                                            <form id="upgradeDefence" action="<?php echo getUrl('user/profile/training'); ?>" method="post">
                                                <input type="hidden" name="<?php echo $this->security->getTokenKey() ?>" value="<?php echo $this->security->getToken() ?>"/>
                                                <input type="hidden" name="stat_type" value="def">
                                                <img style="cursor: hand" onclick='document.forms["upgradeDefence"].submit();' src="<?php echo getAssetLink('img/symbols/iconplus.png'); ?>">
                                            </form>
                                        <?php else: ?>
                                            <img src="<?php echo getAssetLink('img/symbols/iconplus_inactiv.png'); ?>"/>
                                        <?php endif; ?>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td>Dexterity:</td>
                                <td nowrap>
                                    <div class="tooltip left"  title="<div><div class='tooltipHead'>Dexterity: <?php echo prettyNumber($user->dex); ?></div><div class='tooltipContent'><table><tr><td>Basic value:</td><td align='right'><?php echo prettyNumber($user->dex); ?></td></tr></table></div></div>" style="text-align:left;">
                                        <img src="<?php echo getAssetLink('img/b1.gif'); ?>" alt=""><img src="<?php echo getAssetLink('img/b2.gif'); ?>" alt="" height="12" width="<?php echo $dex_red_long; ?>"><img src="<?php echo getAssetLink('img/b3.gif') ?>" alt=""> <span class="fontsmall">(<?php echo prettyNumber($user->dex); ?>)</span>
                                    </div>
                                </td>
                                <td>
                                    <div class="tooltip" title='<div style="width: 150px;"><table class="noBackground"><tbody><tr><td nowrap="">costs: <?php echo prettyNumber($dex_cost); ?><img src="<?php echo getAssetLink('img/symbols/res2.gif'); ?>" alt="Gold" align="absmiddle" border="0"></td></tr><?php if($user->gold < $dex_cost): ?><tr><td>Unfortunately you don`t have enough gold coins!</td></tr><?php endif; ?></tbody></table></div>'>
                                        <?php if($user->gold >= $dex_cost): ?>
                                            <form id="upgradeDexterity" action="<?php echo getUrl('user/profile/training'); ?>" method="post">
                                                <input type="hidden" name="<?php echo $this->security->getTokenKey() ?>" value="<?php echo $this->security->getToken() ?>"/>
                                                <input type="hidden" name="stat_type" value="dex">
                                                <img style="cursor: hand" onclick='document.forms["upgradeDexterity"].submit();' src="<?php echo getAssetLink('img/symbols/iconplus.png'); ?>">
                                            </form>
                                        <?php else: ?>
                                            <img src="<?php echo getAssetLink('img/symbols/iconplus_inactiv.png'); ?>"/>
                                        <?php endif; ?>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td>Endurance:</td>
                                <td nowrap>
                                    <div class="tooltip left"  title="<div><div class='tooltipHead'>Endurance: <?php echo prettyNumber($user->end); ?></div><div class='tooltipContent'><table><tr><td>Basic value:</td><td align='right'><?php echo prettyNumber($user->end); ?></td></tr></table></div></div>" style="text-align:left;">
                                        <img src="<?php echo getAssetLink('img/b1.gif'); ?>" alt=""><img src="<?php echo getAssetLink('img/b2.gif'); ?>" alt="" height="12" width="<?php echo $end_red_long; ?>"><img src="<?php echo getAssetLink('img/b3.gif') ?>" alt=""> <span class="fontsmall">(<?php echo prettyNumber($user->end); ?>)</span>
                                    </div>
                                </td>
                                <td>
                                    <div class="tooltip" title='<div style="width: 150px;"><table class="noBackground"><tbody><tr><td nowrap="">costs: <?php echo prettyNumber($end_cost); ?><img src="<?php echo getAssetLink('img/symbols/res2.gif'); ?>" alt="Gold" align="absmiddle" border="0"></td></tr><?php if($user->gold < $end_cost): ?><tr><td>Unfortunately you don`t have enough gold coins!</td></tr><?php endif; ?></tbody></table></div>'>
                                        <?php if($user->gold >= $end_cost): ?>
                                            <form id="upgradeEndurance" action="<?php echo getUrl('user/profile/training'); ?>" method="post">
                                                <input type="hidden" name="<?php echo $this->security->getTokenKey() ?>" value="<?php echo $this->security->getToken() ?>"/>
                                                <input type="hidden" name="stat_type" value="end">
                                                <img style="cursor: hand" onclick='document.forms["upgradeEndurance"].submit();' src="<?php echo getAssetLink('img/symbols/iconplus.png'); ?>">
                                            </form>
                                        <?php else: ?>
                                            <img src="<?php echo getAssetLink('img/symbols/iconplus_inactiv.png'); ?>"/>
                                        <?php endif; ?>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td>Charisma:</td>
                                <td nowrap>
                                    <div class="tooltip left"  title="<div><div class='tooltipHead'>Charisma: <?php echo prettyNumber($user->cha); ?></div><div class='tooltipContent'><table><tr><td>Basic value:</td><td align='right'><?php echo prettyNumber($user->cha); ?></td></tr></table></div></div>" style="text-align:left;">
                                        <img src="<?php echo getAssetLink('img/b1.gif'); ?>" alt=""><img src="<?php echo getAssetLink('img/b2.gif'); ?>" alt="" height="12" width="<?php echo $cha_red_long; ?>"><img src="<?php echo getAssetLink('img/b3.gif') ?>" alt=""> <span class="fontsmall">(<?php echo prettyNumber($user->cha); ?>)</span>
                                    </div>
                                </td>
                                <td>
                                    <div class="tooltip" title='<div style="width: 150px;"><table class="noBackground"><tbody><tr><td nowrap="">costs: <?php echo prettyNumber($cha_cost); ?><img src="<?php echo getAssetLink('img/symbols/res2.gif'); ?>" alt="Gold" align="absmiddle" border="0"></td></tr><?php if($user->gold < $cha_cost): ?><tr><td>Unfortunately you don`t have enough gold coins!</td></tr><?php endif; ?></tbody></table></div>'>
                                        <?php if($user->gold >= $cha_cost): ?>
                                            <form id="upgradeCharisma" action="<?php echo getUrl('user/profile/training'); ?>" method="post">
                                                <input type="hidden" name="<?php echo $this->security->getTokenKey() ?>" value="<?php echo $this->security->getToken() ?>"/>
                                                <input type="hidden" name="stat_type" value="cha">
                                                <img style="cursor: hand" onclick='document.forms["upgradeCharisma"].submit();' src="<?php echo getAssetLink('img/symbols/iconplus.png'); ?>">
                                            </form>
                                        <?php else: ?>
                                            <img src="<?php echo getAssetLink('img/symbols/iconplus_inactiv.png'); ?>"/>
                                        <?php endif; ?>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td>Experience:</td>
                                <td colspan="2"><img src="<?php echo getAssetLink('img/b1.gif'); ?>" alt="" ><img src="<?php echo getAssetLink('img/b2.gif'); ?>" alt="" height="12" width="<?php echo $exp_red_long; ?>"><img src="<?php echo getAssetLink('img/b4.gif'); ?>" alt="" height="12" width="<?php echo 400 - $exp_red_long; ?>"><img src="<?php echo getAssetLink('img/b5.gif'); ?>" alt="" ><span class="fontsmall"><br>(<?php echo prettyNumber($user->exp); ?> / <?php echo prettyNumber($required_exp); ?>)</span></td>
                            </tr>
                            <tr>
                                <td>Health:</td>
                                <td colspan="2">
                                    <div class="tooltip left" title="<div><div class='tooltipHead'>Total Health: <?php echo prettyNumber($user->hp_max); ?></div><div class='tooltipContent'><table><tr><td>Basic value:</td><td align='right'><?php echo prettyNumber($config->basicHp); ?></td></tr><tr><td>Defence:</td><td align='right'><?php echo prettyNumber($config->defHpRatio * $user->def); ?></td></tr></table></div></div>">
                                        <img src="<?php echo getAssetLink('img/b1.gif'); ?>" alt="" ><img src="<?php echo getAssetLink('img/b2.gif'); ?>" alt="" height="12" width="<?php echo $hp_red_long; ?>"><img src="<?php echo getAssetLink('img/b4.gif'); ?>" alt="" height="12" width="<?php echo 400 - $hp_red_long; ?>"><?php if($user->hp_now < $user->hp_max): ?><img src="<?php echo getAssetLink('img/b5.gif'); ?>" alt="" ><?php else: ?><img src="<?php echo getAssetLink('img/b5.gif'); ?>" alt="" ><?php endif; ?><br><span class="fontsmall left">(<?php echo prettyNumber($user->hp_now); ?> / <?php echo prettyNumber($user->hp_max); ?>)</span>
                                    </div>
                                </td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
            <div class="wrap-bottom-left">
                <div class="wrap-bottom-right">
                    <div class="wrap-bottom-middle"></div>
                </div>
            </div>
        </div>
    </div>
    <div id="tabs-3">
        <div id="stats_tab">
            <div class="wrap-top-left clearfix">
                <div class="wrap-top-right clearfix">
                    <div class="wrap-top-middle clearfix"></div>
                </div>
            </div>
            <div class="wrap-left clearfix">
                <div class="wrap-content wrap-right clearfix">
                    <div class="table-wrap">
                        <table cellpadding="2" cellspacing="2" border="0" width="100%">
                            <tr>
                                <td>Entire booty:</td>
                                <td><?php echo prettyNumber($user->s_booty); ?></td>
                            </tr>
                            <tr>
                                <td>Fights:</td>
                                <td><?php echo prettyNumber($user->s_fight); ?></td>
                            </tr>
                            <tr>
                                <td>Victories:</td>
                                <td><?php echo prettyNumber($user->s_victory); ?></td>
                            </tr>
                            <tr>
                                <td>Defeats:</td>
                                <td><?php echo prettyNumber($user->s_defeat); ?></td>
                            </tr>
                            <tr>
                                <td>Draws:</td>
                                <td><?php echo prettyNumber($user->s_draw); ?></td>
                            </tr>
                            <tr>
                                <td>Gold captured:</td>
                                <td><?php echo prettyNumber($user->s_gold_captured); ?> <img src="<?php echo getAssetLink('img/symbols/res2.gif'); ?>"  alt="Gold" align="absmiddle" border="0" /></td>
                            </tr>
                            <tr>
                                <td>Gold lost:</td>
                                <td><?php echo prettyNumber($user->s_gold_lost); ?> <img src="<?php echo getAssetLink('img/symbols/res2.gif'); ?>"  alt="Gold" align="absmiddle" border="0" /></td>
                            </tr>
                            <tr>
                                <td>Damage caused:</td>
                                <td><?php echo prettyNumber($user->s_damage_caused); ?></td>
                            </tr>
                            <tr>
                                <td>Hit points lost:</td>
                                <td><?php echo prettyNumber($user->s_hp_lost); ?></td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
            <div class="wrap-bottom-left">
                <div class="wrap-bottom-right">
                    <div class="wrap-bottom-middle"></div>
                </div>
            </div>
        </div>
    </div>
    <div id="tabs-4">
        <div id="skillmodis_tab">
            <div class="wrap-top-left clearfix">
                <div class="wrap-top-right clearfix">
                    <div class="wrap-top-middle clearfix"></div>
                </div>
            </div>
            <div class="wrap-left clearfix">
                <div class="wrap-content wrap-right clearfix">
                    <div class="table-wrap">
                        <table cellpadding="2" cellspacing="2" border="0" width="100%">
                            <tr>
                                <td>Attack:</td>
                                <td>
                                    <div class="tooltip left" title="<div><div class='tooltipHead'>Attack: <?php echo prettyNumber($config->basicAttack); ?></div><div class='tooltipContent'><table><tr><td>Basic value:</td><td align='right'><?php echo prettyNumber($config->basicAttack); ?></td></tr></table></div></div>"><?php echo prettyNumber($config->basicAttack); ?></div>
                                </td>
                            </tr>
                            <tr>
                                <td>Basic damage:</td>
                                <td>
                                    <div class="tooltip left" title="<div><div class='tooltipHead'>Basic Damage: <?php echo prettyNumber($config->basicDamage); ?></div><div class='tooltipContent'><table><tr><td>Basic value:</td><td align='right'><?php echo prettyNumber($config->basicDamage); ?></td></tr></table></div></div>"><?php echo prettyNumber($config->basicDamage); ?></div>
                                </td>
                            </tr>
                            <tr>
                                <td>Bonus damage:</td>
                                <td>
                                    <div class="tooltip left" title="<div><div class='tooltipHead'>Bonus damage: <?php echo prettyNumber($config->bonusDamage); ?></div><div class='tooltipContent'><table><tr><td>Basic value:</td><td align='right'><?php echo prettyNumber($config->bonusDamage); ?></td></tr></table></div></div>"><?php echo prettyNumber($config->bonusDamage); ?></div>
                                </td>
                            </tr>
                            <tr>
                                <td>Hit Chance:</td>
                                <td>
                                    <div class="tooltip left" title="<div><div class='tooltipHead'>Hit Chance: <?php echo prettyNumber($config->hitChance); ?></div><div class='tooltipContent'><table><tr><td>Basic value:</td><td align='right'><?php echo prettyNumber($config->hitChance); ?></td></tr></table></div></div>"><?php echo prettyNumber($config->hitChance); ?></div>
                                </td>
                            </tr>
                            <tr>
                                <td>Bonus hit chance:</td>
                                <td>
                                    <div class="tooltip left" title="<div><div class='tooltipHead'>Bonus hit chance: <?php echo prettyNumber($config->bonusHitChance); ?></div><div class='tooltipContent'><table><tr><td>Basic value:</td><td align='right'><?php echo prettyNumber($config->bonusHitChance); ?></td></tr></table></div></div>"><?php echo prettyNumber($config->bonusHitChance); ?></div>
                                </td>
                            </tr>
                            <tr>
                                <td>Basic talent:</td>
                                <td>
                                    <div class="tooltip left" title="<div><div class='tooltipHead'>Basic talent: <?php echo prettyNumber($config->basicTalent); ?></div><div class='tooltipContent'><table><tr><td>Basic value:</td><td align='right'><?php echo prettyNumber($config->basicTalent); ?></td></tr></table></div></div>"><?php echo prettyNumber($config->basicTalent); ?></div>
                                </td>
                            </tr>
                            <tr>
                                <td>Bonus Talent:</td>
                                <td>
                                    <div class="tooltip left" title="<div><div class='tooltipHead'>Bonus Talent: <?php echo prettyNumber($config->bonusTalent); ?></div><div class='tooltipContent'><table><tr><td>Basic value:</td><td align='right'><?php echo prettyNumber($config->bonusTalent); ?></td></tr></table></div></div>"><?php echo prettyNumber($config->bonusTalent); ?></div>
                                </td>
                            </tr>
                            <tr>
                                <td>Regeneration:</td>
                                <td>
                                    <div class="tooltip left" title="<div><div class='tooltipHead'>Regeneration: <?php echo prettyNumber($config->basicRegen + $user->end * $config->endRegenRatio); ?></div><div class='tooltipContent'><table><tr><td>Basic value:</td><td align='right'><?php echo prettyNumber($config->basicRegen); ?></td></tr><tr><td>Endurance:</td><td align='right'><?php echo prettyNumber($config->endRegenRatio * $user->end); ?></td></tr></table></div></div>"><?php echo prettyNumber($config->basicRegen + $user->end * $config->endRegenRatio); ?></div>
                                </td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
            <div class="wrap-bottom-left">
                <div class="wrap-bottom-right">
                    <div class="wrap-bottom-middle"></div>
                </div>
            </div>
        </div>
    </div>
    <!--
    <div id="tabs-5">
        <div id="talents_tab">
            <div class="wrap-top-left clearfix">
                <div class="wrap-top-right clearfix">
                    <div class="wrap-top-middle clearfix"></div>
                </div>
            </div>
            <div class="wrap-left clearfix">
                <div class="wrap-content wrap-right clearfix">
                    <div class="table-wrap">
                        <div class="triggerTooltip">
                            <table cellpadding="2" cellspacing="2" border="0" width="100%">
                                <tr>
                                    <td>Available points</td>
                                    <td>2</td>
                                </tr>
                                <tr>
                                    <td>Used points</td>
                                    <td>27</td>
                                </tr>
                                <tr>
                                    <td>Maximum points</td>
                                    <td>31</td>
                                </tr>
                            </table>
                        </div>
                        <div class="tooltip"><table class='noBackground'><tr><td nowrap colspan='2' style='font-size: 1.1em;'>Next points</td></tr><tr><td nowrap>Level: 289</td><td nowrap>2</td></tr></table></div>
                        <div class="btn-left right">
                            <div class="btn-right">
                                <a href="/profile/talents" class="btn">buy now</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="wrap-bottom-left">
                <div class="wrap-bottom-right">
                    <div class="wrap-bottom-middle"></div>
                </div>
            </div>
        </div>
    </div>
    -->
    <!--
    <div id="tabs-6" style="display:none;">
        <div id="aspects_tab">
            <div class="wrap-top-left clearfix">
                <div class="wrap-top-right clearfix">
                    <div class="wrap-top-middle clearfix"></div>
                </div>
            </div>
            <div class="wrap-left clearfix">
                <div class="wrap-content wrap-right clearfix">
                    <div style="padding:5px;">
                        <div class="aspect_overview clearfix" style="height:700px;">
                            <img src="http://s202.en.bitefight.gameforge.com/img/story/aspects/Aspekte_pfeil_grau_1.gif"  alt="Human" style="position:absolute;left:309px;top:125px;"/>
                            <img src="http://s202.en.bitefight.gameforge.com/img/story/aspects/human.gif" class="triggerTooltip" style="position:absolute;left:313px;top:28px;"/>
                            <div class="tooltip" style="text-align:left;">
                                <b>Human</b><br/>
                                974<br/>
                                Effect: -        </div>
                            <img src="http://s202.en.bitefight.gameforge.com/img/story/aspects/Aspekte_pfeil_grau_2.gif" style="position:absolute;left:359px;top:184px;"/>
                            <img src="http://s202.en.bitefight.gameforge.com/img/story/aspects/knowledge.gif" class="triggerTooltip"  style="position:absolute;left:529px;top:95px;"/>
                            <div class="tooltip" style="text-align:left;">
                                <b>Knowledge</b><br/>
                                1009<br/>
                                Effect: -        </div>
                            <img src="http://s202.en.bitefight.gameforge.com/img/story/aspects/Aspekte_pfeil_grau_3.gif" style="position:absolute;left:377px;top:309px;"/>
                            <img src="http://s202.en.bitefight.gameforge.com/img/story/aspects/regularity.gif" class="triggerTooltip"  style="position:absolute;left:598px;top:314px;"/>
                            <div class="tooltip" style="text-align:left;">
                                <b>Order</b><br/>
                                991<br/>
                                Effect: -        </div>
                            <img src="http://s202.en.bitefight.gameforge.com/img/story/aspects/Aspekte_pfeil_grau_4.gif" style="position:absolute;left:357px;top:353px;"/>
                            <img src="http://s202.en.bitefight.gameforge.com/img/story/aspects/nature.gif" class="triggerTooltip"  style="position:absolute;left:528px;top:527px;"/>
                            <div class="tooltip" style="text-align:left;">
                                <b>Nature</b><br/>
                                996<br/>
                                Effect: -        </div>
                            <img src="http://s202.en.bitefight.gameforge.com/img/story/aspects/Aspekte_pfeil_grau_5.gif" style="position:absolute;left:307px;top:379px;"/>
                            <img src="http://s202.en.bitefight.gameforge.com/img/story/aspects/beast.gif" class="triggerTooltip"  style="position:absolute;left:312px;top:599px;"/>
                            <div class="tooltip" style="text-align:left;">
                                <b>Beast</b><br/>
                                1015<br/>
                                Effect: -        </div>
                            <img src="http://s202.en.bitefight.gameforge.com/img/story/aspects/Aspekte_pfeil_grau_6.gif" style="position:absolute;left:188px;top:354px;"/>
                            <img src="http://s202.en.bitefight.gameforge.com/img/story/aspects/destruction.gif" class="triggerTooltip"  style="position:absolute;left:97px;top:527px;"/>
                            <div class="tooltip" style="text-align:left;">
                                <b>Destruction</b><br/>
                                992<br/>
                                Effect: -        </div>
                            <img src="http://s202.en.bitefight.gameforge.com/img/story/aspects/Aspekte_pfeil_grau_7.gif" style="position:absolute;left:125px;top:308px;"/>
                            <img src="http://s202.en.bitefight.gameforge.com/img/story/aspects/chaos.gif" class="triggerTooltip"  style="position:absolute;left:26px;top:315px;"/>
                            <div class="tooltip" style="text-align:left;">
                                <b>Chaos</b><br/>
                                1000<br/>
                                Effect: -        </div>
                            <img src="http://s202.en.bitefight.gameforge.com/img/story/aspects/Aspekte_pfeil_grau_8.gif" style="position:absolute;left:188px;top:186px;"/>
                            <img src="http://s202.en.bitefight.gameforge.com/img/story/aspects/corruption.gif" class="triggerTooltip" style="position:absolute;left:97px;top:96px;"/>
                            <div class="tooltip" style="text-align:left;">
                                <b>Corruption</b><br/>
                                1023<br/>
                                Effect: -        </div>
                        </div>
                        <br/>
                        <div style="text-align:left;">
                            <table width="100%">
                                <tr><td>Human</td><td>974</td><td width="100%">-</td></tr><tr><td>Knowledge</td><td>1009</td><td width="100%">-</td></tr><tr><td>Order</td><td>991</td><td width="100%">-</td></tr><tr><td>Nature</td><td>996</td><td width="100%">-</td></tr><tr><td>Beast</td><td>1015</td><td width="100%">-</td></tr><tr><td>Destruction</td><td>992</td><td width="100%">-</td></tr><tr><td>Chaos</td><td>1000</td><td width="100%">-</td></tr><tr><td>Corruption</td><td>1023</td><td width="100%">-</td></tr>        </table>

                            <br/>
                            There are 8 aspects that describe the player character`s nature. Each aspect has 2 related aspects (e.g. Corruption - Human - Knowledge) and an opposite aspect (e.g. Human <> Beast). Every player has a total of 8,000 aspect points. A new player starts off with 1,000 aspect points on every aspect.
                            Aspects are changed by actions in quests. If, for example, you win points for the human aspect, you will simultaneously lose points in the beast aspect (its opposite aspect).
                            If an aspect increases, the related aspects will also increase. The opposite aspect will decrease a total of just as much as the three opposite aspects together!
                            If you increase an aspect above a certain threshold value, you will receive different bonuses on attributes or fight modifications.        <br/><br/>
                        </div>
                    </div>
                </div>
            </div>
            <div class="wrap-bottom-left">
                <div class="wrap-bottom-right">
                    <div class="wrap-bottom-middle"></div>
                </div>
            </div>
        </div>
    </div>
    -->
    <!--
    <div id="tabs-7">
        <div id="orbs_tab">
            <div class="wrap-top-left clearfix">
                <div class="wrap-top-right clearfix">
                    <div class="wrap-top-middle clearfix"></div>
                </div>
            </div>
            <div class="wrap-left clearfix">
                <div class="wrap-content wrap-right clearfix">
                    <script type="text/javascript">
                        function submitOrbGenerationFormWithSubmitType(sender, type)
                        {
                            if ($(sender).hasClass('btndisable'))
                            {
                                return false;
                            }

                            $('#orb_generation_form [name=action]').val(type);
                            $('#orb_generation_form').submit();

                            return true;
                        }

                        function setDefaultFeedbackState()
                        {
                            var defaultOrbGenerationFeedbackText = '(minimum 20, maximum 100)';
                            $(".generate_orb_button").removeClass("btn");
                            $(".generate_orb_button").addClass("btndisable");
                            $(".extra_costs_text").html(0);
                            $("#generate_splinters_amount_feedback").html(defaultOrbGenerationFeedbackText);
                        }

                        function orbGenerationRequirementsCheck()
                        {
                            var timer;
                            var value;
                            var minSplinters = 20;
                            var maxSplinters = 100;
                            var playerTs = 3;
                            var playerSplinters = 3213;

                            value = parseInt($("#splinterAmount").val());
                            if (timer)
                            {
                                clearTimeout(timer);
                                timer = null
                            }

                            timer = setTimeout(function()
                            {
                                if (isNaN(value)) {
                                    setDefaultFeedbackState();
                                    return;
                                }

                                if (value < minSplinters) {
                                    setDefaultFeedbackState();
                                    $("#generate_splinters_amount_feedback").html('<span style="color:#C00C0C;">Minimum of 20 fragments</span>');
                                    return;
                                }

                                if (value > maxSplinters) {
                                    setDefaultFeedbackState();
                                    $("#generate_splinters_amount_feedback").html('<span style="color:#C00C0C;">Maximum 100 fragments</span>');
                                    return;
                                }

                                if (value > playerSplinters) {
                                    setDefaultFeedbackState();
                                    $("#generate_splinters_amount_feedback").html('<span style="color:#C00C0C;">not enough fragments</span>');
                                    return;
                                }

                                if (!$("input[@name='orbType']:checked").val()) {
                                    setDefaultFeedbackState();
                                    return;
                                }

                                if (value <= playerSplinters)
                                {
                                    $.getJSON("/profile/ajaxCalculateOrbGenerationExtraCosts",
                                        'splinter='+value,
                                        function(data)
                                        {
                                            if (data.status)
                                            {
                                                $("#increased_gold_gold_costs").html(data.messages.increasedGoldPrice);
                                                $("#full_gold_gold_costs").html(data.messages.fullGoldPrice);
                                                $("#full_premium_premium_costs").html(data.messages.fullPremiumPrice);

                                                $("#generate_splinters_button_standard, #generate_splinters_button_increased_gold, #generate_splinters_button_full_gold, #generate_splinters_button_full_premium").removeClass("btndisable");
                                                $("#generate_splinters_button_standard, #generate_splinters_button_increased_gold, #generate_splinters_button_full_gold, #generate_splinters_button_full_premium").addClass("btn");
                                            }
                                            else
                                            {
                                                setDefaultFeedbackState();
                                            }
                                        }
                                    );
                                }

                            }, 500);
                        }

                        jQuery().ready(function()
                        {
                            $('.accordion').accordion({ autoHeight: false });

                            setDefaultFeedbackState();
                            var canCreate = 1;
                            if (canCreate)
                            {
                                $("#splinterAmount").keyup(function ()
                                {
                                    orbGenerationRequirementsCheck();
                                });
                                $('#orb_generation_form [name=orbType]').click(function ()
                                {
                                    orbGenerationRequirementsCheck();
                                });
                            }
                        });
                    </script>

                    <h3><div id="orb_generation_info_icon" onclick="$('#orb_generation_info_content').toggle();"><img src="http://s202.en.bitefight.gameforge.com/img/symbols/info.png"/></div>Create mighty orbs that make you stronger and more powerful.<div id="orb_generation_info_content">
                            <h3>Information about the orbs</h3>
                            <p>Orbs are crystal balls with which you can temporarily improve items. During its effect duration, an orb effects every equipped item in the concerned category. If you switch your weapon while a weapon orb is in effect, the effect will then work for the new weapon.<br/>
                                Orbs take up space and you can only have as many as the level of your own domicile in the hideout has.<br/>
                                You can use a maximum of 4 Orbs at the same time, but they need to belong to different categories. You can't, for example, use two weapon orbs at the same time.<br/>
                                Orbs can be sold at the market place. Once they have been sold, they are soul bound.<br/>
                                Some orbs give you access to talents: orb aura works like transparency, orb song works like the Negation Master, orb rage works like pure power and orb life works like the great feast. You can use the auras provided by the orbs independently of your level.<br/>
                                You need at least 20 fragments and a maximum of 100 fragments per orb. The more fragments you use, the mightier the orb becomes.<br/>
                                Normally there is a 25% chance that you can successfully produce an orb.<br/>
                                You can find fragments everywhere: in the grotto, whilst hunting humans, whilst experiencing adventures or as a reward in the mission system.<br/>
                                You can also get a fragment when you defeat other players that are stronger than you. The fragments are not taken away from other players, but newly created instead.<br/>
                                Orbs bestow great power onto you, so don't hesitate to use them!</p></div></h3>
                    <form id="orb_generation_form" action="http://s202.en.bitefight.gameforge.com/profile/index#tabs-7" method="POST">
                        <div id="firstStep">
                            <h4><span>1.</span>Choose the number of fragments!</h4>
                            <p class="choose_splinters">Your fragments: 3.213 <img src="http://s202.en.bitefight.gameforge.com/img/symbols/res_splinters.png" alt="Fragments" align="absmiddle" border="0">           <span class="generate_to">»</span>Used fragments:<input type="text" name="splinterAmount" id="splinterAmount" /></p>
                            <p id="generate_splinters_amount_feedback"></p>
                        </div>
                        <div id="secondStep">
                            <h4><span>2.</span>Choose the item category that the orb is meant to work for!</h4>
                            <input type="radio" name="orbType" id="orbType" value="weapon">Weapon&nbsp;&nbsp;&nbsp;&nbsp;<input type="radio" name="orbType" id="orbType" value="armor">Armour&nbsp;&nbsp;&nbsp;&nbsp;<input type="radio" name="orbType" id="orbType" value="shield">Shield&nbsp;&nbsp;&nbsp;&nbsp;<input type="radio" name="orbType" id="orbType" value="boots">Boots&nbsp;&nbsp;&nbsp;&nbsp;<input type="radio" name="orbType" id="orbType" value="gloves">Gloves&nbsp;&nbsp;&nbsp;&nbsp;<input type="radio" name="orbType" id="orbType" value="helmet">Helmets&nbsp;&nbsp;&nbsp;&nbsp;<input type="radio" name="orbType" id="orbType" value="items">Jewellery&nbsp;&nbsp;&nbsp;&nbsp;    </div>
                        <div id="thirdStep">
                            <h4><span>3.</span>Choose a chance of success and generate your orb!</h4>
                            <p>
                            <div class="btn-left">
                                <div class="btn-right">
                                    <a id="generate_splinters_button_standard" class="generate_orb_button btndisable" href="#" onclick="return submitOrbGenerationFormWithSubmitType(this, 'standard');">
                                        <strong>50</strong>% chance for 0 <img src="http://s202.en.bitefight.gameforge.com/img/symbols/res2.gif" alt="Gold" align="absmiddle" border="0">                	</a>
                                </div>
                            </div>
                            <div class="btn-left">
                                <div class="btn-right">
                                    <a id="generate_splinters_button_increased_gold" class="generate_orb_button btndisable" href="#" onclick="return submitOrbGenerationFormWithSubmitType(this, 'increasedgold');">
                                        <strong>75</strong>% chance for <span id="increased_gold_gold_costs" class="extra_costs_text">0</span> <img src="http://s202.en.bitefight.gameforge.com/img/symbols/res2.gif" alt="Gold" align="absmiddle" border="0">					</a>
                                </div>
                            </div>
                            <div class="btn-left">
                                <div class="btn-right">
                                    <a id="generate_splinters_button_full_gold" class="generate_orb_button btndisable" href="#" onclick="return submitOrbGenerationFormWithSubmitType(this, 'fullgold');">
                                        <strong>100</strong>% chance for <span id="full_gold_gold_costs" class="extra_costs_text">0</span> <img src="http://s202.en.bitefight.gameforge.com/img/symbols/res2.gif" alt="Gold" align="absmiddle" border="0">                    </a>
                                </div>
                            </div>
                            <div class="btn-left">
                                <div class="btn-right">
                                    <a id="generate_splinters_button_full_premium" class="generate_orb_button btndisable" href="#" onclick="return submitOrbGenerationFormWithSubmitType(this, 'fullpremium');">
                                        <strong>100</strong>% chance for <span id="full_premium_premium_costs" class="extra_costs_text">0</span> <img src="http://s202.en.bitefight.gameforge.com/img/symbols/res3.gif" alt="Hellstones" align="absmiddle" border="0">                    </a>
                                </div>
                            </div>
                        </div>

                        <br/>

                        <input type="hidden" name="action" value=""/>

                        <div style="clear:both"></div>
                    </form>
                    <div class="accordion">
                        <h3><a href="#" title="">Active orbs ( 0 / 4 )</a></h3>
                        <div>
                        </div>
                        <h3><a href="#">Available orbs ( 0 / 11 )</a></h3>
                        <div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="wrap-bottom-left">
                <div class="wrap-bottom-right">
                    <div class="wrap-bottom-middle"></div>
                </div>
            </div>
        </div>
    </div>
    -->
</div>

<!--
<script type="text/javascript">
    jQuery().ready(function(){
        $('#accordion').accordion({
            heightStyle: "content"
        });
    });
</script>

<br class="clearfloat" />
<br class="clearfloat" />
<br class="clearfloat" />

<div id="items">
    <div class="wrap-top-left clearfix">
        <div class="wrap-top-right clearfix">
            <div class="wrap-top-middle clearfix"></div>
        </div>
    </div>
    <div class="wrap-left clearfix">
        <div class="wrap-content wrap-right clearfix">

            <div class="table-wrap">
                <h2>&nbsp;Items ( 22 / 25 )</h2>
                <div id="accordion">
                    <h3>
                        <a href="#">Potions ( 15 )</a>
                    </h3>
                    <div>
                        <table cellpadding="2" cellspacing="2" border="0" width="100%">
                            <tr>
                                <td class='inactive itemslot'><div style="position:relative;width:300px;">
                                        <img src="http://s202.en.bitefight.gameforge.com/img/items/2/4.jpg" alt="100% Healing Potion (will give you full health)" style="border: 1px solid #6f86a9;">
                                        <div style="position:absolute;right:90px;top:15px;z-index:9999">
                                        </div>
                                    </div></td>
                                <td class='inactive'>
                                    <strong>100% Healing Potion (will give you full health)</strong><br />(Your inventory: 2 item(s))<br /><br />Resale value: 0<img src="http://s202.en.bitefight.gameforge.com/img/symbols/res2.gif" alt="Gold" align="absmiddle" border="0"><br /><br />Immediately heals 100% of your Health<br /><br />Requirement: level 1        <br />
                                    <div class="btn-left left"><div class="btn-right">
                                            <a class="btn" href="http://s202.en.bitefight.gameforge.com/profile/useItem/2/4?__token=0ce051019480c8a8046458f2dfd98c2f">Use this item</a>
                                        </div></div>
                                    <br/></td>
                            </tr><tr>
                                <td class='inactive itemslot'><div style="position:relative;width:300px;">
                                        <img src="http://s202.en.bitefight.gameforge.com/img/items/2/17.jpg" alt="Energy Potion">
                                        <div style="position:absolute;right:90px;top:15px;z-index:9999">
                                        </div>
                                    </div></td>
                                <td class='inactive'>
                                    <strong>Energy Potion</strong><br />(Your inventory: 13 item(s))<br /><br />Resale value: 250<img src="http://s202.en.bitefight.gameforge.com/img/symbols/res2.gif" alt="Gold" align="absmiddle" border="0"><br /><br />Energy: +10<br />Duration of effect: 06:00:00<br /><br />Requirement: level 1        <br />
                                    <div class="btn-left left"><div class="btn-right">
                                            <a class="btn" href="http://s202.en.bitefight.gameforge.com/profile/useItem/2/17?__token=0ce051019480c8a8046458f2dfd98c2f">Use this item</a>
                                        </div></div>
                                    <br/></td>
                            </tr>                        </table>
                    </div>
                    <h3>
                        <a href="#">Weapons ( 1 )</a>
                    </h3>
                    <div>
                        <table cellpadding="2" cellspacing="2" border="0" width="100%">
                            <tr>
                                <td class='active itemslot'><div style="position:relative;width:300px;">
                                        <img src="http://s202.en.bitefight.gameforge.com/img/items/1/78.jpg" alt="Sonisha">
                                        <div style="position:absolute;right:20px;top:15px;z-index:9999">
                                        </div>
                                    </div></td>
                                <td class='active'>
                                    <strong>Sonisha</strong><br />(Your inventory: 1 item(s))<br /><br />Resale value: 942.603<img src="http://s202.en.bitefight.gameforge.com/img/symbols/res2.gif" alt="Gold" align="absmiddle" border="0"><br /><br />Basic damage: +8<br />Bonus damage: +24<br />Strength: +50<br /><br />Requirement: level 195        <br />
                                    <br/></td>
                            </tr>                        </table>
                    </div>
                    <h3>
                        <a href="#">Helmets ( 1 )</a>
                    </h3>
                    <div>
                        <table cellpadding="2" cellspacing="2" border="0" width="100%">
                            <tr>
                                <td class='active itemslot'><div style="position:relative;width:300px;">
                                        <img src="http://s202.en.bitefight.gameforge.com/img/items/3/45.jpg" alt="Bergor">
                                        <div style="position:absolute;right:90px;top:15px;z-index:9999">
                                        </div>
                                    </div></td>
                                <td class='active'>
                                    <strong>Bergor</strong><br />(Your inventory: 1 item(s))<br /><br />Resale value: 931.061<img src="http://s202.en.bitefight.gameforge.com/img/symbols/res2.gif" alt="Gold" align="absmiddle" border="0"><br /><br />Basic damage (on opponent): -5<br />Bonus damage (on opponent): -13<br />Endurance: +50<br /><br />Requirement: level 194        <br />
                                    <br/></td>
                            </tr>                        </table>
                    </div>
                    <h3>
                        <a href="#">Armour ( 1 )</a>
                    </h3>
                    <div>
                        <table cellpadding="2" cellspacing="2" border="0" width="100%">
                            <tr>
                                <td class='active itemslot'><div style="position:relative;width:300px;">
                                        <img src="http://s202.en.bitefight.gameforge.com/img/items/4/53.jpg" alt="Urrosh">
                                        <div style="position:absolute;right:90px;top:15px;z-index:9999">
                                        </div>
                                    </div></td>
                                <td class='active'>
                                    <strong>Urrosh</strong><br />(Your inventory: 1 item(s))<br /><br />Resale value: 885.719<img src="http://s202.en.bitefight.gameforge.com/img/symbols/res2.gif" alt="Gold" align="absmiddle" border="0"><br /><br />Basic damage (on opponent): -4<br />Bonus damage (on opponent): -12<br />Endurance: +49<br /><br />Requirement: level 190        <br />
                                    <br/></td>
                            </tr>                        </table>
                    </div>
                    <h3>
                        <a href="#">Jewellery ( 1 )</a>
                    </h3>
                    <div>
                        <table cellpadding="2" cellspacing="2" border="0" width="100%">
                            <tr>
                                <td class='active itemslot'><div style="position:relative;width:300px;">
                                        <img src="http://s202.en.bitefight.gameforge.com/img/items/5/42.jpg" alt="Sytyr">
                                        <div style="position:absolute;right:90px;top:15px;z-index:9999">
                                        </div>
                                    </div></td>
                                <td class='active'>
                                    <strong>Sytyr</strong><br />(Your inventory: 1 item(s))<br /><br />Resale value: 560.793<img src="http://s202.en.bitefight.gameforge.com/img/symbols/res2.gif" alt="Gold" align="absmiddle" border="0"><br /><br />Dexterity: +85<br /><br />Requirement: level 157        <br />
                                    <br/></td>
                            </tr>                        </table>
                    </div>
                    <h3>
                        <a href="#">Gloves ( 1 )</a>
                    </h3>
                    <div>
                        <table cellpadding="2" cellspacing="2" border="0" width="100%">
                            <tr>
                                <td class='active itemslot'><div style="position:relative;width:300px;">
                                        <img src="http://s202.en.bitefight.gameforge.com/img/items/6/45.jpg" alt="Kwera">
                                        <div style="position:absolute;right:90px;top:15px;z-index:9999">
                                        </div>
                                    </div></td>
                                <td class='active'>
                                    <strong>Kwera</strong><br />(Your inventory: 1 item(s))<br /><br />Resale value: 1.075.088<img src="http://s202.en.bitefight.gameforge.com/img/symbols/res2.gif" alt="Gold" align="absmiddle" border="0"><br /><br />Strength: +63<br />Dexterity: +42<br /><br />Requirement: level 206        <br />
                                    <br/></td>
                            </tr>                        </table>
                    </div>
                    <h3>
                        <a href="#">Boots ( 1 )</a>
                    </h3>
                    <div>
                        <table cellpadding="2" cellspacing="2" border="0" width="100%">
                            <tr>
                                <td class='active itemslot'><div style="position:relative;width:300px;">
                                        <img src="http://s202.en.bitefight.gameforge.com/img/items/7/26.jpg" alt="Penumbraal">
                                        <div style="position:absolute;right:90px;top:15px;z-index:9999">
                                        </div>
                                    </div></td>
                                <td class='active'>
                                    <strong>Penumbraal</strong><br />(Your inventory: 1 item(s))<br /><br />Resale value: 778.095<img src="http://s202.en.bitefight.gameforge.com/img/symbols/res2.gif" alt="Gold" align="absmiddle" border="0"><br /><br />Defence: +38<br />Dexterity: +57<br /><br />Requirement: level 180        <br />
                                    <br/></td>
                            </tr>                        </table>
                    </div>
                    <h3>
                        <a href="#">Shields ( 1 )</a>
                    </h3>
                    <div>
                        <table cellpadding="2" cellspacing="2" border="0" width="100%">
                            <tr>
                                <td class='active itemslot'><div style="position:relative;width:300px;">
                                        <img src="http://s202.en.bitefight.gameforge.com/img/items/8/26.jpg" alt="Jameter">
                                        <div style="position:absolute;right:90px;top:15px;z-index:9999">
                                        </div>
                                    </div></td>
                                <td class='active'>
                                    <strong>Jameter</strong><br />(Your inventory: 1 item(s))<br /><br />Resale value: 463.560<img src="http://s202.en.bitefight.gameforge.com/img/symbols/res2.gif" alt="Gold" align="absmiddle" border="0"><br /><br />Defence: +80<br /><br />Requirement: level 145        <br />
                                    <br/></td>
                            </tr>                        </table>
                    </div>
                    <h3><a href="#">Totems ( 1 / 11 )</a></h3>
                    <div>
                        <table cellpadding="2" cellspacing="2" border="0" width="100%">
                            <tr>
                                <td class='active itemslot'>
                                    <img src="http://s202.en.bitefight.gameforge.com/img/totems/9.jpg" alt="Ear from GustiBrother" >
                                </td>
                                <td class='active'>
                                    <strong>Ear from GustiBrother <span style="color:orangered">(activated)</span></strong><br>
                                    <br>
                                    Dexterity: +4<br />Endurance: +3<br />    </td>
                            </tr>                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="wrap-bottom-left">
        <div class="wrap-bottom-right">
            <div class="wrap-bottom-middle"></div>
        </div>
    </div>
</div>
-->