<div id="search">
    <div class="wrap-top-left clearfix">
        <div class="wrap-top-right clearfix">
            <div class="wrap-top-middle clearfix"></div>
        </div>
    </div>
    <div class="wrap-left clearfix">
        <div class="wrap-content wrap-right clearfix">
            <h2><img src="<?php echo getAssetLink('img/symbols/race'.$user->race.'small.gif'); ?>" alt="">What are you looking for?</h2>
            <form action="<?php echo getUrl('search'); ?>" method="POST" class="clearfix">
                <input type="hidden" name="<?php echo $this->security->getTokenKey() ?>" value="<?php echo $this->security->getToken() ?>"/>
                <div id="searchOptions">
                    <div>
                        <input type="radio" name="searchtyp" value="name" <?php if($search_type == 'name') echo 'checked'; ?>>
                        <label>Player</label>
                    </div>
                    <div>
                        <input type="radio" name="searchtyp" value="clan" <?php if($search_type == 'clan') echo 'checked'; ?>>
                        <label>Clan (Name)</label>
                    </div>
                    <div>
                        <input type="radio" name="searchtyp" value="tag" <?php if($search_type == 'tag') echo 'checked'; ?>>
                        <label>Clan (Clan tag)</label>
                    </div>
                </div>
                <div id="searchField">
                    <div class="btn-left right">
                        <div class="btn-right">
                            <input type="submit" name="search" value="search" class="btn">
                        </div>
                    </div>
                    <label>Text:</label>
                    <input type="text" name="text" size="30" maxlength="30" value="<?php if(isset($searchString)) echo e($searchString); ?>">
                    <input id="exact" type="checkbox" class="check" name="exakt" <?php if(isset($exact) && $exact) echo 'checked'; ?>>
                    <label class="checklabel" for="exact">only show exact results</label>
                </div>
            </form>
            <?php if(isset($results)): ?>
            <h2 style="margin-bottom: 1rem;"><img src="<?php echo getAssetLink('img/symbols/race'.$user->race.'small.gif'); ?>">Results</h2>
            <table width="80%">
                <tbody>
                <tr><td>Race</td>
                <?php if($search_type == 'player'): ?>
                    <td>Player</td>
                <?php else: ?>
                    <td>Clan</td><td>Members</td>
                <?php endif; ?>
                <td>Entire booty</td></tr>
                <?php foreach($results as $res): ?>
                    <?php if($search_type == 'player'): ?>
                        <tr>
                            <td>
                                <img src="<?php echo getAssetLink('img/symbols/race'.$res->race.'small.gif'); ?>" title="<?php echo $res->race == 1?'Vampire':'Werewolf'; ?>" border="0">
                            </td>
                            <td>
                                <a href="<?php echo getUrl('profile/player/'.$res->id); ?>"><?php echo $res->name; ?></a>
                            </td>
                            <td><?php echo prettyNumber($res->s_booty); ?></td>
                        </tr>
                    <?php else: ?>
                        <tr>
                            <td>
                                <img src="<?php echo getAssetLink('img/symbols/race'.$res->race.'small.gif'); ?>" title="<?php echo $res->race == 1?'Vampire':'Werewolf'; ?>" border="0">
                            </td>
                            <td>
                                <a href="<?php echo getUrl('clan/view/'.$res->id); ?>"><?php echo e($res->name); ?> [<?php echo e($res->tag); ?>]</a>
                            </td><td><?php echo $res->members; ?> / <?php if($res->stufe == 0) echo 1; else echo $res->stufe * 3; ?></td>
                            <td><?php echo prettyNumber($res->booty); ?></td>
                        </tr>
                    <?php endif; ?>
                <?php endforeach; ?>
                <tr>
                    <td class="no-bg" colspan="2"><?php if(count($results) > 0):echo count($results); ?> Results (25 max.)<?php else: ?>no results<?php endif; ?></td>
                </tr>
                </tbody>
            </table>
            <?php endif; ?>
        </div>
    </div>
    <div class="wrap-bottom-left">
        <div class="wrap-bottom-right">
            <div class="wrap-bottom-middle"></div>
        </div>
    </div>
</div>