<div class="btn-left left">
    <div class="btn-right"><a href="<?php echo getUrl('profile/index#tabs-5'); ?>" class="btn"><?php echo \Bitefight\Library\Translate::_('back'); ?></a></div>
</div>
<br class="clearfloat">
<div id="specialSkills">
    <div class="wrap-top-left clearfix">
        <div class="wrap-top-right clearfix">
            <div class="wrap-top-middle clearfix"></div>
        </div>
    </div>
    <div class="wrap-left clearfix">
        <div class="wrap-content wrap-right clearfix">
            <h2><img src="<?php echo getAssetLink('img/symbols/race'.$user->race.'small.gif'); ?>" alt=""><?php echo \Bitefight\Library\Translate::_('profile_talent_talents'); ?></h2>
            <div class="table-wrap">
                <table id="talentsOptions" width="100%" border="0">
                    <tbody><tr>
                        <td colspan="2">
                            <span class="gold">
                                <?php echo \Bitefight\Library\Translate::_('gold'); ?>: <?php echo prettyNumber($user->gold); ?> <img src="<?php echo getAssetLink('img/symbols/res2.gif'); ?>" alt="<?php echo \Bitefight\Library\Translate::_('gold'); ?>" align="absmiddle" border="0">
                            </span>&nbsp;&nbsp;<span class="gold">
                                <!--<a href="https://s202-en.bitefight.gameforge.com:443/city/voodoo">--><?php echo \Bitefight\Library\Translate::_('hellstones'); ?><!--</a>-->: <?php echo prettyNumber($user->hellstone); ?> <img src="<?php echo getAssetLink('img/symbols/res3.gif'); ?>" alt="<?php echo \Bitefight\Library\Translate::_('hellstones'); ?>" align="absmiddle" border="0">
                            </span>
                        </td>
                    </tr>
                    <tr>
                        <td valign="top" align="left">
                            <table cellpadding="2" cellspacing="2" border="0" class="noBackground">
                                <tbody><tr>
                                    <td style="vertical-align:middle;"><strong><?php echo \Bitefight\Library\Translate::_('profile_talent_display_filter'); ?>:</strong></td>
                                    <td>
                                        <select size="1" onchange="location = this.options[this.selectedIndex].value;">
                                            <option value="talents?filter=1" <?php if($filter == 1) echo 'selected=""' ?>><?php echo \Bitefight\Library\Translate::_('profile_talent_display_filter_learned'); ?></option>
                                            <option value="talents?filter=2" <?php if($filter == 2) echo 'selected=""' ?>><?php echo \Bitefight\Library\Translate::_('profile_talent_display_filter_learnable'); ?></option>
                                            <option value="talents?filter=3" <?php if($filter == 3) echo 'selected=""' ?>><?php echo \Bitefight\Library\Translate::_('profile_talent_display_filter_all'); ?></option>
                                        </select>
                                    </td>
                                </tr>
                                <tr class="next_point_info">
                                    <td style="vertical-align:middle;"><strong><?php echo \Bitefight\Library\Translate::_('profile_talent_available_points'); ?>:</strong></td>
                                    <td style="vertical-align:middle;"><center><b><?php echo $available; ?></b></center></td>
                                </tr>
                                <tr class="next_point_info">
                                    <td style="vertical-align:middle;"><strong><?php echo \Bitefight\Library\Translate::_('profile_talent_used_points'); ?>:</strong></td>
                                    <td style="vertical-align:middle;"><center><b><?php echo $used_points; ?></b></center></td>
                                </tr>
                                <tr class="next_point_info">
                                    <td style="vertical-align:middle;"><strong><?php echo \Bitefight\Library\Translate::_('profile_talent_max_points'); ?>:</strong></td>
                                    <td style="vertical-align:middle;"><center><b><?php echo $max_points; ?></b></center></td>
                                </tr>
                                <tr class="next_point_info">
                                    <td style="vertical-align:middle;"><strong><?php echo \Bitefight\Library\Translate::_('profile_talent_next_points'); ?></strong><br><?php echo \Bitefight\Library\Translate::_('level'); ?>: <?php echo $next_talent_level; ?></td>
                                    <td style="vertical-align:middle;"><center><b>+2</b></center></td>
                                </tr>
                                </tbody></table>
                        </td>
                        <td>&nbsp;</td>
                        <td valign="top" align="right">
                            <table cellpadding="2" cellspacing="2" border="0">
                                <tbody><tr>
                                    <form action="<?php echo getUrl('user/talents'); ?>" method="POST">
                                        <input type="hidden" name="<?php echo $this->security->getTokenKey() ?>" value="<?php echo $this->security->getToken() ?>"/>
                                        <td style="vertical-align:middle;"><strong><?php echo \Bitefight\Library\Translate::_('profile_talent_form_next_point'); ?>:</strong></td>
                                        <td><input type="hidden" name="filter" value="<?php echo $filter; ?>"><input type="submit" class="input" name="buypoint" value="buy now" <?php if($max_points - $user->talent_points == 0 || $user->gold < $new_talent_price) echo 'disabled=""' ?>></td>
                                        <td style="vertical-align:middle;" nowrap=""><?php echo prettyNumber($new_talent_price); ?> <img src="https://s202-en.bitefight.gameforge.com:443/img/symbols/res2.gif" alt="Gold" align="absmiddle" border="0"></td>
                                    </form>
                                </tr>
                                <tr>
                                    <form action="<?php echo getUrl('user/talents'); ?>" method="POST">
                                        <input type="hidden" name="<?php echo $this->security->getTokenKey() ?>" value="<?php echo $this->security->getToken() ?>"/>
                                        <td style="vertical-align:middle;"><strong><?php echo \Bitefight\Library\Translate::_('profile_talent_form_reset_gold_and_talents'); ?>:</strong></td>
                                        <td><input type="hidden" name="filter" value="<?php echo $filter; ?>"><input type="submit" class="input" name="resetpoinths" value="Reset" <?php if($user->hellstone < 19) echo 'disabled=""'; ?>></td>
                                        <td style="vertical-align:middle;" nowrap="">19 <img src="<?php echo getAssetLink('img/symbols/res3.gif'); ?>" alt="<?php echo \Bitefight\Library\Translate::_('hellstones'); ?>" align="absmiddle" border="0"></td>
                                    </form>
                                </tr>
                                <tr>
                                    <form action="<?php echo getUrl('user/talents'); ?>" method="POST">
                                        <input type="hidden" name="<?php echo $this->security->getTokenKey() ?>" value="<?php echo $this->security->getToken() ?>"/>
                                        <td style="vertical-align:middle;"><strong><?php echo \Bitefight\Library\Translate::_('profile_talent_form_reset_all_points'); ?>:</strong></td>
                                        <td><input type="hidden" name="filter" value="<?php echo $filter; ?>"><input type="submit" class="input" name="resetpointg" value="Reset" <?php if($user->gold < $talent_reset_price || $user->talent_points == $available) echo 'disabled=""'; ?>></td>
                                        <td style="vertical-align:middle;" nowrap=""><?php echo prettyNumber($talent_reset_price); ?> <img src="<?php echo getAssetLink('img/symbols/res2.gif'); ?>" alt="<?php echo \Bitefight\Library\Translate::_('gold'); ?>" align="absmiddle" border="0"></td>
                                    </form>
                                </tr>
                                <tr>
                                    <td style="vertical-align:middle;"><strong><?php echo \Bitefight\Library\Translate::_('profile_talent_form_reset_single_talent'); ?>:</strong></td>
                                    <td style="vertical-align:middle;" colspan="2" nowrap="">2 <img src="<?php echo getAssetLink('img/symbols/res3.gif'); ?>" alt="<?php echo \Bitefight\Library\Translate::_('hellstones'); ?>" align="absmiddle" border="0"></td>
                                </tr>
                                </tbody>
                            </table>
                        </td>
                    </tr>
                    </tbody>
                </table>
                <h2><img src="<?php echo getAssetLink('img/symbols/race'.$user->race.'small.gif'); ?>"><?php echo \Bitefight\Library\Translate::_('talents'); ?></h2>
                <table border="0" cellpadding="0" cellspacing="2" width="100%" class="talents_bg">
                    <tbody><tr class="talents_headline">
                        <th><?php echo \Bitefight\Library\Translate::_('level'); ?></th>
                        <th colspan="2" align="left">&nbsp;<?php echo \Bitefight\Library\Translate::_('profile_talent_talents'); ?></th>
                    </tr>
                    <?php foreach ($talents as $talent): ?>
                        <tr>
                            <td align="center" class="talent_level"><b><?php echo $talent[0]->level; ?></b></td>
                            <td class="<?php if($talent[0]->user_id) echo 'talent_buyed'; elseif(getLevel($user->exp) >= $talent[0]->level && (!isset($talent[1]) || (isset($talent[1]) && !$talent[1]->user_id))) echo 'talent_buyable'; else echo 'talent_inactive' ?>">
                                <table width="100%" border="0">
                                    <tbody>
                                    <tr>
                                        <td class="no-bg" align="left" width="25"><img src="<?php echo getAssetLink('img/symbols/talent_'.($talent[0]->active?'active':'passive').'.png'); ?>" title="<?php echo \Bitefight\Library\Translate::_('profile_talent_talent_type_'.$talent[0]->active); ?>"></td>
                                        <td class="no-bg" align="left">
                                            <div class="tooltip" title='<?php $this->partial('partials/talent_tooltip_content', ['talent_obj' => $talent[0]]) ?>'><b><?php echo \Bitefight\Library\Translate::_tn($talent[0]->id); ?></b></div>
                                        </td>
                                        <td class="no-bg align-right" align="right">
                                            <?php if($talent[0]->user_id && $user->hellstone >= 2 && $talent[0]->id != 1): ?>
                                                <form id="talent_reset<?php echo $talent[0]->id; ?>" action="<?php echo getUrl('user/talent/reset/single'); ?>" method="post">
                                                    <input type="hidden" name="<?php echo $this->security->getTokenKey() ?>" value="<?php echo $this->security->getToken() ?>"/>
                                                    <input type="hidden" name="talent_id" value="<?php echo $talent[0]->id; ?>">
                                                    <input type="hidden" name="filter" value="<?php echo $filter; ?>">
                                                </form>
                                                <a onclick="document.forms['talent_reset<?php echo $talent[0]->id; ?>'].submit();" class="buytalent">
                                                    <img src="<?php echo getAssetLink('img/symbols/reset.png'); ?>" alt="<?php echo \Bitefight\Library\Translate::_('profile_talent_reset_single'); ?>" title="<?php echo \Bitefight\Library\Translate::_('profile_talent_reset_single'); ?>"/>
                                                </a>
                                            <?php endif; ?>

                                            <?php
                                            if(!$talent[0]->user_id && $available && getLevel($user->exp) >= $talent[0]->level && (!isset($talent[1]) || (isset($talent[1]) && !$talent[1]->user_id))):
                                                ?>
                                                <form id="talent_buy<?php echo $talent[0]->id; ?>" action="<?php echo getUrl('user/talent/use'); ?>" method="post">
                                                    <input type="hidden" name="<?php echo $this->security->getTokenKey() ?>" value="<?php echo $this->security->getToken() ?>"/>
                                                    <input type="hidden" name="talent_id" value="<?php echo $talent[0]->id; ?>">
                                                    <input type="hidden" name="filter" value="<?php echo $filter; ?>">
                                                </form>
                                                <a onclick="document.forms['talent_buy<?php echo $talent[0]->id; ?>'].submit();" class="buytalent">
                                                    <img src="<?php echo getAssetLink('img/symbols/iconplus.png'); ?>" alt="<?php echo \Bitefight\Library\Translate::_('profile_talent_buy_now'); ?>" title="<?php echo \Bitefight\Library\Translate::_('profile_talent_buy_now'); ?>">
                                                </a>
                                            <?php endif; ?>
                                        </td>
                                    </tr>
                                    </tbody>
                                </table>
                            </td>
                            <?php if(isset($talent[1])): ?>
                                <td class="<?php if($talent[1]->user_id) echo 'talent_buyed'; elseif(getLevel($user->exp) >= $talent[1]->level && !$talent[0]->user_id) echo 'talent_buyable'; else echo 'talent_inactive' ?>">
                                    <table width="100%" border="0">
                                        <tbody>
                                        <tr>
                                            <td class="no-bg" align="left" width="25"><img src="<?php echo getAssetLink('img/symbols/talent_'.($talent[1]->active?'active':'passive').'.png'); ?>" title="<?php echo \Bitefight\Library\Translate::_('profile_talent_talent_type_'.$talent[1]->active); ?>"></td>
                                            <td class="no-bg" align="left">
                                                <div class="tooltip" title='<?php $this->partial('partials/talent_tooltip_content', ['talent_obj' => $talent[1]]) ?>'><b><?php echo \Bitefight\Library\Translate::_tn($talent[1]->id); ?></b></div>
                                            </td>
                                            <td class="no-bg align-right" align="right">

                                                <?php if($talent[1]->user_id && $user->hellstone > 1): ?>
                                                    <form id="talent_reset<?php echo $talent[1]->id; ?>" action="<?php echo getUrl('user/talent/reset/single'); ?>" method="post">
                                                        <input type="hidden" name="<?php echo $this->security->getTokenKey() ?>" value="<?php echo $this->security->getToken() ?>"/>
                                                        <input type="hidden" name="talent_id" value="<?php echo $talent[1]->id; ?>">
                                                        <input type="hidden" name="filter" value="<?php echo $filter; ?>">
                                                    </form>
                                                    <a onclick="document.forms['talent_reset<?php echo $talent[1]->id; ?>'].submit();" href="javascript:;" class="buytalent">
                                                        <img src="<?php echo getAssetLink('img/symbols/reset.png'); ?>" alt="<?php echo \Bitefight\Library\Translate::_('profile_talent_reset_single'); ?>" title="<?php echo \Bitefight\Library\Translate::_('profile_talent_reset_single'); ?>"/>
                                                    </a>
                                                <?php endif; ?>
                                                <?php if(!$talent[0]->user_id && $available && getLevel($user->exp) >= $talent[1]->level && !$talent[1]->user_id): ?>
                                                    <form id="talent_buy<?php echo $talent[1]->id; ?>" action="<?php echo getUrl('user/talent/use'); ?>" method="post">
                                                        <input type="hidden" name="<?php echo $this->security->getTokenKey() ?>" value="<?php echo $this->security->getToken() ?>"/>
                                                        <input type="hidden" name="talent_id" value="<?php echo $talent[1]->id; ?>">
                                                        <input type="hidden" name="filter" value="<?php echo $filter; ?>">
                                                    </form>
                                                    <a onclick="document.forms['talent_buy<?php echo $talent[1]->id; ?>'].submit();" href="javascript:;" class="buytalent">
                                                        <img src="<?php echo getAssetLink('img/symbols/iconplus.png'); ?>" alt="<?php echo \Bitefight\Library\Translate::_('profile_talent_buy_now'); ?>" title="<?php echo \Bitefight\Library\Translate::_('profile_talent_buy_now'); ?>">
                                                    </a>
                                                <?php endif; ?>
                                            </td>
                                        </tr>
                                        </tbody>
                                    </table>
                                </td>
                            <?php endif; ?>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
                <br class="cleafloat">
            </div>
        </div>
    </div>
    <div class="wrap-bottom-left">
        <div class="wrap-bottom-right">
            <div class="wrap-bottom-middle"></div>
        </div>
    </div>
</div>