<div class="btn-left left">
    <div class="btn-right"><a href="<?php echo getUrl('profile/index#tabs-5'); ?>" class="btn"><?php echo \Bitefight\Library\Translate::_('back'); ?></a></div>
</div>
<br class="clearfloat">
<div id="specialSkills">
    <div class="wrap-top-left clearfix">
        <div class="wrap-top-right clearfix">
            <div class="wrap-top-middle clearfix"></div>
        </div>
    </div>
    <div class="wrap-left clearfix">
        <div class="wrap-content wrap-right clearfix">
            <h2><img src="<?php echo getAssetLink('img/symbols/race'.$user->race.'small.gif'); ?>" alt=""><?php echo \Bitefight\Library\Translate::_('profile_talent_talents'); ?></h2>
            <div class="table-wrap">
                <table id="talentsOptions" width="100%" border="0">
                    <tbody><tr>
                        <td colspan="2">
                            <span class="gold"><?php echo \Bitefight\Library\Translate::_('gold'); ?>: 2.266 <img src="<?php echo getAssetLink('img/symbols/res2.gif'); ?>" alt="Gold" align="absmiddle" border="0"></span>&nbsp;&nbsp;<span class="gold"><a href="https://s202-en.bitefight.gameforge.com:443/city/voodoo">Hellstones</a>: 3 <img src="https://s202-en.bitefight.gameforge.com:443/img/symbols/res3.gif" alt="Hellstones" align="absmiddle" border="0"></span>
                        </td>
                    </tr>
                    <tr>
                        <td valign="top" align="left">
                            <table cellpadding="2" cellspacing="2" border="0" class="noBackground">
                                <tbody><tr>
                                    <td style="vertical-align:middle;"><strong>Display filter:</strong></td>
                                    <td>
                                        <select size="1" onchange="location = this.options[this.selectedIndex].value;">
                                            <option value="talents?filter=1">All learned talents</option><option value="talents?filter=2" selected="">Learnable talents</option><option value="talents?filter=3">All talents</option>                            </select>
                                    </td>
                                </tr>
                                <tr class="next_point_info">
                                    <td style="vertical-align:middle;"><strong>Available points:</strong></td>
                                    <td style="vertical-align:middle;"><center><b>0</b></center></td>
                                </tr>
                                <tr class="next_point_info">
                                    <td style="vertical-align:middle;"><strong>Used points:</strong></td>
                                    <td style="vertical-align:middle;"><center><b>31</b></center></td>
                                </tr>
                                <tr class="next_point_info">
                                    <td style="vertical-align:middle;"><strong>Maximum points:</strong></td>
                                    <td style="vertical-align:middle;"><center><b>31</b></center></td>
                                </tr>
                                <tr class="next_point_info">
                                    <td style="vertical-align:middle;"><strong>Next points</strong><br>Level: 289</td>
                                    <td style="vertical-align:middle;"><center><b>+2</b></center></td>
                                </tr>
                                </tbody></table>
                        </td>
                        <td>&nbsp;</td>
                        <td valign="top" align="right">
                            <table cellpadding="2" cellspacing="2" border="0">
                                <tbody><tr>
                                    <form action="https://s202-en.bitefight.gameforge.com:443/profile/talents?__token=c509f38d220a3c95329c4f18e93c099e" method="POST"></form>
                                    <td style="vertical-align:middle;"><strong>next point:</strong></td>
                                    <td><input type="hidden" name="filter" value="2"><input type="submit" class="input" name="buypoint" value="buy now" disabled=""></td>
                                    <td style="vertical-align:middle;" nowrap="">535.062 <img src="https://s202-en.bitefight.gameforge.com:443/img/symbols/res2.gif" alt="Gold" align="absmiddle" border="0"></td>

                                </tr>
                                <tr>
                                    <form action="https://s202-en.bitefight.gameforge.com:443/profile/talentsMasterReset?__token=c509f38d220a3c95329c4f18e93c099e" method="POST"></form>
                                    <td style="vertical-align:middle;"><strong>Reset gold price and relearn all talents:</strong></td>
                                    <td><input type="hidden" name="filter" value="2"><input type="submit" class="input" name="resetpoint" value="Reset" disabled=""></td>
                                    <td style="vertical-align:middle;" nowrap="">19 <img src="https://s202-en.bitefight.gameforge.com:443/img/symbols/res3.gif" alt="Hellstones" align="absmiddle" border="0"></td>

                                </tr>
                                <tr>
                                    <form action="https://s202-en.bitefight.gameforge.com:443/profile/talentsReset?__token=c509f38d220a3c95329c4f18e93c099e" method="POST"></form>
                                    <td style="vertical-align:middle;"><strong>Reset all points:</strong></td>
                                    <td><input type="hidden" name="filter" value="2"><input type="submit" class="input" name="resetpoint" value="Reset" disabled=""></td>
                                    <td style="vertical-align:middle;" nowrap="">3.395.900 <img src="https://s202-en.bitefight.gameforge.com:443/img/symbols/res2.gif" alt="Gold" align="absmiddle" border="0"></td>

                                </tr>
                                <tr>
                                    <td style="vertical-align:middle;"><strong>Reset single talent:</strong></td>
                                    <td style="vertical-align:middle;" colspan="2" nowrap="">2 <img src="https://s202-en.bitefight.gameforge.com:443/img/symbols/res3.gif" alt="Hellstones" align="absmiddle" border="0"></td>
                                </tr>
                                </tbody></table>
                        </td>
                    </tr>
                    </tbody></table>
                <h2><img src="/img/symbols/race1small.gif">Talents</h2>
                <table border="0" cellpadding="0" cellspacing="2" width="100%" class="talents_bg">
                    <tbody><tr class="talents_headline">
                        <th>Level</th>
                        <th colspan="2" align="left">&nbsp;Talents</th>
                    </tr>
                    <?php foreach ($talents as $talent): ?>
                        <tr>
                            <td align="center" class="talent_level"><b><?php echo $talent[0]->level; ?></b></td>
                            <td class="talent_buyable">
                                <table width="100%" border="0">
                                    <tbody>
                                    <tr>
                                        <td class="no-bg" align="left" width="25"><img src="<?php echo getAssetLink('img/symbols/talent_'.($talent[0]->active?'active':'passive').'.png'); ?>" title="<?php echo \Bitefight\Library\Translate::_('profile_talent_talent_type_'.$talent[0]->active); ?>"></td>
                                        <td class="no-bg" align="left">
                                            <div class="tooltip" title='<table class="noBackground"><tbody><tr><td nowrap="" style="font-size: 1.1em;"><?php echo \Bitefight\Library\Translate::_tn($talent[0]->id); ?></td></tr><tr><td nowrap=""><?php echo \Bitefight\Library\Translate::_('profile_talent_talent_type_'.$talent[0]->active); ?></td></tr><tr><td><?php echo \Bitefight\Library\Translate::_td($talent[0]->id); ?></td></tr><?php foreach(getTalentPropertyArray($talent[0]) as $prop) echo '<tr><td nowrap="">'.$prop[1].' '.$prop[0].'</td></tr>' ?></tbody></table>'><b><?php echo \Bitefight\Library\Translate::_tn($talent[0]->id); ?></b></div>
                                        </td>
                                        <td class="no-bg align-right" align="right"></td>
                                    </tr>
                                    </tbody>
                                </table>
                            </td>
                            <?php if(isset($talent[1])): ?>
                                <td class="talent_buyable">
                                    <table width="100%" border="0">
                                        <tbody>
                                        <tr>
                                            <td class="no-bg" align="left" width="25"><img src="<?php echo getAssetLink('img/symbols/talent_'.($talent[1]->active?'active':'passive').'.png'); ?>" title="<?php echo \Bitefight\Library\Translate::_('profile_talent_talent_type_'.$talent[1]->active); ?>"></td>
                                            <td class="no-bg" align="left">
                                                <div class="tooltip" title='<table class="noBackground"><tbody><tr><td nowrap="" style="font-size: 1.1em;"><?php echo \Bitefight\Library\Translate::_tn($talent[1]->id); ?></td></tr><tr><td nowrap=""><?php echo \Bitefight\Library\Translate::_('profile_talent_talent_type_'.$talent[1]->active); ?></td></tr><tr><td><?php echo \Bitefight\Library\Translate::_td($talent[1]->id); ?></td></tr><?php foreach(getTalentPropertyArray($talent[1]) as $prop) echo '<tr><td nowrap="">'.$prop[1].' '.$prop[0].'</td></tr>' ?></tbody></table>'><b><?php echo \Bitefight\Library\Translate::_tn($talent[1]->id); ?></b></div>
                                            </td>
                                            <td class="no-bg align-right" align="right"></td>
                                        </tr>
                                        </tbody>
                                    </table>
                                </td>
                            <?php endif; ?>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
                <br class="cleafloat">
            </div>
        </div>
    </div>
    <div class="wrap-bottom-left">
        <div class="wrap-bottom-right">
            <div class="wrap-bottom-middle"></div>
        </div>
    </div>
</div>