<div class="btn-left left"><div class="btn-right"><a href="<?php echo getUrl('message'); ?>" class="btn">back</a></div></div>
<br class="clearfloat">
<div id="handleFolders">
    <div class="wrap-top-left clearfix">
        <div class="wrap-top-right clearfix">
            <div class="wrap-top-middle clearfix"></div>
        </div>
    </div>
    <div class="wrap-left clearfix">
        <div class="wrap-content wrap-right clearfix">
            <h2><img src="<?php echo getAssetLink('img/symbols/race'.$user->race.'small.gif'); ?>" alt="">manage folders</h2>
            <div class="table-wrap">
                <table cellpadding="2" cellspacing="2" border="0" width="100%">
                    <tbody><tr>
                        <td class="no-bg">Folder</td>
                        <td class="no-bg">Action</td>
                    </tr>
                    <tr>
                        <td class="tdn"><span style="color:#fff; font-weight:bold;">Inbox</span></td>
                        <td class="tdn">-</td>
                        <td class="tdn">-</td>
                    </tr>

                    <?php foreach($folders as $folder): ?>
                        <tr>
                            <form action="<?php echo getUrl('message/folders'); ?>" method="POST">
                                <input type="hidden" name="<?php echo $this->security->getTokenKey() ?>" value="<?php echo $this->security->getToken() ?>"/>
                                <td class="tdn"><span style="color:#fff; font-weight:bold;;"><?php echo e($folder->folder_name); ?></span></td>
                                <td class="tdn">
                                    <input type="hidden" name="folderid" value="<?php echo $folder->id; ?>">
                                    <div class="btn-left left">
                                        <div class="btn-right">
                                            <input class="btn" type="submit" name="action" value="delete">
                                        </div>
                                    </div>
                                    <div class="btn-left left">
                                        <div class="btn-right">
                                            <input class="btn" type="submit" name="action" value="rename">
                                        </div>
                                    </div>
                                </td>
                                <td class="tdn">
                                    <?php if($folder_max_min->min !== $folder->folder_order): ?>
                                        <div class="btn-left left">
                                            <div class="btn-right">
                                                <input class="btn" type="submit" name="action" value="move up">
                                            </div></div>
                                    <?php endif; ?>
                                    <?php if($folder_max_min->max !== $folder->folder_order): ?>
                                        <div class="btn-left left">
                                            <div class="btn-right">
                                                <input class="btn" type="submit" name="action" value="move down">
                                            </div>
                                        </div>
                                    <?php endif; ?>
                                </td>
                            </form>
                        </tr>
                        <?php if($folder_rename_id == $folder->id): ?>
                            <tr>
                                <td class="tdn" colspan="3">
                                    <form action="<?php echo getUrl('message/folders'); ?>" method="POST">
                                        <input type="hidden" name="<?php echo $this->security->getTokenKey() ?>" value="<?php echo $this->security->getToken() ?>"/>
                                        <label class="left">new name:</label>
                                        <input class="input left" type="text" name="name" value="" maxlength="50" size="20">
                                        <input type="hidden" name="folderid" value="<?php echo $folder->id; ?>">
                                        <input type="hidden" name="action" value="save new name">
                                        <div class="btn-left left"><div class="btn-right"><input class="btn" type="submit" name="rename" value="Save"></div></div>
                                    </form>
                                </td>
                            </tr>
                        <?php endif; ?>
                    <?php endforeach; ?>

                    <tr>
                        <td class="tdn"><span style="color:#fff; font-weight:bold;">Outbox</span></td>
                        <td class="tdn">-</td>
                        <td class="tdn">-</td>
                    </tr>
                    <?php if($folder_action_info): ?>
                    <tr>
                        <td colspan="3">
                            <div class="error"><?php echo $folder_action_info; ?></div>
                        </td>
                    </tr>
                    <?php endif; ?>
                    </tbody>
                </table>
            </div>
            <br>
            <form action="<?php echo getUrl('message/folders'); ?>" method="POST">
                <input type="hidden" name="<?php echo $this->security->getTokenKey() ?>" value="<?php echo $this->security->getToken() ?>"/>
                <h2><img src="<?php echo getAssetLink('img/symbols/race'.$user->race.'small.gif'); ?>">create new folder...</h2>
                <div class="table-wrap">
                    <table cellpadding="2" cellspacing="2" border="0" width="100%">
                        <tbody><tr>
                            <td class="tdn">
                                <label>Name:</label>
                                <input class="left" type="text" name="name" value="" maxlength="50">
                                <div class="btn-left left ">
                                    <div class="btn-right">
                                        <input class="btn" type="submit" name="action" value="create folder">
                                    </div>
                                </div>
                                <br class="clearfloat">
                                <?php if($folder_create_info): ?>
                                    <div class="error"><?php echo $folder_create_info; ?></div>
                                <?php endif; ?>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </form>
        </div>
    </div>
    <div class="wrap-bottom-left">
        <div class="wrap-bottom-right">
            <div class="wrap-bottom-middle"></div>
        </div>
    </div>
</div>