<div id="msg">
    <div class="wrap-top-left clearfix">
        <div class="wrap-top-right clearfix">
            <div class="wrap-top-middle clearfix"></div>
        </div>
    </div>
    <div class="wrap-left clearfix">
        <div class="wrap-content wrap-right clearfix">
            <h2><img src="<?php echo getAssetLink('img/symbols/race'.$user->race.'small.gif'); ?>" alt="">messages</h2>
            <div class="clearfix">
                <?php echo $this->partial('partials/write_message'); ?>
                <div class="btn-left left">
                    <div class="btn-right">
                        <a href="#" class="btn" onclick="writeMessageSplash()">Write message</a>
                    </div>
                </div>
                <div class="btn-left right">
                    <div class="btn-right">
                        <a href="<?php echo getUrl('message/settings'); ?>" class="btn">Settings</a>
                    </div>
                </div>
                <div class="btn-left right">
                    <div class="btn-right">
                        <a href="<?php echo getUrl('message/folders'); ?>" class="btn">manage folders</a>
                    </div>
                </div>
                <br class="clearfloat">
                <div class="table-wrap">
                    <table width="100%" cellspacing="0" style="margin:0px;">
                        <tbody>
                        <?php foreach ($folders as $folder): ?>
                            <tr>
                                <td class="tdn" width="25" style="padding:1px 5px;">
                                    <img alt="new Message" src="<?php echo getAssetLink('img/symbols/mail_status'.($folder->newMsgCount > 0 ? 1 : 0).'.png'); ?>">
                                </td>
                                <td class="tdn" style="padding:1px 5px;">
                                    <a href="<?php echo getUrl('message/read?folder='.$folder->id); ?>"><?php echo e($folder->folder_name); ?></a> (<?php echo prettyNumber($folder->newMsgCount); ?> / <?php echo prettyNumber($folder->msgCount); ?> messages)
                                </td>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
                <div class="btn-left right">
                    <div class="btn-right">
                        <a href="<?php echo getUrl('message/block'); ?>" class="btn">blocked players</a>
                    </div>
                </div>
                <br class="clearfloat">
            </div>
        </div>
    </div>
    <div class="wrap-bottom-left">
        <div class="wrap-bottom-right">
            <div class="wrap-bottom-middle"></div>
        </div>
    </div>
</div>