<!-- box-model START -->
<div id="shop">
    <!-- box HEADER START -->
    <div class="wrap-top-left clearfix">
        <div class="wrap-top-right clearfix">
            <div class="wrap-top-middle clearfix"></div>
        </div>
    </div>
    <!-- box HEADER END -->
    <!-- box CONTENT START -->
    <div class="wrap-left clearfix">
        <div class="wrap-content wrap-right clearfix">
            <!-- CONTENT START -->
            <h2><img src="<?php echo getAssetLink('img/symbols/race1small.gif'); ?>" alt=""/>The merchant</h2>
            <div class="buildingDesc">
                <img class="npc-logo" src="<?php echo getAssetLink('img/city/npc/0_1.jpg'); ?>" align="left" />
                <h3>The merchant welcomes you <?php echo e($user->name); ?></h3>
                <p>Welcome to my modest shop. How can I serve you? I can offer you some good weapons and items that can improve your abilities! Please make your selection...</p>
                <p>You have <?php echo $user_item_available_slot; ?> free spaces in your inventory (and <?php echo $user_item_max_count; ?> inventory spaces in total).</p>
            </div>

            <div style="clear: both;width:100%;">
                <h2><img alt="" src="<?php echo getAssetLink('img/symbols/race'.$user->race.'small.gif'); ?>">Which goods are you interested in?</h2>
                <div id="shopMenu">
                    <a href="<?php echo getUrl('city/shop?model=weapons'); ?>">Weapons</a> |
                    <a href="<?php echo getUrl('city/shop?model=potions'); ?>">Potions</a> |
                    <a href="<?php echo getUrl('city/shop?model=helmets'); ?>">Helmets</a> |
                    <a href="<?php echo getUrl('city/shop?model=armour'); ?>">Armour</a> |
                    <a href="<?php echo getUrl('city/shop?model=jewellery'); ?>">Jewellery</a> |
                    <a href="<?php echo getUrl('city/shop?model=gloves'); ?>">Gloves</a> |
                    <a href="<?php echo getUrl('city/shop?model=boots'); ?>">Boots</a> |
                    <a href="<?php echo getUrl('city/shop?model=shields'); ?>">Shields</a>
                </div>
                <table cellpadding="2" cellspacing="2" border="0" width="100%">
                    <tr>
                        <td>
                            <form action ="<?php echo getUrl('city/shop'); ?>" method="get" name="filterForm">
                                <?php if($iModel != 'weapons') echo '<input type="hidden" name="model" value="'.$iModel.'">'; ?>
                                <div style="float:left;">
                                    Level: <input class="inputblack" type="text" name="lvlfrom" size="3" value="<?php echo $iLevelFrom; ?>"> - <input class="inputblack" type="text" name="lvlto" size="3" value="<?php echo $iLevelTo; ?>">
                                    <select name="premiumfilter">
                                        <option value="all" <?php if($iPFilter == 'all') echo 'selected="selected"'; ?>>Show all items</option>
                                        <option value="premium" <?php if($iPFilter == 'premium') echo 'selected="selected"'; ?>>Only show premium items</option>
                                        <option value="nonpremium" <?php if($iPFilter == 'nonpremium') echo 'selected="selected"'; ?>>Only show normal items</option>
                                    </select>
                                </div>
                                <div class="btn-left left"><div class="btn-right"><input type="submit" value="Filter"  class="btn"></div></div>
                            </form>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="3" class="tdh" align="center">Overview</td>
                    </tr>
                </table>
                <center>
                    <?php if($rPage > 2): ?>
                    <a href="<?php echo getLinkWithParams(getUrl('city/shop'), array('page' => 1, 'lvlto' => $iLevelTo, 'lvlfrom' => $iLevelFrom, 'premiumfilter' => $iPFilter, 'model' => $iModel)); ?>"><img src="<?php echo getAssetLink('img/symbols/arrow_left_end.gif'); ?>" border="0" title="to the start"></a>
                    &nbsp;&nbsp;
                    <?php endif; ?>
                    <?php if($rPage > 1): ?>
                    <a href="<?php echo getLinkWithParams(getUrl('city/shop'), array('page' => $rPage - 1, 'lvlto' => $iLevelTo, 'lvlfrom' => $iLevelFrom, 'premiumfilter' => $iPFilter, 'model' => $iModel)); ?>"><img src="<?php echo getAssetLink('img/symbols/single_arrow_left.gif'); ?>" border="0" title="-1"></a>
                    &nbsp;&nbsp;
                    <?php endif; ?>
                    <?php if($rPage > 2): ?>
                    <a href="<?php echo getLinkWithParams(getUrl('city/shop'), array('page' => $rPage - 2, 'lvlto' => $iLevelTo, 'lvlfrom' => $iLevelFrom, 'premiumfilter' => $iPFilter, 'model' => $iModel)); ?>"><?php echo $rPage - 2; ?></a>
                    &nbsp;&nbsp;
                    <?php endif; ?>
                    <?php if($rPage > 1): ?>
                    <a href="<?php echo getLinkWithParams(getUrl('city/shop'), array('page' => $rPage - 1, 'lvlto' => $iLevelTo, 'lvlfrom' => $iLevelFrom, 'premiumfilter' => $iPFilter, 'model' => $iModel)); ?>"><?php echo $rPage - 1; ?></a>
                    &nbsp;&nbsp;
                    <?php endif; ?>
                    <b><?php echo $rPage; ?></b>
                    &nbsp;&nbsp;
                    <?php if($rPage < $total_pages): ?>
                    <a href="<?php echo getLinkWithParams(getUrl('city/shop'), array('page' => $rPage + 1, 'lvlto' => $iLevelTo, 'lvlfrom' => $iLevelFrom, 'premiumfilter' => $iPFilter, 'model' => $iModel)); ?>"><?php echo $rPage + 1; ?></a>
                    &nbsp;&nbsp;
                    <?php endif; ?>
                    <?php if($rPage < $total_pages - 1): ?>
                    <a href="<?php echo getLinkWithParams(getUrl('city/shop'), array('page' => $rPage + 2, 'lvlto' => $iLevelTo, 'lvlfrom' => $iLevelFrom, 'premiumfilter' => $iPFilter, 'model' => $iModel)); ?>"><?php echo $rPage + 2; ?></a>
                    &nbsp;&nbsp;
                    <?php endif; ?>
                    <?php if($rPage < $total_pages): ?>
                    <a href="<?php echo getLinkWithParams(getUrl('city/shop'), array('page' => $rPage + 1, 'lvlto' => $iLevelTo, 'lvlfrom' => $iLevelFrom, 'premiumfilter' => $iPFilter, 'model' => $iModel)); ?>"><img src="<?php echo getAssetLink('img/symbols/single_arrow_right.gif'); ?>" border="0" title="+1"></a>
                    &nbsp;&nbsp;
                    <?php endif; ?>
                    <?php if($rPage < $total_pages - 1): ?>
                    <a href="<?php echo getLinkWithParams(getUrl('city/shop'), array('page' => $total_pages, 'lvlto' => $iLevelTo, 'lvlfrom' => $iLevelFrom, 'premiumfilter' => $iPFilter, 'model' => $iModel)); ?>"><img src="<?php echo getAssetLink('img/symbols/arrow_right_end.gif'); ?>" border="0" title="to the end"></a>
                    <?php endif; ?>
                </center>
                <br>
                <table id="shopOverview" cellpadding="2" cellspacing="2" border="0" width="100%" style="margin-top:-2px;padding-top:0px;">
                    <?php foreach($items as $i): ?>
                        <tr>
                            <td class='no-bg' style="text-align:center;">
                                <div style="position:relative;width:300px;">
                                    <img src="<?php echo getAssetLink('img/items/'.$i->model.'/'.$i->id.'.jpg') ?>" <?php if($i->scost > 0) echo 'style="border: 1px solid #6f86a9;"'; ?> alt="<?php echo $i->name ?>">
                                    <div style="position:absolute;right:90px;top:15px;z-index:9999">
                                    </div>
                                </div>
                            </td>
                            <td class='tdn'>
                                <?php printItemDetails($i, true); ?><br>
                            </td>
                            <td class="tdn" style="width:150px;" align="center">---</td>
                        </tr>
                    <?php endforeach; ?>
                </table>
                <center>
                    <?php if($rPage > 2): ?>
                        <a href="<?php echo getLinkWithParams(getUrl('city/shop'), array('page' => 1, 'lvlto' => $iLevelTo, 'lvlfrom' => $iLevelFrom, 'premiumfilter' => $iPFilter, 'model' => $iModel)); ?>"><img src="<?php echo getAssetLink('img/symbols/arrow_left_end.gif'); ?>" border="0" title="to the start"></a>
                        &nbsp;&nbsp;
                    <?php endif; ?>
                    <?php if($rPage > 1): ?>
                        <a href="<?php echo getLinkWithParams(getUrl('city/shop'), array('page' => $rPage - 1, 'lvlto' => $iLevelTo, 'lvlfrom' => $iLevelFrom, 'premiumfilter' => $iPFilter, 'model' => $iModel)); ?>"><img src="<?php echo getAssetLink('img/symbols/single_arrow_left.gif'); ?>" border="0" title="-1"></a>
                        &nbsp;&nbsp;
                    <?php endif; ?>
                    <?php if($rPage > 2): ?>
                        <a href="<?php echo getLinkWithParams(getUrl('city/shop'), array('page' => $rPage - 2, 'lvlto' => $iLevelTo, 'lvlfrom' => $iLevelFrom, 'premiumfilter' => $iPFilter, 'model' => $iModel)); ?>"><?php echo $rPage - 2; ?></a>
                        &nbsp;&nbsp;
                    <?php endif; ?>
                    <?php if($rPage > 1): ?>
                        <a href="<?php echo getLinkWithParams(getUrl('city/shop'), array('page' => $rPage - 1, 'lvlto' => $iLevelTo, 'lvlfrom' => $iLevelFrom, 'premiumfilter' => $iPFilter, 'model' => $iModel)); ?>"><?php echo $rPage - 1; ?></a>
                        &nbsp;&nbsp;
                    <?php endif; ?>
                    <b><?php echo $rPage; ?></b>
                    &nbsp;&nbsp;
                    <?php if($rPage < $total_pages): ?>
                        <a href="<?php echo getLinkWithParams(getUrl('city/shop'), array('page' => $rPage + 1, 'lvlto' => $iLevelTo, 'lvlfrom' => $iLevelFrom, 'premiumfilter' => $iPFilter, 'model' => $iModel)); ?>"><?php echo $rPage + 1; ?></a>
                        &nbsp;&nbsp;
                    <?php endif; ?>
                    <?php if($rPage < $total_pages - 1): ?>
                        <a href="<?php echo getLinkWithParams(getUrl('city/shop'), array('page' => $rPage + 2, 'lvlto' => $iLevelTo, 'lvlfrom' => $iLevelFrom, 'premiumfilter' => $iPFilter, 'model' => $iModel)); ?>"><?php echo $rPage + 2; ?></a>
                        &nbsp;&nbsp;
                    <?php endif; ?>
                    <?php if($rPage < $total_pages): ?>
                        <a href="<?php echo getLinkWithParams(getUrl('city/shop'), array('page' => $rPage + 1, 'lvlto' => $iLevelTo, 'lvlfrom' => $iLevelFrom, 'premiumfilter' => $iPFilter, 'model' => $iModel)); ?>"><img src="<?php echo getAssetLink('img/symbols/single_arrow_right.gif'); ?>" border="0" title="+1"></a>
                        &nbsp;&nbsp;
                    <?php endif; ?>
                    <?php if($rPage < $total_pages - 1): ?>
                        <a href="<?php echo getLinkWithParams(getUrl('city/shop'), array('page' => $total_pages, 'lvlto' => $iLevelTo, 'lvlfrom' => $iLevelFrom, 'premiumfilter' => $iPFilter, 'model' => $iModel)); ?>"><img src="<?php echo getAssetLink('img/symbols/arrow_right_end.gif'); ?>" border="0" title="to the end"></a>
                    <?php endif; ?>
                </center>
            </div>
        </div>
    </div>
    <div class="wrap-bottom-left">
        <div class="wrap-bottom-right">
            <div class="wrap-bottom-middle"></div>
        </div>
    </div>
</div>