<h1><?php echo \Bitefight\Library\Translate::_('hunt_header', ['user' => e($user->name)]); ?></h1>
<p><?php echo \Bitefight\Library\Translate::_('hunt_header_line'); ?></p>
<br>
<div>
    <div id="wolfHunting">
        <div class="wrap-top-left">
            <div class="wrap-top-right">
                <div class="wrap-top-middle"></div>
            </div>
        </div>
        <div class="wrap-left">
            <div class="wrap-content wrap-right">
                <form action="<?php echo getUrl('hunt/race/search'); ?>" method="POST">
                    <input type="hidden" name="<?php echo $this->security->getTokenKey() ?>" value="<?php echo $this->security->getToken() ?>"/>
                    <h2>
                        <img src="<?php echo getAssetLink('img/symbols/race'.$user->race.'small.gif'); ?>" alt="">
                        Werewolf Hunt  ( 1 <img src="<?php echo getAssetLink('img/symbols/ap.gif'); ?>" title="Action point" style="float: none; vertical-align: middle; margin: 0;"> )
                    </h2>
                    <img src="<?php echo getAssetLink('img/hunt/new_race1hunt2.jpg'); ?>" title="Werewolf Hunt" width="340" height="125"><br/><br/>
                    <p class="tdnp" style="text-align: center;">Roam the streets for <?php if($user->race == 1) echo 'werewolves'; else echo 'vampires'; ?></p>
                    <div class="tdi">
                        search options: <br>
                        <select name="enemy_type" size="1">
                            <option value="1">normal</option>
                            <option value="2">only search for stronger or equally strong rivals</option>
                        </select><br>
                        <!--<input id="totemsearch" type="checkbox" name="totemsearch" value="totemsearch" checked="checked" onchange="docheckbox('totemsearch')"> Search for lost souls too (include inactive users in the search).<br>-->
                        <div class="btn-left center">
                            <div class="btn-right">
                                <input type="submit" class="btn" name="optionsearch" value="Go!">
                            </div>
                        </div>
                    </div>
                    <!--
                    <br>
                    <div class="tdi">
                        search options:<br>
                        Battle value from <input class="input" type="text" name="lvlvon" size="5" value="2536" maxlength="10">
                        to <input class="input" type="text" name="lvlbis" size="5" value="3961" maxlength="10">
                        <input class="input" type="hidden" name="ef38240d8dbf1af58bb4f14417ae9aa2" value="77625"><br>
                        <input id="totemsearch" type="checkbox" name="totemsearch" value="totemsearch" checked="checked" onchange="docheckbox('totemsearch')"> Search for lost souls too (include inactive users in the search).<br>
                        <div class="btn-left center">
                            <div class="btn-right">
                                <input type="submit" class="btn" name="levelsearch" value="Go!">
                            </div>
                        </div>
                    </div>
                    -->
                    <?php if(isset($race_search_error_top)): ?>
                        <div class="tdi">
                            <strong style="font-size:1.8em; color:#fff"><?php echo $race_search_error_top; ?></strong>
                        </div>
                    <?php endif; ?>
                </form>
                <br>

                <h2><img src="<?php echo getAssetLink('img/symbols/race'.$user->race.'small.gif'); ?>" alt="">Look for a particular werewolf</h2>
                <form action="<?php echo getUrl('hunt/race/search/exact'); ?>" method="POST">
                    <input type="hidden" name="<?php echo $this->security->getTokenKey() ?>" value="<?php echo $this->security->getToken() ?>"/>
                    <div class="tdi">Name:<br>
                        <input class="input" type="text" name="name" size="30" value="" maxlength="30">
                        <div class="btn-left center">
                            <div class="btn-right">
                                <input type="submit" class="btn" name="namesearch" value="Go!">
                            </div>
                        </div>
                    </div>
                    <?php if(isset($race_search_error)): ?>
                    <div class="tdi">
                        <strong style="font-size:1.8em; color:#fff"><?php echo $race_search_error; ?></strong>
                    </div>
                    <?php endif; ?>
                </form>
            </div>
        </div>
        <div class="wrap-bottom-left">
            <div class="wrap-bottom-right">
                <div class="wrap-bottom-middle"></div>
            </div>
        </div>
    </div>
    <div id="humanHunting">
        <div class="wrap-top-left">
            <div class="wrap-top-right">
                <div class="wrap-top-middle"></div>
            </div>
        </div>
        <div class="wrap-left clearfix">
            <div id="humanhunt" class="wrap-content wrap-right">
                <h2><img src="<?php echo getAssetLink('img/symbols/race'.$user->race.'small.gif'); ?>" alt=""/><?php echo \Bitefight\Library\Translate::_('human_hunt_header'); ?></h2>
                <div <?php if($user->ap_now > 1 && !$onGraveyardWork): ?>onclick="doHunt(1)"<?php endif; ?> class="mjs" style="position:relative; height:121px; cursor:pointer;">
                    <img src="<?php echo getAssetLink('img/hunt/city1.jpg'); ?>" alt="<?php echo \Bitefight\Library\Translate::_('human_hunt_hunt_1'); ?>"/>
                    <div id="mjInfo_1" style="text-align:left;">
                        <table class='noBackground' border="0" style="display:block;">
                            <tr>
                                <td nowrap style='font-size: 1.1em;'><b><?php echo \Bitefight\Library\Translate::_('human_hunt_hunt_1'); ?></b> ( 1 <img src="<?php echo getAssetLink('img/symbols/ap.gif'); ?>" alt="<?php echo \Bitefight\Library\Translate::_('action_points'); ?>" /> )</td>
                            </tr>
                        </table>
                        <table class='noBackground' border="0" style="display:none;">
                            <tr>
                                <td nowrap style='font-size: 1.1em;'><b><?php echo \Bitefight\Library\Translate::_('human_hunt_hunt_1'); ?></b> ( 1 <img src="<?php echo getAssetLink('img/symbols/ap.gif'); ?>" alt="<?php echo \Bitefight\Library\Translate::_('action_points'); ?>" /> )</td>
                            </tr>
                            <tr>
                                <td nowrap><?php echo \Bitefight\Library\Translate::_('humen_hunt_chance_of_success'); ?>: <?php echo $hunt1Chance; ?>%</td>
                            </tr>
                            <tr>
                                <td nowrap><?php echo prettyNumber($hunt1Reward); ?> <img src="<?php echo getAssetLink('img/symbols/res2.gif'); ?>" alt="<?php echo \Bitefight\Library\Translate::_('gold'); ?>" /> + <?php echo $hunt1Exp; ?> <?php echo \Bitefight\Library\Translate::_('experience'); ?></td>
                            </tr>
                        </table>
                    </div>
                </div>
                <div class="btn-left center">
                    <div class="btn-right">
                        <button <?php if($user->ap_now > 1 && !$onGraveyardWork): ?>onclick="doHunt(1)"<?php endif; ?> class="btn"><?php echo \Bitefight\Library\Translate::_('human_hunt_hunt_1'); ?></button>
                    </div>
                </div>
                <br/>
                <div <?php if($user->ap_now > 1 && !$onGraveyardWork): ?>onclick="doHunt(2)"<?php endif; ?> class="mjs" style="position:relative; height:121px; cursor:pointer;">
                    <img src="<?php echo getAssetLink('img/hunt/city2.jpg'); ?>" alt="<?php echo \Bitefight\Library\Translate::_('human_hunt_hunt_2'); ?>"/>
                    <div id="mjInfo_2" style="text-align:left;">
                        <table class='noBackground' border="0" style="display:block;">
                            <tr>
                                <td nowrap style='font-size: 1.1em;'><b><?php echo \Bitefight\Library\Translate::_('human_hunt_hunt_2'); ?></b> ( 1 <img src="<?php echo getAssetLink('img/symbols/ap.gif'); ?>" alt="<?php echo \Bitefight\Library\Translate::_('action_points'); ?>" /> )</td>
                            </tr>
                        </table>
                        <table class='noBackground' border="0" style="display:none;">
                            <tr>
                                <td nowrap style='font-size: 1.1em;'><b><?php echo \Bitefight\Library\Translate::_('human_hunt_hunt_2'); ?></b> ( 1 <img src="<?php echo getAssetLink('img/symbols/ap.gif'); ?>" alt="<?php echo \Bitefight\Library\Translate::_('action_points'); ?>" /> )</td>
                            </tr>
                            <tr>
                                <td nowrap><?php echo \Bitefight\Library\Translate::_('humen_hunt_chance_of_success'); ?>: <?php echo $hunt2Chance; ?>%</td>
                            </tr>
                            <tr>
                                <td nowrap><?php echo prettyNumber($hunt2Reward); ?> <img src="<?php echo getAssetLink('img/symbols/res2.gif'); ?>" alt="<?php echo \Bitefight\Library\Translate::_('gold'); ?>" /> + <?php echo $hunt2Exp; ?> <?php echo \Bitefight\Library\Translate::_('experience'); ?></td>
                            </tr>
                        </table>
                    </div>
                </div>
                <div class="btn-left center">
                    <div class="btn-right">
                        <button <?php if($user->ap_now > 1 && !$onGraveyardWork): ?>onclick="doHunt(2)"<?php endif; ?> class="btn"><?php echo \Bitefight\Library\Translate::_('human_hunt_hunt_2'); ?></button>
                    </div>
                </div>
                <br/>
                <div <?php if($user->ap_now > 2 && !$onGraveyardWork): ?>onclick="doHunt(3)"<?php endif; ?> class="mjs" style="position:relative; height:121px; cursor:pointer;">
                    <img src="<?php echo getAssetLink('img/hunt/city3.jpg'); ?>" alt="<?php echo \Bitefight\Library\Translate::_('human_hunt_hunt_3'); ?>"/>
                    <div id="mjInfo_3" style="text-align:left;">
                        <table class='noBackground' border="0" style="display:block;">
                            <tr>
                                <td nowrap style='font-size: 1.1em;'><b><?php echo \Bitefight\Library\Translate::_('human_hunt_hunt_3'); ?></b> ( 2 <img src="<?php echo getAssetLink('img/symbols/ap.gif'); ?>" alt="<?php echo \Bitefight\Library\Translate::_('action_points'); ?>" /> )</td>
                            </tr>
                        </table>
                        <table class='noBackground' border="0" style="display:none;">
                            <tr>
                                <td nowrap style='font-size: 1.1em;'><b><?php echo \Bitefight\Library\Translate::_('human_hunt_hunt_3'); ?></b> ( 2 <img src="<?php echo getAssetLink('img/symbols/ap.gif'); ?>" alt="<?php echo \Bitefight\Library\Translate::_('action_points'); ?>" /> )</td>
                            </tr>
                            <tr>
                                <td nowrap><?php echo \Bitefight\Library\Translate::_('humen_hunt_chance_of_success'); ?>: <?php echo $hunt3Chance; ?>%</td>
                            </tr>
                            <tr>
                                <td nowrap><?php echo prettyNumber($hunt3Reward); ?> <img src="<?php echo getAssetLink('img/symbols/res2.gif'); ?>" alt="<?php echo \Bitefight\Library\Translate::_('gold'); ?>" /> + <?php echo $hunt3Exp; ?> <?php echo \Bitefight\Library\Translate::_('experience'); ?></td>
                            </tr>
                        </table>
                    </div>
                </div>
                <div class="btn-left center">
                    <div class="btn-right">
                        <button <?php if($user->ap_now > 2 && !$onGraveyardWork): ?>onclick="doHunt(3)"<?php endif; ?> class="btn"><?php echo \Bitefight\Library\Translate::_('human_hunt_hunt_3'); ?></button>
                    </div>
                </div>
                <br/>
                <div <?php if($user->ap_now > 2 && !$onGraveyardWork): ?>onclick="doHunt(4)"<?php endif; ?> class="mjs" style="position:relative; height:121px; cursor:pointer;">
                    <img src="<?php echo getAssetLink('img/hunt/city4.jpg'); ?>" alt="<?php echo \Bitefight\Library\Translate::_('human_hunt_hunt_4'); ?>"/>
                    <div id="mjInfo_4" style="text-align:left;">
                        <table class='noBackground' border="0" style="display:block;">
                            <tr>
                                <td nowrap style='font-size: 1.1em;'><b><?php echo \Bitefight\Library\Translate::_('human_hunt_hunt_4'); ?></b> ( 2 <img src="<?php echo getAssetLink('img/symbols/ap.gif'); ?>" alt="<?php echo \Bitefight\Library\Translate::_('action_points'); ?>" /> )</td>
                            </tr>
                        </table>
                        <table class='noBackground' border="0" style="display:none;">
                            <tr>
                                <td nowrap style='font-size: 1.1em;'><b><?php echo \Bitefight\Library\Translate::_('human_hunt_hunt_4'); ?></b> ( 2 <img src="<?php echo getAssetLink('img/symbols/ap.gif'); ?>" alt="<?php echo \Bitefight\Library\Translate::_('action_points'); ?>" /> )</td>
                            </tr>
                            <tr>
                                <td nowrap><?php echo \Bitefight\Library\Translate::_('humen_hunt_chance_of_success'); ?>: <?php echo $hunt4Chance; ?>%</td>
                            </tr>
                            <tr>
                                <td nowrap><?php echo prettyNumber($hunt4Reward); ?> <img src="<?php echo getAssetLink('img/symbols/res2.gif'); ?>" alt="<?php echo \Bitefight\Library\Translate::_('gold'); ?>" /> + <?php echo $hunt4Exp; ?> <?php echo \Bitefight\Library\Translate::_('experience'); ?></td>
                            </tr>
                        </table>
                    </div>
                </div>
                <div class="btn-left center">
                    <div class="btn-right">
                        <button <?php if($user->ap_now > 2 && !$onGraveyardWork): ?>onclick="doHunt(4)"<?php endif; ?> class="btn"><?php echo \Bitefight\Library\Translate::_('human_hunt_hunt_4'); ?></button>
                    </div>
                </div>
                <br/>
                <div <?php if($user->ap_now > 3 && !$onGraveyardWork): ?>onclick="doHunt(5)"<?php endif; ?> class="mjs" style="position:relative; height:121px; cursor:pointer;">
                    <img src="<?php echo getAssetLink('img/hunt/city5.jpg'); ?>" alt="<?php echo \Bitefight\Library\Translate::_('human_hunt_hunt_5'); ?>"/>
                    <div id="mjInfo_5" style="text-align:left;">
                        <table class='noBackground' border="0" style="display:block;">
                            <tr>
                                <td nowrap style='font-size: 1.1em;'><b><?php echo \Bitefight\Library\Translate::_('human_hunt_hunt_5'); ?></b> ( 3 <img src="<?php echo getAssetLink('img/symbols/ap.gif'); ?>" alt="<?php echo \Bitefight\Library\Translate::_('action_points'); ?>" /> )</td>
                            </tr>
                        </table>
                        <table class='noBackground' border="0" style="display:none;">
                            <tr>
                                <td nowrap style='font-size: 1.1em;'><b><?php echo \Bitefight\Library\Translate::_('human_hunt_hunt_5'); ?></b> ( 3 <img src="<?php echo getAssetLink('img/symbols/ap.gif'); ?>" alt="<?php echo \Bitefight\Library\Translate::_('action_points'); ?>" /> )</td>
                            </tr>
                            <tr>
                                <td nowrap><?php echo \Bitefight\Library\Translate::_('humen_hunt_chance_of_success'); ?>: <?php echo $hunt5Chance; ?>%</td>
                            </tr>
                            <tr>
                                <td nowrap><?php echo prettyNumber($hunt5Reward); ?> <img src="<?php echo getAssetLink('img/symbols/res2.gif'); ?>" alt="<?php echo \Bitefight\Library\Translate::_('gold'); ?>" /> + <?php echo $hunt5Exp; ?> <?php echo \Bitefight\Library\Translate::_('experience'); ?></td>
                            </tr>
                        </table>
                    </div>
                </div>
                <div class="btn-left center">
                    <div class="btn-right">
                        <button <?php if($user->ap_now > 3 && !$onGraveyardWork): ?>onclick="doHunt(5)"<?php endif; ?> class="btn"><?php echo \Bitefight\Library\Translate::_('human_hunt_hunt_5'); ?></button>
                    </div>
                </div>
                <script type="text/javascript">
                    $('.mjs').hover(
                        function() {
                            $(this).children('div').animate({height: '90'});
                            $(this).children('div').children('table:first-child').hide();
                            $(this).children('div').children('table:last-child').show();
                        },
                        function() {
                            $(this).children('div').animate({height: '35'});
                            $(this).children('div').children('table:first-child').show();
                            $(this).children('div').children('table:last-child').hide();
                        }
                    );
                </script>
            </div>
        </div>
        <div class="wrap-bottom-left">
            <div class="wrap-bottom-right">
                <div class="wrap-bottom-middle"></div>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        function doHunt(type)
        {
            var url = "<?php echo getUrl('hunt/human'); ?>/"+type+"?_tkey=<?php echo $this->security->getTokenKey() ?>&_token=<?php echo $this->security->getToken() ?>";
            window.location.replace(url);
        }

        function docheckbox(id)
        {
            var $totemSearch = $('#totemsearch'),
                $onlyTotemSearch = $('#onlytotemsearch');

            if ($totemSearch.is(':checked') && id == 'totemsearch')
            {
                $onlyTotemSearch.removeAttr('checked');
            }
            if ($onlyTotemSearch.is(':checked') && id == 'onlytotemsearch')
            {
                $totemSearch.removeAttr('checked');
            }
        }
    </script>
</div>