<div id="splashInfo">
    <div class="wrap-top-left clearfix">
        <div class="wrap-top-right clearfix">
            <div class="wrap-top-middle clearfix"></div>
        </div>
    </div>
    <div class="wrap-left clearfix">
        <div class="wrap-content wrap-right clearfix">
            <div id="speedserverbig">Speed server x4</div>
            <img src="<?php echo getAssetLink('img/layout/home_splash.jpg') ?>" width="710" height="381" border="0" alt="Bitefight" usemap="#home-splash-map"/>
            <map name="home-splash-map" id="home-splash-map">
                <area  alt="" title="" href="werewolf" shape="poly" coords="708,7,641,9,608,21,582,40,559,69,551,95,536,136,526,162,536,187,538,209,543,226,552,246,566,269,573,306,589,338,614,357,641,374,708,376" style="outline:none;" />
                <area  alt="" title="" href="vampire" shape="poly" coords="5,36,23,46,52,63,84,76,97,105,120,120,134,142,141,167,152,179,164,203,178,226,190,242,181,265,150,287,3,374" style="outline:none;" />
            </map>
            <p id="splashText">
                The struggle between Vampires and <br>
                Werewolves has been rampaging for centuries.<br>
                It`s your destiny to decide this battle`s outcome!
            </p>
            <a href="<?php echo getUrl('news'); ?>" id="regBtn" target="_top">Play now for free!</a> <br class="clearfloat">
            <div id="features" class="clearfix">
                <p>Roam the city<br>looking for new victims.<img src="<?php echo getAssetLink('img/home_thumb01.jpg'); ?>" width="170" height="86"/></p>
                <p>Equip yourself to defeat <br> your enemies.<img src="<?php echo getAssetLink('img/home_thumb02.jpg'); ?>" width="170" height="86"/></p>
                <p>Build an immense stronghold<br> with your friends.<img src="<?php echo getAssetLink('img/home_thumb03.jpg'); ?>" width="170" height="86"/></p>
            </div>
            <br class="clearfloat"/>
        </div>
    </div>
    <div class="wrap-bottom-left">
        <div class="wrap-bottom-right">
            <div class="wrap-bottom-middle"></div>
        </div>
    </div>
</div>