<div id="login">
    <div class="wrap-top-left clearfix">
        <div class="wrap-top-right clearfix">
            <div class="wrap-top-middle clearfix"></div>
        </div>
    </div>
    <div class="wrap-left clearfix">
        <div class="wrap-content wrap-right clearfix">
            <h2>Please enter your name and password to login</h2>
            <div class="table-wrap">
                <table width="100%">
                    <tr>
                        <td><img src="<?php echo getAssetLink('img/symbols/race1.gif'); ?>" alt="Vampire" ></td>
                        <td>
                            <form id="loginForm" name="loginForm" action="<?php echo getUrl('login'); ?>"  method="POST">
                                <input type="hidden" name="<?php echo $this->security->getTokenKey() ?>" value="<?php echo $this->security->getToken() ?>"/>
                                <table cellpadding="2" cellspacing="2" border="0" width="100%">
                                    <tr>
                                        <td>Name:</td>
                                        <td><input class="input" type="text" name="user" size="30" MAXLENGTH="30"></td>
                                    </tr>
                                    <tr>
                                        <td>Password:</td>
                                        <td><input class="input" type="password" name="pass" size="30" MAXLENGTH="30">
                                            <br />
                                            <!--<a href="/user/lostpw" target="_top" id="pwlostLink">Have you forgotten your password?</a>-->
                                        </td>
                                    </tr>
                                    <tr>
                                        <td></td>
                                        <td><input type="submit" class="btn-small" value="Login"></td>
                                </table>
                            </form>
                        </td>
                        <td><img src="<?php echo getAssetLink('img/symbols/race2.gif'); ?>" alt="Werewolf" ></td>
                    </tr>
                </table>
                <?php if($error) echo '<div class="error">The entered username or password is wrong.</div>'; ?>
                <br class="clearfloat" />
            </div>
        </div>
    </div>
    <div class="wrap-bottom-left">
        <div class="wrap-bottom-right">
            <div class="wrap-bottom-middle"></div>
        </div>
    </div>
</div>