<script type="text/javascript">
    $('#header').find('h1').text('Lost Password');
</script>
<div id="login">
    <div class="wrap-top-left clearfix">
        <div class="wrap-top-right clearfix">
            <div class="wrap-top-middle clearfix"></div>
        </div>
    </div>
    <div class="wrap-left clearfix">
        <div class="wrap-content wrap-right clearfix">
            <h2>Please enter your name and e-mail-address</h2>
            <form action="<?php echo getUrl('user/lostpw'); ?>" method="POST">
                <input type="hidden" name="<?php echo $this->security->getTokenKey() ?>" value="<?php echo $this->security->getToken() ?>"/>
                <?php echo $this->flashSession->output(); ?>
                <div class="table-wrap">
                    <table cellpadding="0" cellspacing="0" border="0" width="100%">
                        <tbody><tr>
                            <td align="center" valign="top"><img src="<?php echo getAssetLink('img/symbols/race1.gif'); ?>" alt="Vampire"></td>
                            <td valign="top">
                                <table cellpadding="2" cellspacing="2" border="0" width="100%">
                                    <tbody><tr>
                                        <td>Name</td>
                                        <td><input class="input" type="text" name="name" size="30" maxlength="30"></td>
                                    </tr>
                                    <tr>
                                        <td>E-MAIL</td>
                                        <td><input class="input" type="text" name="email" size="30" maxlength="130"></td>
                                    </tr>
                                    <tr>
                                        <td></td>
                                        <td><input type="submit" class="btn-small" value="send"></td>
                                    </tr>
                                    </tbody></table>
                            </td>
                            <td align="center" valign="top"><img src="<?php echo getAssetLink('img/symbols/race2.gif'); ?>" alt="Werewolf"></td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </form>
        </div>
    </div>
    <div class="wrap-bottom-left">
        <div class="wrap-bottom-right">
            <div class="wrap-bottom-middle"></div>
        </div>
    </div>
</div>