<div id="news">
    <div class="wrap-top-left clearfix">
        <div class="wrap-top-right clearfix">
            <div class="wrap-top-middle clearfix"></div>
        </div>
    </div>
    <div class="wrap-left clearfix">
        <div class="wrap-content wrap-right clearfix">
            <h2><img src="<?php echo getAssetLink('img/symbols/race1small.gif'); ?>" alt=""><?php echo \Bitefight\Library\Translate::_('menu_news'); ?></h2>
            <div class="table-wrap">
                <table cellpadding="2" cellspacing="10" border="0" width="100%">
                    <tbody>
                    <?php foreach($news as $new): ?>
                        <tr id="short_news_<?php echo $new->id; ?>" class="news_<?php echo $new->id; ?> ">
                            <td width="100%" style="cursor: pointer;">
                                <b style="font-size:1.2em;"><?php echo $new->title; ?></b>
                                <span style="float: right;">
                                    <b><?php echo $new->date; ?></b>&nbsp;&nbsp;<img border="0" src="<?php echo getAssetLink('img/symbols/expand.png'); ?>">
                                </span>
                            </td>
                        </tr>
                        <tr id="full_news_<?php echo $new->id; ?>" class="news_<?php echo $new->id; ?> hidden">
                            <td width="100%" style="cursor: pointer;">
                                <span>
                                    <b style="font-size:1.2em;"><?php echo $new->title; ?></b>
                                    <span style="float: right;">
                                        <b><?php echo $new->date; ?></b>&nbsp;&nbsp;<img border="0" src="<?php echo getAssetLink('img/symbols/collapse.png'); ?>">
                                    </span>
                                </span>
                                <br>
                                <hr>
                                <?php echo $new->message; ?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="wrap-bottom-left">
        <div class="wrap-bottom-right">
            <div class="wrap-bottom-middle"></div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $('[class^="news_"]').click(function () {
        $('.' + $(this).attr('class')).toggleClass('hidden');
    });
</script>