<?php if($id == 0): ?>

    <script language="JavaScript">
        p1 = new Image();
        p1.src = "<?php echo getAssetLink('img/symbols/race1loginen.gif'); ?>";
        p1x = new Image();
        p1x.src = "<?php echo getAssetLink('img/symbols/race1loginhoveren.gif'); ?>";
        p2 = new Image();
        p2.src = "<?php echo getAssetLink('img/symbols/race2loginen.gif'); ?>";
        p2x = new Image();
        p2x.src = "<?php echo getAssetLink('img/symbols/race2loginhoveren.gif'); ?>";
    </script>
    <div id="chooseRace">
        <div class="wrap-top-left clearfix">
            <div class="wrap-top-right clearfix">
                <div class="wrap-top-middle clearfix"></div>
            </div>
        </div>
        <div class="wrap-left clearfix">
            <div class="wrap-content wrap-right clearfix">
                <div class="table-wrap">
                    <table cellpadding="0" cellspacing="0" border="0" width="100%">
                        <tr>
                            <td width="40%" align="left">
                                <a href="<?php echo getUrl('register/1'); ?>" onfocus="if(this.blur)this.blur()"
                                   target="_top" onmouseover="document.pic1.src = p1x.src"
                                   onmouseout="document.pic1.src = p1.src">
                                    <img src="<?php echo getAssetLink('img/symbols/race1loginen.gif'); ?>" alt="<?php echo \Bitefight\Library\Translate::_('vampire'); ?>"
                                         name="pic1" border="0">
                                </a>
                            </td>
                            <td width="20%"><?php echo \Bitefight\Library\Translate::_('home_register_select_race'); ?></td>
                            <td width="40%" align="right">
                                <a href="<?php echo getUrl('register/2'); ?>" onfocus="if(this.blur)this.blur()"
                                   target="_top" onmouseover="document.pic2.src = p2x.src"
                                   onmouseout="document.pic2.src = p2.src">
                                    <img src="<?php echo getAssetLink('img/symbols/race2loginen.gif'); ?>" alt="<?php echo \Bitefight\Library\Translate::_('werewolf'); ?>"
                                         name="pic2" border="0">
                                </a>
                            </td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="wrap-bottom-left">
            <div class="wrap-bottom-right">
                <div class="wrap-bottom-middle"></div>
            </div>
        </div>
    </div>

<?php else: ?>

    <div id="register">
        <div class="wrap-top-left clearfix">
            <div class="wrap-top-right clearfix">
                <div class="wrap-top-middle clearfix"></div>
            </div>
        </div>
        <div class="wrap-left clearfix">
            <div class="wrap-content wrap-right clearfix">
                <h2><img src="<?php echo getAssetLink('img/symbols/race'.$id.'small.gif'); ?>" alt=""/><?php echo \Bitefight\Library\Translate::_('menu_register'); ?></h2>
                <div class="table-wrap">
                    <script type="text/javascript">
                        $(function () {
                            var timer;
                            $("#name").keyup(function () {
                                if(timer) {
                                    clearTimeout(timer);
                                    timer = null
                                }
                                timer = setTimeout(function() {
                                    ajaxCheck("name");
                                }, 500)
                            });

                            $("#email").keyup(function () {
                                if(timer) {
                                    clearTimeout(timer);
                                    timer = null
                                }
                                timer = setTimeout(function() {
                                    ajaxCheck("email");
                                }, 500)
                            });

                            $("#agb").change(function () {
                                if ($("#agb").is(':checked')){
                                    $("#agb_status").html('<img src="<?php echo getAssetLink('img/symbols/tick.gif'); ?>"/>');
                                } else {
                                    $("#agb_status").html('<img src="<?php echo getAssetLink('img/symbols/cross.gif'); ?>"/>');
                                }
                            });
                        });

                        function ajaxCheck(name){
                            $.getJSON("/register/ajaxcheck",
                                $("#"+name).serialize(),
                                function(data){
                                    if (data.status){
                                        $("#"+name+"_status").html('<img src="<?php echo getAssetLink('img/symbols/tick.gif'); ?>" style="vertical-align:middle;"/>');
                                    } else {
                                        $("#"+name+"_status").html('<img src="<?php echo getAssetLink('img/symbols/cross.gif'); ?>" style="vertical-align:middle;"/><b style="color:yellow" class="fontsmall">'+data.messages+'</b>');
                                    }
                                })
                        }
                    </script>
                    <h3><?php echo \Bitefight\Library\Translate::_('home_register_header'); ?></h3>
                    <p><?php echo \Bitefight\Library\Translate::_('home_register_unnecessary_info'); ?></p>
                    <?php echo $this->flashSession->output(); ?>
                    <br>
                    <form id="registerForm" name="registerForm" action="<?php echo getUrl('register/'.$id); ?>"  method="POST">
                        <input type="hidden" name="<?php echo $this->security->getTokenKey() ?>" value="<?php echo $this->security->getToken() ?>"/>
                        <table cellpadding="0" cellspacing="0" border="0">
                            <tr>
                                <td align="center" valign="top">
                                    <table cellpadding="2" cellspacing="2" border="0" width="100%">
                                        <tr>
                                            <td><?php echo \Bitefight\Library\Translate::_('home_register_name_label'); ?>:</td>
                                            <td>
                                                <input class="input" type="text" id="name" name="name" size="30" MAXLENGTH="30" value="<?php echo $name; ?>">
                                                <span id="name_status">
                                                    <img src="<?php echo getAssetLink('img/symbols/cross.gif'); ?>" style="vertical-align:middle;"/>
                                                </span>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td><?php echo \Bitefight\Library\Translate::_('home_register_password_label'); ?>:</td>
                                            <td>
                                                <input class="input" type="password" name="pass" id="pass" maxlength="20" value="<?php echo $pass; ?>">
                                            </td>
                                        </tr>
                                        <tr>
                                            <td><?php echo \Bitefight\Library\Translate::_('home_register_mail_label'); ?>:</td>
                                            <td>
                                                <input class="input" type="text" id="email" name="email" size="30" maxlength="120" value="<?php echo $email; ?>">
                                                <span id="email_status">
                                                    <img src="<?php echo getAssetLink('img/symbols/cross.gif'); ?>" style="vertical-align:middle;"/>
                                                </span>
                                            </td>
                                        </tr>
                                        <!--<tr>
                                            <td></td>
                                            <td><?php echo \Bitefight\Library\Translate::_('home_register_activation_info'); ?></td>
                                        </tr>-->
                                        <tr>
                                            <td colspan="2">
                                                <span class="fontsmall">
                                                    <input type="checkbox" id="agb" name="agb" value="ok" <?php if($agb) echo 'checked'; ?>><?php echo \Bitefight\Library\Translate::_('home_register_accept_agb'); ?>
                                                    <span id="agb_status" style="margin-left:12px;">
                                                        <img src="<?php echo getAssetLink('img/symbols/cross.gif'); ?>" style="vertical-align:middle;"/>
                                                    </span>
                                                </span>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td align="center" colspan="2">
                                                <div class="btn-left left">
                                                    <div class="btn-right">
                                                        <input type="submit" id="registerButton" class="btn" value="<?php echo strtolower(\Bitefight\Library\Translate::_('send')); ?>">
                                                    </div>
                                                </div>
                                            </td>
                                        </tr>
                                    </table>
                                </td>
                                <td valign="top">
                                    <img src="<?php echo getAssetLink('img/symbols/race'.$id.'.gif'); ?>" alt="<?php if($id == 1) echo \Bitefight\Library\Translate::_('vampire'); else echo \Bitefight\Library\Translate::_('werewolf'); ?>" >
                                </td>
                            </tr>
                        </table>
                    </form>
                </div>
            </div>
        </div>
        <div class="wrap-bottom-left">
            <div class="wrap-bottom-right">
                <div class="wrap-bottom-middle"></div>
            </div>
        </div>
    </div>

<?php endif; ?>