<?php if($id == 0): ?>

    <script language="JavaScript">
        p1 = new Image();
        p1.src = "<?php echo getAssetLink('img/symbols/race1loginen.gif'); ?>";
        p1x = new Image();
        p1x.src = "<?php echo getAssetLink('img/symbols/race1loginhoveren.gif'); ?>";
        p2 = new Image();
        p2.src = "<?php echo getAssetLink('img/symbols/race2loginen.gif'); ?>";
        p2x = new Image();
        p2x.src = "<?php echo getAssetLink('img/symbols/race2loginhoveren.gif'); ?>";
    </script>
    <div id="chooseRace">
        <div class="wrap-top-left clearfix">
            <div class="wrap-top-right clearfix">
                <div class="wrap-top-middle clearfix"></div>
            </div>
        </div>
        <div class="wrap-left clearfix">
            <div class="wrap-content wrap-right clearfix">
                <div class="table-wrap">
                    <table cellpadding="0" cellspacing="0" border="0" width="100%">
                        <tr>
                            <td width="40%" align="left">
                                <a href="<?php echo getUrl('register/1'); ?>" onfocus="if(this.blur)this.blur()"
                                   target="_top" onmouseover="document.pic1.src = p1x.src"
                                   onmouseout="document.pic1.src = p1.src">
                                    <img src="<?php echo getAssetLink('img/symbols/race1loginen.gif'); ?>" alt="Vampir"
                                         name="pic1" border="0">
                                </a>
                            </td>
                            <td width="20%">Choose your race!</td>
                            <td width="40%" align="right">
                                <a href="<?php echo getUrl('register/2'); ?>" onfocus="if(this.blur)this.blur()"
                                   target="_top" onmouseover="document.pic2.src = p2x.src"
                                   onmouseout="document.pic2.src = p2.src">
                                    <img src="<?php echo getAssetLink('img/symbols/race2loginen.gif'); ?>" alt="Werewolf"
                                         name="pic2" border="0">
                                </a>
                            </td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="wrap-bottom-left">
            <div class="wrap-bottom-right">
                <div class="wrap-bottom-middle"></div>
            </div>
        </div>
    </div>

<?php else: ?>

    <div id="register">
        <div class="wrap-top-left clearfix">
            <div class="wrap-top-right clearfix">
                <div class="wrap-top-middle clearfix"></div>
            </div>
        </div>
        <div class="wrap-left clearfix">
            <div class="wrap-content wrap-right clearfix">
                <h2><img src="<?php echo getAssetLink('img/symbols/race1small.gif'); ?>" alt=""/>Register</h2>
                <div class="table-wrap">
                    <script type="text/javascript">
                        $(function () {
                            var timer;
                            $("#name").keyup(function () {
                                if(timer) {
                                    clearTimeout(timer);
                                    timer = null
                                }
                                timer = setTimeout(function() {
                                    ajaxCheck("name");
                                }, 500)
                            });

                            $("#email").keyup(function () {
                                if(timer) {
                                    clearTimeout(timer);
                                    timer = null
                                }
                                timer = setTimeout(function() {
                                    ajaxCheck("email");
                                }, 500)
                            });

                            $("#agb").change(function () {
                                if ($("#agb").is(':checked')){
                                    $("#agb_status").html('<img src="/img/tick.gif"/>');
                                } else {
                                    $("#agb_status").html('<img src="/img/cross.gif"/>');
                                }
                            });
                        });

                        function ajaxCheck(name){
                            $.getJSON("/user/ajaxcheck",
                                $("#"+name).serialize(),
                                function(data){
                                    if (data.status){
                                        $("#"+name+"_status").html('<img src="<?php echo getAssetLink('img/tick.gif'); ?>" style="vertical-align:middle;"/>');
                                    } else {
                                        $("#"+name+"_status").html('<img src="<?php echo getAssetLink('img/cross.gif'); ?>" style="vertical-align:middle;"/><b style="color:yellow" class="fontsmall">'+data.messages+'</b>');
                                    }
                                })
                        }
                    </script>
                    <h3>BiteFight can be played for free.</h3>
                    <p>Please click "send" after filling out all given fields,<br> to join the game</p>
                    <form id="registerForm" name="registerForm" action="/user/register/0/1/save"  method="POST"><br>
                        <table cellpadding="0" cellspacing="0" border="0">
                            <tr>
                                <td align="center" valign="top">
                                    <table cellpadding="2" cellspacing="2" border="0" width="100%">
                                        <tr>
                                            <td>Choose your name:</td>
                                            <td><input class="input" type="text" id="name" name="name" size="30" MAXLENGTH="30" value=""><span id="name_status"><img src="/img/cross.gif" style="vertical-align:middle;"/></span></td>
                                        </tr>
                                        <tr>
                                            <td>Please enter a password:</td>
                                            <td><input class="input" type="password" name="pass" onkeyup="checkInput()" id="pass"  MAXLENGTH="20"  value="">
                                                <!--
                                                <script type="text/javascript">
                                                    document.write('<img src="http://s202.en.bitefight.gameforge.com/img/passsecure0.gif" name="seclevel" style="width: 86px; vertical-align:middle;" \/>');
                                                </script><span id="pass_status"><img src="/img/cross.gif" style="vertical-align:middle;"/></span>
                                                -->
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>Your e-mail address:</td>
                                            <td><input class="input" type="text" id="email" name="email" size="30" MAXLENGTH="120" value=""><span id="email_status"><img src="/img/cross.gif" style="vertical-align:middle;"/></span></td>
                                        </tr>
                                        <tr>
                                            <td></td>
                                            <td>An e-mail containing your activation link will be sent to your email address. Please activate the account within the next 3 days.</td>
                                        </tr>
                                        <tr>
                                            <td colspan="2">
                                                <span class="fontsmall"><input type="checkbox" id="agb" name="agb" value="ok">I accept the <a href="http://agbserver.gameforge.com/rewrite.php?game=bitefight&page=terms&lang=en"  class="copyright" target="blank" >Terms and Conditions</a> and the <a href="http://agbserver.gameforge.com/rewrite.php?game=bitefight&page=privacy&lang=en"  class="copyright" target="blank" >Privacy Policy</a>.<span id="agb_status" style="margin-left:12px;"><img src="/img/cross.gif" style="vertical-align:middle;"/></span></span>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td align="center" colspan="2">
                                                <div class="btn-left left"><div class="btn-right">
                                                        <input type="submit" id="registerButton" class="btn" value="send">
                                                    </div></div>
                                            </td>
                                        </tr>
                                    </table>
                                </td>
                                <td valign="top">
                                    <img src="/img/race1.gif" alt="Vampire" >

                                </td>
                            </tr>
                        </table>
                    </form>
                </div>
                <!-- CONTENT END -->
            </div>
        </div>
        <!-- box CONTENT END -->
        <!-- box FOOTER START -->
        <div class="wrap-bottom-left">
            <div class="wrap-bottom-right">
                <div class="wrap-bottom-middle"></div>
            </div>
        </div>
        <!-- box CONTENT END -->
    </div>
    <!-- box-model END --><script type="text/javascript">
        standard = new Image;
        unsecure = new Image;
        secure = new Image;
        highlysecure = new Image;
        standard.src = "<?php echo getAssetLink('img/passsecure0.gif'); ?>";
        unsecure.src = "<?php echo getAssetLink('img/passsecure1.gif'); ?>";
        secure.src = "<?php echo getAssetLink('img/passsecure2.gif'); ?>";
        highlysecure.src = "<?php echo getAssetLink('img/passsecure3.gif'); ?>";
        function checkInput() {
            var TestNumberOfChars = false;
            var TestUppercaseChars = false;
            var TestLowercaseChars = false;
            var TestDigits = false;
            var TestSpecialChars = false;
            var TestCounter = false;
            var TestWhiteSpaces = false;
            var TestSecondPassword = false;
            var counter = 0;
            hilfe = document.getElementById('pass').value;

            /* Passwort länger als 7 Zeichen*/
            if(hilfe.length >= 8) {
                if(!TestNumberOfChars) {
                    TestNumberOfChars = true;
                }
            } else {
                TestNumberOfChars = false;
            }
            if(hilfe.length < 5) {
                TestNumberOfChars = false;
            }

            if (hilfe.length < 3){
                $("#pass_status").html('<img src="/img/cross.gif" style="vertical-align:middle;"/>');
            } else if ($("#pass").val() == $("#name").val()) {
                $("#pass_status").html('<img src="/img/cross.gif" style="vertical-align:middle;"/>');
            } else {
                $("#pass_status").html('<img src="/img/tick.gif" style="vertical-align:middle;"/>');
            }

            /* Passwort enthält min. 2 Grossbuchstagben */
            if(hilfe.match(/[A-Z].*[A-Z]/)) {
                TestUppercaseChars = true;
            } else {
                TestUppercaseChars = false;
            }
            if(hilfe.length < 5) {
                TestUppercaseChars = false;
            }

            /* Passwort enthält min. 2 Kleinbuchstaben */
            if(hilfe.match(/[a-z].*[a-z]/)) {
                TestLowercaseChars = true;
            } else {
                TestLowercaseChars = false;
            }
            if(hilfe.length < 5) {
                TestLowercaseChars = false;
            }

            /* Passwort enthält min. 2 Zahlen */
            if(hilfe.match(/[0-9].*[0-9]/)) {
                TestDigits = true;
            } else {
                TestDigits = false;
            }
            if(hilfe.length < 5) {
                TestDigits = false;
            }

            /* Passwort enthält min. 2 Sonderzeichen */
            var specCharCounter = 0;
            if(hilfe.length > 0) {
                characters = hilfe.split("");
                for(var i = 0; i < characters.length; i++) {
                    singleChar = characters[i];
                    if(singleChar.match(/[^a-zA-Z0-9]/)) {
                        specCharCounter++;
                    }
                }
                if(specCharCounter >= 2) {
                    TestSpecialChars = true;
                } else {
                    TestSpecialChars = false;
                }
            }
            if(hilfe.length < 5) {
                TestSpecialChars = false;
            }

            /* Sonderprüfung */
            if(hilfe.match(/\s/)) {
                TestWhiteSpaces = true;
            } else {
                TestWhiteSpaces = false;
            }
            if(hilfe.length < 5) {
                TestWhiteSpaces = false;
            }

            /* Auswertung */
            if(TestUppercaseChars) { counter++; }
            if(TestLowercaseChars) { counter++; }
            if(TestDigits)         { counter++; }
            if(TestSpecialChars)   { counter++; }

            if(counter == 0) {
                window.document.images['seclevel'].src = standard.src;
            }
            if(counter == 1) {
                window.document.images['seclevel'].src = unsecure.src;
            }
            if(counter == 2) {
                window.document.images['seclevel'].src = secure.src;
            }
            if(counter == 3) {
                window.document.images['seclevel'].src = highlysecure.src;
            }
        }
        $(document).ready(function(){
            ajaxCheck("email");
        });
    </script>

<?php endif; ?>