<div id="clanExtern">
    <div class="wrap-top-left clearfix">
        <div class="wrap-top-right clearfix">
            <div class="wrap-top-middle clearfix"></div>
        </div>
    </div>
    <div class="wrap-left clearfix">
        <div class="wrap-content wrap-right clearfix">
            <h2><img src="<?php echo getAssetLink('img/symbols/race'.$user->race.'small.gif'); ?>" alt="">Send an application to a clan gasgas</h2>
            <script language="JavaScript">
                $(document).ready(function() {
                    var applicationText = document.getElementsByName('applicationText')[0];
                    CheckLen(applicationText);
                });

                function CheckLen(Target) {
                    var maxlength = "2000";
                    StrLen=Target.value.replace(/\r\n?/g, "\n").length;
                    if (StrLen==1&&Target.value.substring(0,1)==" ") {
                        Target.value="";
                        StrLen=0;
                    }
                    if (StrLen>maxlength ) {
                        Target.value=Target.value.substring(0,maxlength);
                        CharsLeft=0;
                    } else {
                        CharsLeft=maxlength-StrLen;
                    }
                    document.getElementById('charcount1').innerHTML=CharsLeft;
                }
            </script>
            <form method="POST">
                <input type="hidden" name="<?php echo $this->security->getTokenKey() ?>" value="<?php echo $this->security->getToken() ?>"/>
                <table width="100%">
                    <tbody>
                    <?php if(isset($form_sent)): ?>
                        <tr><td>Your application is going to be handed in now</td></tr>
                    <?php else: ?>
                        <?php if($clan->application_id): ?>
                            <tr>
                                <td class="no-bg">
                                    <div class="error">Warning:<p>You have already sent in an application to the following clan: <?php echo e($clan->name); ?> [<?php echo e($clan->tag); ?>]</p></div>
                                </td>
                            </tr>
                        <?php else: ?>
                            <tr>
                                <th>Text<br> ( <span id="charcount1">2000</span> Characters )</th>
                                <th><textarea onkeydown="CheckLen(this)" onkeyup="CheckLen(this)" onfocus="CheckLen(this)" onchange="CheckLen(this)" name="applicationText" cols="70" rows="5">Entire booty: <?php echo prettyNumber($user->s_booty); ?> Blood</textarea></th>
                            </tr>
                            <tr>
                                <td class="no-bg" colspan="2">
                                    <div class="btn-left left"><div class="btn-right">
                                            <input type="submit" class="btn" value="send">
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        <?php endif; ?>
                    <?php endif; ?>
                    </tbody>
                </table>
            </form>
        </div>
    </div>
    <div class="wrap-bottom-left">
        <div class="wrap-bottom-right">
            <div class="wrap-bottom-middle"></div>
        </div>
    </div>
</div>