<div id="clanExtern">
    <!-- box HEADER START -->
    <div class="wrap-top-left clearfix">
        <div class="wrap-top-right clearfix">
            <div class="wrap-top-middle clearfix"></div>
        </div>
    </div>
    <!-- box HEADER END -->
    <!-- box CONTENT START -->
    <div class="wrap-left clearfix">
        <div class="wrap-content wrap-right clearfix">
            <!-- CONTENT START -->
            <h2><img src="/img/symbols/race1small.gif" alt="">Send an application to a clan gasgas</h2>
            <script language="JavaScript">
                function init() {
                    var applicationText = document.getElementsByName('applicationText')[0];
                    CheckLen(applicationText);
                }

                function CheckLen(Target) {
                    var maxlength = "2000";
                    StrLen=Target.value.replace(/\r\n?/g, "\n").length;
                    if (StrLen==1&&Target.value.substring(0,1)==" ") {
                        Target.value="";
                        StrLen=0;
                    }
                    if (StrLen>maxlength ) {
                        Target.value=Target.value.substring(0,maxlength);
                        CharsLeft=0;
                    } else {
                        CharsLeft=maxlength-StrLen;
                    }
                    document.getElementById('charcount1').innerHTML=CharsLeft;
                }
            </script>
            <form action="http://s202.en.bitefight.gameforge.com/clan/apply/9269/?__token=71f7ea03b70c1f6d88a48adcf64a2805" method="POST">
                <table width="100%">
                    <tbody><tr>
                        <th>Text<br> ( <span id="charcount1">1979</span> Characters )</th>
                        <th><textarea onkeydown="CheckLen(this)" onkeyup="CheckLen(this)" onfocus="CheckLen(this)" onchange="CheckLen(this)" name="applicationText" cols="70" rows="5">Entire booty: 0 Blood</textarea></th>
                    </tr>
                    <tr>
                        <td class="no-bg" colspan="2">
                            <div class="btn-left left"><div class="btn-right">
                                    <input type="submit" class="btn" value="send">
                                </div></div>
                        </td>
                    </tr>
                    </tbody></table>
            </form>
            <!-- CONTENT END -->
        </div>
    </div>
    <!-- box CONTENT END -->
    <!-- box FOOTER START -->
    <div class="wrap-bottom-left">
        <div class="wrap-bottom-right">
            <div class="wrap-bottom-middle"></div>
        </div>
    </div>
    <!-- box CONTENT END -->
</div>

<div id="clanExtern">
    <!-- box HEADER START -->
    <div class="wrap-top-left clearfix">
        <div class="wrap-top-right clearfix">
            <div class="wrap-top-middle clearfix"></div>
        </div>
    </div>
    <!-- box HEADER END -->
    <!-- box CONTENT START -->
    <div class="wrap-left clearfix">
        <div class="wrap-content wrap-right clearfix">
            <!-- CONTENT START -->
            <h2><img src="/img/symbols/race1small.gif" alt="">Send an application to a clan gasgas</h2>
            <script language="JavaScript">
                function init() {
                }

                function CheckLen(Target) {
                    var maxlength = "2000";
                    StrLen=Target.value.replace(/\r\n?/g, "\n").length;
                    if (StrLen==1&&Target.value.substring(0,1)==" ") {
                        Target.value="";
                        StrLen=0;
                    }
                    if (StrLen>maxlength ) {
                        Target.value=Target.value.substring(0,maxlength);
                        CharsLeft=0;
                    } else {
                        CharsLeft=maxlength-StrLen;
                    }
                    document.getElementById('charcount1').innerHTML=CharsLeft;
                }
            </script>
            <form action="http://s202.en.bitefight.gameforge.com/clan/apply/9269/?__token=c14e1e9e0fcfb9b8a338a1144e750ca4" method="POST">
                <table width="100%">
                    <tbody><tr><td>Your application is going to be handed in now</td></tr>    </tbody></table>
            </form>
            <!-- CONTENT END -->
        </div>
    </div>
    <!-- box CONTENT END -->
    <!-- box FOOTER START -->
    <div class="wrap-bottom-left">
        <div class="wrap-bottom-right">
            <div class="wrap-bottom-middle"></div>
        </div>
    </div>
    <!-- box CONTENT END -->
</div>