<div class="btn-left left"><div class="btn-right">
        <a class="btn" href="/clan/index">back</a>
    </div></div>
<br class="clearfloat">
<div id="application">
    <!-- box HEADER START -->
    <div class="wrap-top-left clearfix">
        <div class="wrap-top-right clearfix">
            <div class="wrap-top-middle clearfix"></div>
        </div>
    </div>
    <!-- box HEADER END -->
    <!-- box CONTENT START -->
    <div class="wrap-left clearfix">
        <div class="wrap-content wrap-right clearfix">
            <!-- CONTENT START -->
            <h2><img src="/img/symbols/race1small.gif" alt="">Edit applications</h2>
            <div style="margin:15px auto 0; width:452px;">
                <p style="text-align:right">
                    <a class="left" href="/profile/player/81533" target="_new">osein2</a>
                    Tue, 24.01.2017 - 13:24:36				</p>
                <p>
                    Entire booty: 0 Blood				</p>

                <form class="clearfix" action="http://s202.en.bitefight.gameforge.com/clan/applications/81533?__token=95e2511e871ae7ded4a5cba159047cd1" method="post">
                    <p>Reason for rejection:</p>
                    <textarea name="abltext" cols="50" rows="5"></textarea><br>
                    <div class="btn-left left"><div class="btn-right">
                            <input class="btn" type="submit" name="abl" value="No way">
                        </div></div>
                    <div class="btn-left left"><div class="btn-right">
                            <input class="btn" type="submit" name="ann" value="OK, accepted">
                        </div></div>
                    <div class="btn-left left"><div class="btn-right">
                            <a class="btn" href="http://s202.en.bitefight.gameforge.com/msg/complain/capplication?__token=95e2511e871ae7ded4a5cba159047cd1&amp;id=2683&amp;cc=687640d">( report )</a>
                        </div></div>
                </form>
                <br class="clearfloat">
            </div>
            <!-- CONTENT END -->
        </div>
    </div>
    <!-- box CONTENT END -->
    <!-- box FOOTER START -->
    <div class="wrap-bottom-left">
        <div class="wrap-bottom-right">
            <div class="wrap-bottom-middle"></div>
        </div>
    </div>
    <!-- box CONTENT END -->
</div>