<?php if(!$user->clan_id): ?>
<div id="createClan">
    <div class="wrap-top-left clearfix"><div class="wrap-top-right clearfix"><div class="wrap-top-middle clearfix"></div></div></div>
    <div class="wrap-left clearfix">
        <div class="wrap-content wrap-right clearfix">
            <h2><img src="<?php echo getAssetLink('img/symbols/race'.$user->race.'small.gif'); ?>" alt="">Clan</h2>
            <div class="clearfix">
                <div class="btn-left left"><div class="btn-right"><a href="<?php echo getUrl('clan/create'); ?>" class="btn">Found a clan</a></div></div>
                <div class="btn-left left"><div class="btn-right"><a href="<?php echo getUrl('search'); ?>" class="btn">Search clans</a></div></div>
                <br class="clearfloat">
            </div>
        </div>
    </div>
    <div class="wrap-bottom-left"><div class="wrap-bottom-right"><div class="wrap-bottom-middle"></div></div></div>
</div>
<?php else: ?>
<div id="clanOverview">
    <div class="wrap-top-left clearfix">
        <div class="wrap-top-right clearfix">
            <div class="wrap-top-middle clearfix"></div>
        </div>
    </div>
    <div class="wrap-left clearfix">
        <div class="wrap-content wrap-right clearfix">
            <h2><img src="<?php echo getAssetLink('img/symbols/race'.$user->race.'small.gif'); ?>" alt=""> Clan [<?php echo e($clan->tag); ?>] (since <?php echo date('d.m.Y H:i', $clan->found_date); ?>)</h2>
            <div class="table-wrap">
                <table width="100%">
                    <tbody>
                    <tr>
                        <td class="no-bg" style="text-align:center;" rowspan="10" align="center">
                            <a href="http://s202.en.bitefight.gameforge.com/clan/logo"><img src="<?php echo getAssetLink('img/clan/'.$clan->logo_bg.'-'.$clan->logo_sym.'.png'); ?>" border="0"></a>
                        </td>
                    </tr>
                    <tr>
                        <td>Name</td>
                        <td><?php echo e($clan->name); ?></td>
                    </tr>
                    <tr>
                        <td>Homepage</td>
                        <td><?php if(strlen($clan->website) > 0): ?><a href="<?php echo e($clan->website); ?>"><?php echo e($clan->website); ?></a><?php else: ?>no clan page available<?php endif; ?></td>
                    </tr>
                    <tr>
                        <td>Total booty</td>
                        <td><?php echo prettyNumber($totalBlood); ?> Blood</td>
                    </tr>
                    <tr>
                        <td>Members</td>
                        <td><a href="http://s202.en.bitefight.gameforge.com/clan/memberlist/9267"><?php echo $member_count; ?> / <?php if($clan->stufe == 0) echo 1; else echo $clan->stufe * 3; ?> Member</a></td>
                    </tr>
                    <tr>
                        <td>Capital</td>
                        <td><?php echo prettyNumber($clan->capital); ?><img src="<?php echo getAssetLink('img/symbols/res2.gif'); ?>" title="Gold" align="absmiddle" border="0"></td>
                    </tr>
                    <tr>
                        <td>Your rank</td>
                        <td><?php echo e($rank->rank_name); ?></td>
                    </tr>
                    </tbody>
                </table>


                <h2><img alt="" src="<?php echo getAssetLink('img/symbols/race'.$user->race.'small.gif'); ?>"> Clan settings</h2>
                <p></p>
                <table width="100%">
                    <tbody>
                    <?php if($rank->id == 1 || $rank->id == 2): ?>
                    <tr><th colspan="2"><a href="http://s202.en.bitefight.gameforge.com/clan/change/description">add description</a></th></tr>
                    <tr><th colspan="2"><a href="<?php echo getUrl('clan/logo/background'); ?>">edit clan symbol</a></th></tr>
                    <tr><th colspan="2"><a href="http://s202.en.bitefight.gameforge.com/clan/change/homepage">set as homepage</a></th></tr>
                    <tr><th colspan="2"><a href="http://s202.en.bitefight.gameforge.com/clan/change/clanname">rename clan</a></th></tr>
                    <?php endif; ?>

                    <?php if($rank->send_clan_message): ?>
                    <tr><th colspan="2"><a href="http://s202.en.bitefight.gameforge.com/msg/clanmail">send a message to your clan</a></th></tr>
                    <?php endif; ?>

                    <?php if($rank->id == 1 || $rank->id == 2): ?>
                    <tr><th colspan="2"><a href="http://s202.en.bitefight.gameforge.com/clan/memberrights">manage members</a></th></tr>
                    <?php endif; ?>

                    <?php if($rank->spend_gold): ?>
                    <tr><th colspan="2"><a href="http://s202.en.bitefight.gameforge.com/clan/donationlist">view the donations made to your clan</a></th></tr>
                    <?php endif; ?>
                    </tbody>
                </table>
                <p></p>

                <h2><img alt="" src="<?php echo getAssetLink('img/symbols/race'.$user->race.'small.gif'); ?>"> Clan chat</h2>
                <script>
                    function ajaxLoadContent(targetSelector, targetAction, requestData, reloadCheck)
                    {
                        if ($(targetSelector).html() != '' && reloadCheck)
                        {
                            return;
                        }
                        $(targetSelector).html(
                            '<img src="/img/ajax/ajax_loader_large.gif" alt="loading.." />'
                        );

                        var successFunc = function(htmlContent)
                        {
                            $(targetSelector).html(htmlContent);

                            activateTooltipsForSelector(targetSelector);
                        };

                        ajaxSendRequestHtml(targetAction, requestData, successFunc);
                    }

                    function ajaxReplaceContent(targetSelector, targetAction, requestData)
                    {
                        var successFunc = function(htmlContent)
                        {
                            $(targetSelector).html(htmlContent);

                            activateTooltipsForSelector(targetSelector);
                        };

                        ajaxSendRequestHtml(targetAction, requestData, successFunc);
                    }

                    function ajaxSendRequestHtml(targetAction, requestData, successFunc)
                    {
                        $.get('/ajax/' + targetAction,
                            requestData,
                            successFunc,
                            'html');
                    }

                    function activateTooltipsForSelector(selector)
                    {
                        $(selector + ' .triggerTooltip').tooltip({
                            effect: 'toggle',
                            delay: 0,
                            position: 'center right',
                            relative: true
                        }).dynamic({ bottom: { direction: 'down', bounce: true } });
                    }
                </script>
                <div class="btn-left center">
                    <div class="btn-right">
                        <input type="button" id="clanChat" class="btn" href="#" value="Start Clan chat">
                    </div>
                </div>
                
                <h2><img alt="" src="<?php echo getAssetLink('img/symbols/race'.$user->race.'small.gif'); ?>"> Clan fights</h2>
                <p></p>
                <table id="clanwarsOverview" width="100%">
                    <tbody><tr>
                        <th colspan="2">The clan can only take part in clan fights when it has reached level 1 and has at least 3 members.</th>
                    </tr>
                    </tbody>
                </table>
                <p></p>
                <br>
                
                <h2><img alt="" src="<?php echo getAssetLink('img/symbols/race'.$user->race.'small.gif'); ?>"> Clan rituals</h2>
                <table width="100%" id="ritusOverview">
                    <tbody>
                    <tr>
                        <th>
                            <div class="btn-left center">
                                <div class="btn-right">
                                    <a class="btn" href="/clan/ritus/">
                                        Vocalise a clan ritual                            </a>
                                </div>
                            </div>
                        </th>
                    </tr>
                    </tbody>
                </table>
                There are currently no active rituals
                
                <h2><img alt="" src="<?php echo getAssetLink('img/symbols/race'.$user->race.'small.gif'); ?>"> Clan applications</h2>
                <p></p>
                <table width="100%">
                    <tbody>
                    <tr>
                        <th colspan="2">No Applications</th>
                        <th colspan="2"><a href="/clan/applications/">Application(1)</a></th>
                    </tr>
                    </tbody>
                </table>
                <p></p>


                <h2><img alt="" src="<?php echo getAssetLink('img/symbols/race'.$user->race.'small.gif'); ?>"> View of the clan hideout</h2>
                <div style="background: url('<?php echo getAssetLink('img/clan/hideout/bg1.jpg'); ?>') no-repeat center;">
                    <div style="position: relative; height: 584px;">
                        <div style="position: absolute; width:100%; text-align: center;">
                            <img src="<?php echo getAssetLink('img/clan/hideout/1_'.$clan->stufe.'.jpg'); ?>">
                        </div>
                    </div>
                </div>

                <?php if($rank->spend_gold): ?>
                <h2><img alt="" src="<?php echo getAssetLink('img/symbols/race'.$user->race.'small.gif'); ?>"> Clan hideout</h2>
                <p class="gold">Capital: <?php echo prettyNumber($clan->capital); ?><img src="<?php echo getAssetLink('img/symbols/res2.gif'); ?>" title="Gold" align="absmiddle" border="0"></p>
                <p></p>
                <table width="100%">
                    <tbody>
                    <?php for($i = 1; $i <= $clan->stufe; $i++): ?>
                    <tr>
                        <th align="right">Level: <?php echo $i; ?></th>
                        <th align="right">Members: <?php echo $i * 3; ?></th>
                        <th align="center">OK</th>
                    </tr>
                    <?php endfor; ?>
                    <?php if($clan->stufe < 18): ?>
                    <tr>
                        <th align="right">Level: <?php echo $clan->stufe + 1; ?></th>
                        <th align="right">Members: <?php echo ($clan->stufe + 1) * 3; ?></th>
                        <th align="center"><?php if($clan->capital>= getClanHideoutCost($clan->stufe + 1)): ?><a href="<?php echo getUrl('clan/hideout/upgrade?_tkey='.$this->security->getTokenKey().'&_token='.$this->security->getToken()); ?>"><?php endif; ?>The next level costs<br><?php echo prettyNumber(getClanHideoutCost($clan->stufe + 1)); ?><img src="<?php echo getAssetLink('img/symbols/res2.gif'); ?>" title="Gold" align="absmiddle" border="0"><?php if($clan->capital >= getClanHideoutCost($clan->stufe + 1)): ?></a><?php endif; ?></th>
                    </tr>
                    <?php endif; ?>
                    </tbody>
                </table>
                <p></p>
                <?php endif; ?>

                <h2><img alt="" src="<?php echo getAssetLink('img/symbols/race'.$user->race.'small.gif'); ?>"> Donate into the clan account</h2>
                <p class="gold">Your gold: <?php echo prettyNumber($user->gold); ?> <img src="<?php echo getAssetLink('img/symbols/res2.gif'); ?>" title="Gold" align="absmiddle" border="0"></p>
                <p></p>
                <form action="<?php echo getUrl('clan/donate'); ?>" method="POST">
                    <input type="hidden" name="<?php echo $this->security->getTokenKey() ?>"
                           value="<?php echo $this->security->getToken() ?>"/>
                    <table width="50%" align="center">
                        <tbody>
                            <tr>
                                <th>How much would you like to donate?</th>
                                <th align="right">
                                    <input type="text" name="donation" size="10" maxlength="10">
                                    <img src="<?php echo getAssetLink('img/symbols/res2.gif'); ?>" title="Gold" align="absmiddle" border="0">
                                </th>
                            </tr>
                            <tr>
                                <th colspan="2">
                                    <div class="btn-left center">
                                        <div class="btn-right">
                                            <input class="btn" type="submit" name="donate" value="donate">
                                        </div>
                                    </div>
                                </th>
                            </tr>
                        </tbody>
                    </table>
                </form>
                <p></p>

                <h2><img alt="" src="<?php echo getAssetLink('img/symbols/race'.$user->race.'small.gif'); ?>">
                    Clan description</h2>
                <p style="text-align:center">no description</p>

                <?php if($rank->read_message): ?>
                <h2><img alt="" src="<?php echo getAssetLink('img/symbols/race'.$user->race.'small.gif'); ?>"> messages</h2>
                <p></p>
                <table width="100%">
                    <tbody>
                    <?php if(count($clan_messages) > 0): ?>
                        <tr>
                            <th align="left">Sender</th>
                            <th align="left">Content</th>
                            <?php if($rank->delete_message): ?>
                            <th></th>
                            <?php endif; ?>
                        </tr>
                        <?php foreach($clan_messages as $message): ?>
                            <tr>
                                <td width="30%" align="left"><a href="<?php echo getUrl('profile/player/'.$message->user_id); ?>"><?php echo e($message->name); ?></a> (<?php echo e($message->rank_name); ?>)<br><?php echo date('D, d.m.Y - H:i:s', $message->clan_message_date); ?></td>
                                <td width="40%" align="left"><div style="width:300px;overflow-x:auto;"><?php echo e($message->clan_message); ?></div></td>
                                <?php if($rank->delete_message): ?>
                                <td>
                                    <div class="btn-left left">
                                        <div class="btn-right">
                                            <a class="btn" href="<?php echo getUrl('clan/deletemessage?message_id='.$message->id.'&_tkey='.$this->security->getTokenKey().'&_token='.$this->security->getToken()); ?>">delete message</a>
                                        </div>
                                    </div>
                                </td>
                                <?php endif; ?>
                            </tr>
                        <?php endforeach; ?>
                    <?php else: ?>
                        <tr>
                            <th colspan="3">no messages</th>
                        </tr>
                    <?php endif; ?>
                    </tbody>
                </table>
                <p></p>
                <?php endif; ?>

                <?php if($rank->write_message): ?>
                <h2><img alt="" src="<?php echo getAssetLink('img/symbols/race'.$user->race.'small.gif'); ?>"> new message (<span id="charcount" style="display:inline-block; margin-bottom:0px;">2000</span> Characters)</h2>
                <p>
                    <script language="JavaScript">
                        function CheckLen(Target)
                        {
                            var maxlength = 2000;
                            var StrLen = Target.value.length;
                            var CharsLeft;
                            if (StrLen == 1 && Target.value.substring(0, 1) == " ")
                            {
                                Target.value = "";
                                StrLen = 0;
                            }
                            if (StrLen > maxlength)
                            {
                                Target.value = Target.value.substring(0, maxlength);
                                CharsLeft = 0;
                            }
                            else
                            {
                                CharsLeft = maxlength - StrLen;
                            }
                            document.getElementById('charcount').innerHTML = CharsLeft;
                        }
                    </script>
                </p>
                    <table width="100%">
                    <tbody><tr>
                        <th colspan="2">
                            <form action="<?php echo getUrl('clan/newmessage'); ?>" method="POST">
                                <input type="hidden" name="<?php echo $this->security->getTokenKey() ?>"
                                       value="<?php echo $this->security->getToken() ?>"/>
                                <textarea name="message" rows="6" cols="60" onkeydown="CheckLen(this)" onkeyup="CheckLen(this)" onfocus="CheckLen(this)" onchange="CheckLen(this)"></textarea>
                                <br class="clearfloat">

                                <div class="btn-left center">
                                    <div class="btn-right">
                                        <input class="btn" type="submit" value="insert">
                                    </div>
                                </div>
                            </form>
                        </th>
                    </tr>
                    </tbody></table>
                <p></p>
                <?php endif; ?>

                <h2><img alt="" src="<?php echo getAssetLink('img/symbols/race'.$user->race.'small.gif'); ?>"> <?php if($user->clan_rank == 1) echo 'Disband'; else echo 'Leave'; ?> clan</h2>
                <div class="btn-left center">
                    <div class="btn-right">
                        <a href="<?php echo getUrl('clan/leave'); ?>" class="btn"><?php if($user->clan_rank == 1) echo 'Disband'; else echo 'Leave'; ?> clan</a>
                    </div>
                </div>
                <br class="clearfloat">
            </div>
        </div>
    </div>
    <div class="wrap-bottom-left">
        <div class="wrap-bottom-right">
            <div class="wrap-bottom-middle"></div>
        </div>
    </div>
</div>
<?php endif; ?>