<div class="btn-left left"><div class="btn-right"><a class="btn" href="/clan/index">back</a></div></div>
<br class="clearfloat">
<div id="handleMembers">
    <div class="wrap-top-left clearfix">
        <div class="wrap-top-right clearfix">
            <div class="wrap-top-middle clearfix"></div>
        </div>
    </div>
    <div class="wrap-left clearfix">
        <div class="wrap-content wrap-right clearfix">
            <h2><img src="/img/symbols/race1small.gif" alt="">manage members</h2>
            <b>osein2</b> Do you really want to kick this member?<br>
            <a href="https://s202-en.bitefight.gameforge.com:443/clan/memberrights/kick/81533?__token=ba8543d495e78704ff579382ac2c86f3">kick</a>
        </div>
    </div>
    <div class="wrap-bottom-left">
        <div class="wrap-bottom-right">
            <div class="wrap-bottom-middle"></div>
        </div>
    </div>
</div>