<div class="btn-left left"><div class="btn-right"><a class="btn" href="<?php echo getUrl('clan/memberrights'); ?>">back</a></div></div>
<br class="clearfloat">
<div id="handleMembers">
    <div class="wrap-top-left clearfix">
        <div class="wrap-top-right clearfix">
            <div class="wrap-top-middle clearfix"></div>
        </div>
    </div>
    <div class="wrap-left clearfix">
        <div class="wrap-content wrap-right clearfix">
            <h2><img src="<?php echo getAssetLink('img/symbols/race'.$user->race.'small.gif'); ?>" alt="">manage members</h2>
            <b><?php echo e($kick_user->name); ?></b> Do you really want to kick this member?<br>
            <a href="<?php echo getUrl('clan/memberrights/kick/'.$kick_user->id.'?_tkey='.$this->security->getTokenKey().'&_token='.$this->security->getToken()); ?>">kick</a>
        </div>
    </div>
    <div class="wrap-bottom-left">
        <div class="wrap-bottom-right">
            <div class="wrap-bottom-middle"></div>
        </div>
    </div>
</div>