<div class="btn-left left">
    <div class="btn-right">
        <a href="<?php echo getUrl('clan/index'); ?>" class="btn">back</a>
    </div>
</div>
<br class="clearfloat">
<div id="create">
    <div class="wrap-top-left clearfix">
        <div class="wrap-top-right clearfix">
            <div class="wrap-top-middle clearfix"></div>
        </div>
    </div>
    <div class="wrap-left clearfix">
        <div class="wrap-content wrap-right clearfix">
            <h2><img src="<?php echo getAssetLink('img/symbols/race'.$user->race.'small.gif'); ?>" alt=""><?php if($user->clan_rank == 1) echo 'Disband clan'; else echo 'Leave clan'; ?></h2>
            <div>
                <a href="<?php echo getUrl('clan/clanleave?_tkey='.$this->security->getTokenKey().'&_token='.$this->security->getToken()); ?>">Are you sure you want to <?php if($user->clan_rank == 1) echo 'disband'; else echo 'leave'; ?> the clan?</a></div>
        </div>
    </div>
    <div class="wrap-bottom-left">
        <div class="wrap-bottom-right">
            <div class="wrap-bottom-middle"></div>
        </div>
    </div>
</div>