<div class="btn-left left"><div class="btn-right"><a href="<?php echo getUrl('clan/'.$clan->id); ?>" class="btn">back</a></div></div>
<br class="clearfloat">
<div id="membreListExt">
    <div class="wrap-top-left clearfix">
        <div class="wrap-top-right clearfix">
            <div class="wrap-top-middle clearfix"></div>
        </div>
    </div>
    <div class="wrap-left clearfix">
        <div class="wrap-content wrap-right clearfix">
            <h2><img src="<?php echo getAssetLink('img/symbols/race'.$clan->race.'small.gif'); ?>" alt="">Member list: Clan <?php echo e($clan->name); ?></h2>
            <div class="table-wrap">
                <table width="100%">
                    <tbody><tr>
                        <td>Player</td>
                        <td>Level</td>
                        <td>Rank</td>
                        <td align="right">Blood</td>
                        <td align="right">captured Gold</td>
                        <td align="right">lost Gold</td>
                    </tr>
                    <?php foreach ($memberList as $member): ?>
                        <tr>
                            <td><a href="<?php echo getUrl('profile/player/'.$member->id); ?>"><?php echo e($member->name); ?></a></td>
                            <td><?php echo prettyNumber(getLevel($member->exp)); ?></td>
                            <td><?php echo e($member->rank_name); ?></td>
                            <td align="right"><?php echo prettyNumber($member->s_booty); ?></td>
                            <td align="right"><?php echo prettyNumber($member->s_gold_captured); ?></td>
                            <td align="right"><?php echo prettyNumber($member->s_gold_lost); ?></td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="wrap-bottom-left">
        <div class="wrap-bottom-right">
            <div class="wrap-bottom-middle"></div>
        </div>
    </div>
</div>