<div class="btn-left left"><div class="btn-right"><a class="btn" href="/clan/index">back</a></div></div>

<br class="clearfloat">

<div id="handleMembers">
    <div class="wrap-top-left clearfix">
        <div class="wrap-top-right clearfix">
            <div class="wrap-top-middle clearfix"></div>
        </div>
    </div>
    <div class="wrap-left clearfix">
        <div class="wrap-content wrap-right clearfix">
            <h2><img src="<?php echo getAssetLink('img/symbols/race'.$user->race.'small.gif'); ?>" alt="">manage members</h2>
            <div class="table-wrap">
                <form action="<?php echo getUrl('clan/memberrights/editrights'); ?>" method="POST">
                    <input type="hidden" name="<?php echo $this->security->getTokenKey() ?>" value="<?php echo $this->security->getToken() ?>"/>
                    <table width="100%">
                        <tbody>
                        <?php foreach($users as $clan_user): ?>
                            <tr>
                                <td><a class="member-name" href="<?php echo getUrl('profile/player/'.$clan_user->id); ?>"><?php echo e($clan_user->name); ?></a></td>
                                <td>
                                    <?php if($user_rank->add_members && $clan_user->id != $user->id): ?>
                                    <div class="btn-left left"><div class="btn-right"><a class="btn" href="<?php echo getUrl('clan/memberrights/kickuser/'.$clan_user->id.'?_tkey='.$this->security->getTokenKey().'&_token='.$this->security->getToken()); ?>">kick</a></div></div>
                                    <?php endif; ?>
                                    <?php if($user->clan_rank == 1 && $clan_user->id != $user->id): ?>
                                    <div class="btn-left left">
                                        <div class="btn-right">
                                            <a class="btn" href="<?php echo getUrl('clan/memberrights/setowner/'.$clan_user->id.'?_tkey='.$this->security->getTokenKey().'&_token='.$this->security->getToken()); ?>">
                                                <?php if(isset($declare_master_form) && $declare_master_form == $clan_user->id): ?>
                                                <font color="yellow"> ---&gt;Declare a master&lt;--- </font>
                                                <?php else: ?>
                                                Declare a master
                                                <?php endif; ?>
                                            </a>
                                        </div>
                                    </div>
                                    <?php endif; ?>
                                </td>
                                <td>
                                    <select name="users[<?php echo $clan_user->id; ?>]" size="1" <?php if($clan_user->rank_id == 1) echo 'disabled=""'; ?>>
                                        <?php foreach ($ranks as $rank): ?>
                                        <option value="<?php echo $rank->id; ?>" <?php if($clan_user->rank_id == $rank->id) echo 'selected=""'; ?>>
                                            <?php echo e($rank->rank_name); ?>
                                        </option>
                                        <?php endforeach; ?>
                                    </select>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                        </tbody></table>
                    <div class="btn-left right"><div class="btn-right"><input class="btn" type="submit" value="Save"></div></div>
                    <br class="clearfloat">
                </form>
            </div>
            <h3>add rank</h3>
            <form id="addRank" class="clearfix" action="<?php echo getUrl('clan/memberrights/addrank'); ?>" method="POST">
                <input type="hidden" name="<?php echo $this->security->getTokenKey() ?>" value="<?php echo $this->security->getToken() ?>"/>
                <label>Name</label>
                <input type="text" name="newRank" size="30" maxlength="30">
                <div class="btn-left left"><div class="btn-right"><input class="btn" type="submit" value="add"></div></div>
            </form>
        </div>
    </div>
    <div class="wrap-bottom-left">
        <div class="wrap-bottom-right">
            <div class="wrap-bottom-middle"></div>
        </div>
    </div>
</div>

<div id="handleRank">
    <div class="wrap-top-left clearfix">
        <div class="wrap-top-right clearfix">
            <div class="wrap-top-middle clearfix"></div>
        </div>
    </div>
    <div class="wrap-left clearfix">
        <div class="wrap-content wrap-right clearfix">
            <h2><img src="<?php echo getAssetLink('img/symbols/race'.$user->race.'small.gif'); ?>" alt="">rank options</h2>
            <form action="<?php echo getUrl('clan/memberrights/editranks'); ?>" method="POST">
                <input type="hidden" name="<?php echo $this->security->getTokenKey() ?>" value="<?php echo $this->security->getToken() ?>"/>
                <div class="info">
                    <b>Please remember that seals can only belong to strong clans:</b><br>
                    A clan needs at least 3 members to be able to own a seal.<br>
                    A clan needs at least 3 members to be able to fight for a seal.<br>
                    A clan needs at least 6 members to be able to carry out seal rituals.
                </div>
                <table width="100%">
                    <tbody>
                    <tr>
                        <td class="c">Name</td>
                        <td class="c" align="center">
                            <img src="<?php echo getAssetLink('img/clan/newsread.gif'); ?>" alt="read messages" title="read messages">
                        </td>
                        <td class="c" align="center">
                            <img src="<?php echo getAssetLink('img/clan/newswrite.gif'); ?>" alt="Write message" title="Write message">
                        </td>
                        <td class="c" align="center">
                            <img src="<?php echo getAssetLink('img/clan/clannewsread.gif'); ?>" alt="Read Clan Messages" title="Read Clan Messages">
                        </td>
                        <td class="c" align="center">
                            <img src="<?php echo getAssetLink('img/clan/useradd.gif'); ?>" alt="add members" title="add members">
                        </td>
                        <td class="c" align="center">
                            <img src="<?php echo getAssetLink('img/clan/newsdel.gif'); ?>" alt="delete message" title="delete message">
                        </td>
                        <td class="c" align="center">
                            <img src="<?php echo getAssetLink('img/clan/clannewswrite.gif'); ?>" alt="send a message to your clan" title="send a message to your clan">
                        </td>
                        <td class="c" align="center">
                            <img src="<?php echo getAssetLink('img/clan/gold.gif'); ?>" alt="Spend gold" title="Spend gold">
                        </td>
                        <td class="c" align="center">
                            <img src="<?php echo getAssetLink('img/clan/warlord.gif'); ?>" alt="War minister" title="War minister">
                        </td>
                        <td class="c" align="center">
                            <img src="<?php echo getAssetLink('img/clan/clanritus.gif'); ?>" alt="Vocalise a clan ritual" title="Vocalise a clan ritual">
                        </td>
                    </tr>
                    <?php foreach ($ranks as $rank): ?>
                        <tr>
                            <th>
                                <?php echo $rank->rank_name; ?>
                                <?php if($rank->id > 3): ?>
                                <br>
                                <a href="<?php echo getUrl('clan/memberrights/deleterank/'.$rank->id.'?_tkey='.$this->security->getTokenKey().'&_token='.$this->security->getToken()); ?>">(delete)</a>
                                <?php endif; ?>
                            </th>
                            <th><input type="checkbox" <?php if($rank->read_message) echo 'checked=""'; ?> <?php if($rank->clan_id == 0) echo 'disabled=""'; ?> name="ranks[<?php echo $rank->id; ?>][read_message]"></th>
                            <th><input type="checkbox" <?php if($rank->write_message) echo 'checked=""'; ?> <?php if($rank->clan_id == 0) echo 'disabled=""'; ?> name="ranks[<?php echo $rank->id; ?>][write_message]"></th>
                            <th><input type="checkbox" <?php if($rank->read_clan_message) echo 'checked=""'; ?> <?php if($rank->clan_id == 0) echo 'disabled=""'; ?> name="ranks[<?php echo $rank->id; ?>][read_clan_message]"></th>
                            <th><input type="checkbox" <?php if($rank->add_members) echo 'checked=""'; ?> <?php if($rank->clan_id == 0) echo 'disabled=""'; ?> name="ranks[<?php echo $rank->id; ?>][add_members]"></th>
                            <th><input type="checkbox" <?php if($rank->delete_message) echo 'checked=""'; ?> <?php if($rank->clan_id == 0) echo 'disabled=""'; ?> name="ranks[<?php echo $rank->id; ?>][delete_message]"></th>
                            <th><input type="checkbox" <?php if($rank->send_clan_message) echo 'checked=""'; ?> <?php if($rank->clan_id == 0) echo 'disabled=""'; ?> name="ranks[<?php echo $rank->id; ?>][send_clan_message]"></th>
                            <th><input type="checkbox" <?php if($rank->spend_gold) echo 'checked=""'; ?> <?php if($rank->clan_id == 0) echo 'disabled=""'; ?> name="ranks[<?php echo $rank->id; ?>][spend_gold]"></th>
                            <th><input type="checkbox" <?php if($rank->war_minister) echo 'checked=""'; ?> <?php if($rank->clan_id == 0) echo 'disabled=""'; ?> name="ranks[<?php echo $rank->id; ?>][war_minister]"></th>
                            <th><input type="checkbox" <?php if($rank->vocalise_ritual) echo 'checked=""'; ?> <?php if($rank->clan_id == 0) echo 'disabled=""'; ?> name="ranks[<?php echo $rank->id; ?>][vocalise_ritual]"></th>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
                <div class="btn-left right"><div class="btn-right"><input class="btn" name="rs" type="submit" value="Save"></div></div>
                <br class="clearfloat">
            </form>
        </div>
    </div>
    <div class="wrap-bottom-left">
        <div class="wrap-bottom-right">
            <div class="wrap-bottom-middle"></div>
        </div>
    </div>
</div>