<div class="btn-left left">
    <div class="btn-right"> <a class="btn" href="/clan/index">
            back		</a> </div>
</div>
<br class="clearfloat">
<div id="handleMembers">
    <!-- box HEADER START -->
    <div class="wrap-top-left clearfix">
        <div class="wrap-top-right clearfix">
            <div class="wrap-top-middle clearfix"></div>
        </div>
    </div>
    <!-- box HEADER END -->
    <!-- box CONTENT START -->
    <div class="wrap-left clearfix">
        <div class="wrap-content wrap-right clearfix">
            <!-- CONTENT START -->
            <h2><img src="/img/symbols/race1small.gif" alt="">manage members</h2>

            <div class="table-wrap">
                <form action="http://s202.en.bitefight.gameforge.com/clan/memberrights?__token=804f83589d2b40ca0d0ad850585b1891" method="POST">
                    <table width="100%">
                        <tbody><tr>
                            <td><a class="member-name" href="/profile/player/81524">
                                    osein					</a></td>
                            <td></td>
                            <td>
                                <select name="zn81524" size="1" disabled=""><option>Master </option><option value="2">
                                        Admin						</option><option value="3">
                                        Biter											</option></select>
                            </td>
                        </tr>
                        <tr>
                            <td><a class="member-name" href="/profile/player/81533">
                                    osein2					</a></td>
                            <td> 					<div class="btn-left left">
                                    <div class="btn-right">
                                        <a class="btn" href="http://s202.en.bitefight.gameforge.com/clan/memberrights/kickquestion/81533?__token=804f83589d2b40ca0d0ad850585b1891">
                                            kick							</a>
                                    </div>
                                </div>
                                <div class="btn-left left">
                                    <div class="btn-right">
                                        <a class="btn" href="http://s202.en.bitefight.gameforge.com/clan/memberrights/setowner/81533?__token=804f83589d2b40ca0d0ad850585b1891">
                                            Declare a master							</a>
                                    </div>
                                </div>
                            </td>
                            <td>
                                <select name="zn81533" size="1">  <option value="2">
                                        Admin						</option><option value="3" selected="">
                                        Biter											</option></select>
                            </td>
                        </tr>
                        </tbody></table>
                    <div class="btn-left right"><div class="btn-right">
                            <input class="btn" type="submit" value="Save">
                        </div></div>
                    <br class="clearfloat">
                </form>
            </div>
            <h3>add rank</h3>
            <form id="addRank" class="clearfix" action="http://s202.en.bitefight.gameforge.com/clan/memberrights?__token=804f83589d2b40ca0d0ad850585b1891" method="POST">
                <label>Name</label>
                <input type="text" name="newRank" size="30" maxlength="30">
                <div class="btn-left left"><div class="btn-right">
                        <input class="btn" type="submit" value="add">
                    </div></div>
            </form>
            <!-- CONTENT END -->
        </div>
    </div>
    <!-- box CONTENT END -->
    <!-- box FOOTER START -->
    <div class="wrap-bottom-left">
        <div class="wrap-bottom-right">
            <div class="wrap-bottom-middle"></div>
        </div>
    </div>
    <!-- box CONTENT END -->
</div>

<div id="handleMembers">
    <!-- box HEADER START -->
    <div class="wrap-top-left clearfix">
        <div class="wrap-top-right clearfix">
            <div class="wrap-top-middle clearfix"></div>
        </div>
    </div>
    <!-- box HEADER END -->
    <!-- box CONTENT START -->
    <div class="wrap-left clearfix">
        <div class="wrap-content wrap-right clearfix">
            <!-- CONTENT START -->
            <h2><img src="/img/symbols/race1small.gif" alt="">manage members</h2>

            <div class="table-wrap">
                <form action="http://s202.en.bitefight.gameforge.com/clan/memberrights?__token=7822a5135b55817cc90b816e673046e5" method="POST">
                    <table width="100%">
                        <tbody><tr>
                            <td><a class="member-name" href="/profile/player/81524">
                                    osein					</a></td>
                            <td></td>
                            <td>
                                <select name="zn81524" size="1" disabled=""><option>Master </option><option value="2">
                                        Admin						</option><option value="3">
                                        Biter											</option></select>
                            </td>
                        </tr>
                        <tr>
                            <td><a class="member-name" href="/profile/player/81533">
                                    osein2					</a></td>
                            <td> 					<div class="btn-left left">
                                    <div class="btn-right">
                                        <a class="btn" href="http://s202.en.bitefight.gameforge.com/clan/memberrights/kickquestion/81533?__token=7822a5135b55817cc90b816e673046e5">
                                            kick							</a>
                                    </div>
                                </div>
                                <div class="btn-left left">
                                    <div class="btn-right">
                                        <a class="btn" href="http://s202.en.bitefight.gameforge.com/clan/memberrights/setownerconf/81533?__token=7822a5135b55817cc90b816e673046e5"><font color="yellow"> ---&gt;Declare a master&lt;--- </font></a>
                                    </div>
                                </div>
                            </td>
                            <td>
                                <select name="zn81533" size="1">  <option value="2">
                                        Admin						</option><option value="3" selected="">
                                        Biter											</option></select>
                            </td>
                        </tr>
                        </tbody></table>
                    <div class="btn-left right"><div class="btn-right">
                            <input class="btn" type="submit" value="Save">
                        </div></div>
                    <br class="clearfloat">
                </form>
            </div>
            <h3>add rank master yapınca eski master admin oluyor</h3>
            <form id="addRank" class="clearfix" action="http://s202.en.bitefight.gameforge.com/clan/memberrights?__token=" method="POST">
                <label>Name</label>
                <input type="text" name="newRank" size="30" maxlength="30">
                <div class="btn-left left"><div class="btn-right"><input class="btn" type="submit" value="add"></div></div>
            </form>
        </div>
    </div>
    <div class="wrap-bottom-left">
        <div class="wrap-bottom-right">
            <div class="wrap-bottom-middle"></div>
        </div>
    </div>
</div>

<div id="handleRank">
    <div class="wrap-top-left clearfix">
        <div class="wrap-top-right clearfix">
            <div class="wrap-top-middle clearfix"></div>
        </div>
    </div>
    <div class="wrap-left clearfix">
        <div class="wrap-content wrap-right clearfix">
            <h2><img src="/img/symbols/race1small.gif" alt="">rank options</h2>
            <form action="http://s202.en.bitefight.gameforge.com/clan/memberrights?__token=804f83589d2b40ca0d0ad850585b1891" method="POST">
                <div class="info">
                    <b>Please remember that seals can only belong to strong clans:</b><br>
                    A clan needs at least 3 members to be able to own a seal.<br>
                    A clan needs at least 3 members to be able to fight for a seal.<br>
                    A clan needs at least 6 members to be able to carry out seal rituals.
                </div>
                <table width="100%">
                    <tbody>
                    <tr>
                        <td class="c">Name</td>
                        <td class="c" align="center">
                            <img src="/img/newsread.gif" alt="read messages" title="read messages">
                        </td>
                        <td class="c" align="center">
                            <img src="/img/newswrite.gif" alt="Write message" title="Write message">
                        </td>
                        <td class="c" align="center">
                            <img src="/img/clannewsread.gif" alt="Read Clan Messages" title="Read Clan Messages">
                        </td>
                        <td class="c" align="center">
                            <img src="/img/useradd.gif" alt="add members" title="add members">
                        </td>
                        <td class="c" align="center">
                            <img src="/img/newsdel.gif" alt="delete message" title="delete message">
                        </td>
                        <td class="c" align="center">
                            <img src="/img/clannewswrite.gif" alt="send a message to your clan" title="send a message to your clan">
                        </td>
                        <td class="c" align="center">
                            <img src="/img/gold.gif" alt="Spend gold" title="Spend gold">
                        </td>
                        <td class="c" align="center">
                            <img src="/img/warlord.gif" alt="War minister" title="War minister">
                        </td>
                        <td class="c" align="center">
                            <img src="/img/clanritus.gif" alt="Vocalise a clan ritual" title="Vocalise a clan ritual">
                        </td>
                    </tr>
                    <tr>
                        <th>Master</th>
                        <th><input type="checkbox" checked="" disabled=""></th>
                        <th><input type="checkbox" checked="" disabled=""></th>
                        <th><input type="checkbox" checked="" disabled=""></th>
                        <th><input type="checkbox" checked="" disabled=""></th>
                        <th><input type="checkbox" checked="" disabled=""></th>
                        <th><input type="checkbox" checked="" disabled=""></th>
                        <th><input type="checkbox" checked="" disabled=""></th>
                        <th><input type="checkbox" checked="" disabled=""></th>
                        <th><input type="checkbox" checked="" disabled=""></th>
                    </tr>
                    <tr>
                        <th>Admin</th>
                        <th><input type="checkbox" checked="" disabled=""></th>
                        <th><input type="checkbox" checked="" disabled=""></th>
                        <th><input type="checkbox" checked="" disabled=""></th>
                        <th><input type="checkbox" checked="" disabled=""></th>
                        <th><input type="checkbox" checked="" disabled=""></th>
                        <th><input type="checkbox" checked="" disabled=""></th>
                        <th><input type="checkbox" checked="" disabled=""></th>
                        <th><input type="checkbox" checked="" disabled=""></th>
                        <th><input type="checkbox" checked="" disabled=""></th>
                    </tr>
                    <tr>
                        <th>Biter</th>
                        <th><input type="checkbox" disabled=""></th>
                        <th><input type="checkbox" disabled=""></th>
                        <th><input type="checkbox" disabled=""></th>
                        <th><input type="checkbox" disabled=""></th>
                        <th><input type="checkbox" disabled=""></th>
                        <th><input type="checkbox" disabled=""></th>
                        <th><input type="checkbox" disabled=""></th>
                        <th><input type="checkbox" disabled=""></th>
                        <th><input type="checkbox" disabled=""></th>
                    </tr>
                    </tbody>
                </table>
                <div class="btn-left right"><div class="btn-right"><input class="btn" name="rs" type="submit" value="Save"></div></div>
                <br class="clearfloat">
            </form>
        </div>
    </div>
    <div class="wrap-bottom-left">
        <div class="wrap-bottom-right">
            <div class="wrap-bottom-middle"></div>
        </div>
    </div>
</div>