<div id="clanExtern">
    <div class="wrap-top-left clearfix">
        <div class="wrap-top-right clearfix">
            <div class="wrap-top-middle clearfix"></div>
        </div>
    </div>
    <div class="wrap-left clearfix">
        <div class="wrap-content wrap-right clearfix">
            <h2>
                <img src="<?php echo getAssetLink('img/symbols/race'.$clan->race.'small.gif'); ?>" alt="">Clan [<?php echo e($clan->tag); ?>]
            </h2>
            <div class="table-wrap">
                <table width="100%">
                    <tbody>
                    <tr>
                        <td class="clan-logo no-bg" rowspan="10">
                            <img src="<?php echo getAssetLink('img/clan/'.$clan->logo_bg.'-'.$clan->logo_sym.'.png'); ?>" border="0">
                        </td>
                    </tr>
                    <tr>
                        <td>Name</td>
                        <td><?php echo e($clan->name); ?></td>
                    </tr>
                    <tr>
                        <td>Homepage</td>
                        <td>
                            <?php if(strlen($clan->website)): ?>
                            <a href="<?php echo getUrl('clan/view/homepage/'.$clan->id.'?_token='.$this->security->getToken().'&_tkey='.$this->security->getTokenKey()); ?>" target="_blank"><?php echo e($clan->website); ?></a>	(<?php echo $clan->website_counter; ?> Visitors)
                            <?php else: ?>
                            no clan page available
                            <?php endif; ?>
                        </td>
                    </tr>
                    <tr>
                        <td>Total booty</td>
                        <td><?php echo prettyNumber($clan->total_booty); ?> Meat</td>
                    </tr>
                    <tr>
                        <td>Members</td>
                        <td>
                            <a href="https://s202-en.bitefight.gameforge.com:443/clan/memberlistExt/9305"><?php echo $clan->member_count; ?> / <?php echo $clan->max_members; ?> Member</a>
                        </td>
                    </tr>
                    <tr>
                        <td>Capital</td>
                        <td><?php echo prettyNumber($clan->gold_count); ?> <img src="https://s202-en.bitefight.gameforge.com:443/img/symbols/res2.gif" title="Gold" align="absmiddle" border="0"></td>
                    </tr>
                    <?php if($user->clan_id < 1 && $clan->member_count < $clan->max_members): ?>
                        <tr>
                            <td class="no-bg" colspan="2">
                                <div class="btn-left left"><div class="btn-right">
                                        <a class="btn" href="<?php echo getUrl('clan/apply/'.$clan->id); ?>">apply to a clan</a>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    <?php endif; ?>
                    </tbody>
                </table>
                <h2><img alt="" src="<?php echo getAssetLink('img/symbols/race'.$clan->race.'small.gif'); ?>">View of the clan hideout</h2>
                <p>
                </p>
                <table cellpadding="0" cellspacing="0" border="0" width="584" align="center">
                    <tbody><tr>
                        <td style="background: url(<?php echo getAssetLink('img/clan/hideout/bg1.jpg'); ?>) no-repeat center;" align="center">
                            <img src="<?php echo getAssetLink('img/clan/hideout/1_'.$clan->stufe.'.jpg'); ?>">
                        </td>
                    </tr>
                    </tbody>
                </table>
                <br>
                <h2>
                    <img alt="" src="<?php echo getAssetLink('img/symbols/race'.$clan->race.'small.gif'); ?>">Clan description <!--<a href="https://s202-en.bitefight.gameforge.com:443/msg/complain/cprofile?id=9305&amp;cc=db627f2" class="copyright">(report)</a>-->
                </h2>
                <p style="text-align:center">
                    <?php echo $clan->descriptionHtml; ?>
                </p>
            </div>
        </div>
    </div>
    <div class="wrap-bottom-left">
        <div class="wrap-bottom-right">
            <div class="wrap-bottom-middle"></div>
        </div>
    </div>
</div>